use std::fmt::{Arguments, Write as _};

use crate::error::{DiaggenError, DiaggenResult};
use crate::model::{Catalog, KindMap, MapMode, MapTarget};

pub fn render_catalog(catalog: &Catalog) -> DiaggenResult<String> {
    let enum_name = catalog
        .enum_name
        .as_ref()
        .ok_or_else(|| DiaggenError(format!("catalog `{}` missing enum name", catalog.owner)))?;
    let mut out = String::new();
    out.push_str("// @generated by musi_diaggen. Do not edit by hand.\n\n");
    push_fmt(&mut out, format_args!("use super::{enum_name};\n\n"));
    out.push_str("struct CatalogEntry {\n");
    push_fmt(&mut out, format_args!("    kind: {enum_name},\n"));
    out.push_str("    code: u16,\n");
    out.push_str("    message: &'static str,\n");
    out.push_str("    primary: &'static str,\n");
    out.push_str("    help: Option<&'static str>,\n");
    out.push_str("}\n\n");
    out.push_str("const ENTRIES: &[CatalogEntry] = &[\n");
    for entry in &catalog.entries {
        out.push_str("    CatalogEntry {\n");
        push_fmt(
            &mut out,
            format_args!("        kind: {enum_name}::{},\n", entry.kind),
        );
        push_fmt(&mut out, format_args!("        code: {},\n", entry.code));
        push_fmt(
            &mut out,
            format_args!("        message: \"{}\",\n", rust_string(&entry.message)),
        );
        push_fmt(
            &mut out,
            format_args!("        primary: \"{}\",\n", rust_string(&entry.primary)),
        );
        match &entry.help {
            Some(help) => push_fmt(
                &mut out,
                format_args!("        help: Some(\"{}\"),\n", rust_string(help)),
            ),
            None => out.push_str("        help: None,\n"),
        }
        out.push_str("    },\n");
    }
    out.push_str("];\n\n");
    push_fmt(
        &mut out,
        format_args!(
            "fn entry(kind: {enum_name}) -> &'static CatalogEntry {{\n    ENTRIES\n        .iter()\n        .find(|entry| entry.kind == kind)\n        .expect(\"missing generated diagnostic catalog entry\")\n}}\n\n"
        ),
    );
    push_fmt(
        &mut out,
        format_args!("pub fn code(kind: {enum_name}) -> u16 {{\n    entry(kind).code\n}}\n\n"),
    );
    push_fmt(
        &mut out,
        format_args!(
            "pub fn message(kind: {enum_name}) -> &'static str {{\n    entry(kind).message\n}}\n\n"
        ),
    );
    push_fmt(
        &mut out,
        format_args!(
            "pub fn primary(kind: {enum_name}) -> &'static str {{\n    entry(kind).primary\n}}\n\n"
        ),
    );
    push_fmt(
        &mut out,
        format_args!(
            "pub fn help(kind: {enum_name}) -> Option<&'static str> {{\n    entry(kind).help\n}}\n\n"
        ),
    );
    push_fmt(
        &mut out,
        format_args!(
            "pub fn from_code(raw: u16) -> Option<{enum_name}> {{\n    ENTRIES\n        .iter()\n        .find(|entry| entry.code == raw)\n        .map(|entry| entry.kind)\n}}\n"
        ),
    );
    for map in &catalog.maps {
        out.push('\n');
        render_map(&mut out, enum_name, map);
    }
    Ok(out)
}

fn render_map(out: &mut String, enum_name: &str, map: &KindMap) {
    let return_type = match map.mode {
        MapMode::Required => enum_name.to_owned(),
        MapMode::Option => format!("Option<{enum_name}>"),
    };
    push_fmt(
        out,
        format_args!(
            "pub const fn {}(source: {}{}) -> {return_type} {{\n    match source {{\n",
            map.name,
            if map.source_by_value { "" } else { "&" },
            map.source_type
        ),
    );
    let mut index = 0;
    while index < map.cases.len() {
        let start = index;
        let target = &map.cases[start].target;
        index += 1;
        while index < map.cases.len() && map.cases[index].target == *target {
            index += 1;
        }
        render_map_arm(out, enum_name, map, start, index);
    }
    out.push_str("    }\n}\n");
}

fn render_map_arm(out: &mut String, enum_name: &str, map: &KindMap, start: usize, end: usize) {
    out.push_str("        ");
    for (offset, case) in map.cases[start..end].iter().enumerate() {
        if offset > 0 {
            out.push_str("\n        | ");
        }
        push_fmt(out, format_args!("{}::{}", map.source_type, case.pattern));
    }
    out.push_str(" => ");
    render_map_target(out, enum_name, map.mode, &map.cases[start].target);
    out.push_str(",\n");
}

fn render_map_target(out: &mut String, enum_name: &str, mode: MapMode, target: &MapTarget) {
    match (mode, target) {
        (MapMode::Option, MapTarget::None) => out.push_str("None"),
        (MapMode::Option, MapTarget::Kind(kind)) => {
            push_fmt(out, format_args!("Some({enum_name}::{kind})"));
        }
        (MapMode::Required, MapTarget::Kind(kind)) => {
            push_fmt(out, format_args!("{enum_name}::{kind}"));
        }
        (MapMode::Required, MapTarget::None) => {
            out.push_str("compile_error!(\"invalid required diagnostic map target\")");
        }
    }
}

fn push_fmt(out: &mut String, args: Arguments<'_>) {
    out.write_fmt(args)
        .expect("write generated diagnostics text");
}

fn rust_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic)]
mod tests;
