import type { RawBookPageDefinition } from "../../types";

export const cCppDeveloperPages = [
	{
		id: "c-cpp-overview",
		partId: "developers",
		path: "/docs/book/developers/c-cpp/overview",
		aliases: [
			"/docs/book/developers/guides/c-cpp/overview",
			"/docs/book/developers/c/overview",
			"/docs/book/developers/cpp/overview",
			"/docs/book/developers/c-plus-plus/overview",
			"/docs/language/developers/c-cpp/overview",
			"/learn/language/developers/c-cpp/overview",
			"/docs/language/developers/c/overview",
			"/learn/language/developers/c/overview",
			"/docs/language/developers/cpp/overview",
			"/learn/language/developers/cpp/overview",
		],
		sourcePath: "docs/what/language/developers/c-cpp/overview.md",
		questions: [],
	},
	{
		id: "c-cpp-values-functions-expressions",
		partId: "developers",
		path: "/docs/book/developers/c-cpp/values-functions-expressions",
		aliases: [
			"/docs/book/developers/guides/c-cpp/values-functions-expressions",
			"/docs/book/developers/c/values-functions-expressions",
			"/docs/book/developers/cpp/values-functions-expressions",
			"/docs/book/developers/c-plus-plus/values-functions-expressions",
			"/docs/language/developers/c-cpp/values-functions-expressions",
			"/learn/language/developers/c-cpp/values-functions-expressions",
		],
		sourcePath:
			"docs/what/language/developers/c-cpp/values-functions-expressions.md",
		questions: [],
	},
	{
		id: "c-cpp-blocks-control-flow",
		partId: "developers",
		path: "/docs/book/developers/c-cpp/blocks-control-flow",
		aliases: [
			"/docs/book/developers/guides/c-cpp/blocks-control-flow",
			"/docs/book/developers/c/blocks-control-flow",
			"/docs/book/developers/cpp/blocks-control-flow",
			"/docs/book/developers/c-plus-plus/blocks-control-flow",
			"/docs/language/developers/c-cpp/blocks-control-flow",
			"/learn/language/developers/c-cpp/blocks-control-flow",
		],
		sourcePath: "docs/what/language/developers/c-cpp/blocks-control-flow.md",
		questions: [],
	},
	{
		id: "c-cpp-variables-mutation",
		partId: "developers",
		path: "/docs/book/developers/c-cpp/variables-mutation",
		aliases: [
			"/docs/book/developers/guides/c-cpp/variables-mutation",
			"/docs/book/developers/c/variables-mutation",
			"/docs/book/developers/cpp/variables-mutation",
			"/docs/book/developers/c-plus-plus/variables-mutation",
			"/docs/language/developers/c-cpp/variables-mutation",
			"/learn/language/developers/c-cpp/variables-mutation",
		],
		sourcePath: "docs/what/language/developers/c-cpp/variables-mutation.md",
		questions: [],
	},
	{
		id: "c-cpp-structs-classes-records",
		partId: "developers",
		path: "/docs/book/developers/c-cpp/structs-classes-records",
		aliases: [
			"/docs/book/developers/guides/c-cpp/structs-classes-records",
			"/docs/book/developers/c/structs-classes-records",
			"/docs/book/developers/cpp/structs-classes-records",
			"/docs/book/developers/c-plus-plus/structs-classes-records",
			"/docs/language/developers/c-cpp/structs-classes-records",
			"/learn/language/developers/c-cpp/structs-classes-records",
		],
		sourcePath:
			"docs/what/language/developers/c-cpp/structs-classes-records.md",
		questions: [],
	},
	{
		id: "c-cpp-arrays-pointers-slices",
		partId: "developers",
		path: "/docs/book/developers/c-cpp/arrays-pointers-slices",
		aliases: [
			"/docs/book/developers/guides/c-cpp/arrays-pointers-slices",
			"/docs/book/developers/c/arrays-pointers-slices",
			"/docs/book/developers/cpp/arrays-pointers-slices",
			"/docs/book/developers/c-plus-plus/arrays-pointers-slices",
			"/docs/language/developers/c-cpp/arrays-pointers-slices",
			"/learn/language/developers/c-cpp/arrays-pointers-slices",
		],
		sourcePath: "docs/what/language/developers/c-cpp/arrays-pointers-slices.md",
		questions: [],
	},
	{
		id: "c-cpp-null-option-result",
		partId: "developers",
		path: "/docs/book/developers/c-cpp/null-option-result",
		aliases: [
			"/docs/book/developers/guides/c-cpp/null-option-result",
			"/docs/book/developers/c/null-option-result",
			"/docs/book/developers/cpp/null-option-result",
			"/docs/book/developers/c-plus-plus/null-option-result",
			"/docs/language/developers/c-cpp/null-option-result",
			"/learn/language/developers/c-cpp/null-option-result",
		],
		sourcePath: "docs/what/language/developers/c-cpp/null-option-result.md",
		questions: [],
	},
	{
		id: "c-cpp-errors-results-effects",
		partId: "developers",
		path: "/docs/book/developers/c-cpp/errors-results-effects",
		aliases: [
			"/docs/book/developers/guides/c-cpp/errors-results-effects",
			"/docs/book/developers/c/errors-results-effects",
			"/docs/book/developers/cpp/errors-results-effects",
			"/docs/book/developers/c-plus-plus/errors-results-effects",
			"/docs/language/developers/c-cpp/errors-results-effects",
			"/learn/language/developers/c-cpp/errors-results-effects",
		],
		sourcePath: "docs/what/language/developers/c-cpp/errors-results-effects.md",
		questions: [],
	},
	{
		id: "c-cpp-enums-variants-patterns",
		partId: "developers",
		path: "/docs/book/developers/c-cpp/enums-variants-patterns",
		aliases: [
			"/docs/book/developers/guides/c-cpp/enums-variants-patterns",
			"/docs/book/developers/c/enums-variants-patterns",
			"/docs/book/developers/cpp/enums-variants-patterns",
			"/docs/book/developers/c-plus-plus/enums-variants-patterns",
			"/docs/language/developers/c-cpp/enums-variants-patterns",
			"/learn/language/developers/c-cpp/enums-variants-patterns",
		],
		sourcePath:
			"docs/what/language/developers/c-cpp/enums-variants-patterns.md",
		questions: [],
	},
	{
		id: "c-cpp-templates-concepts-classes-laws",
		partId: "developers",
		path: "/docs/book/developers/c-cpp/templates-concepts-classes-laws",
		aliases: [
			"/docs/book/developers/guides/c-cpp/templates-concepts-classes-laws",
			"/docs/book/developers/c/templates-concepts-classes-laws",
			"/docs/book/developers/cpp/templates-concepts-classes-laws",
			"/docs/book/developers/c-plus-plus/templates-concepts-classes-laws",
			"/docs/language/developers/c-cpp/templates-concepts-classes-laws",
			"/learn/language/developers/c-cpp/templates-concepts-classes-laws",
		],
		sourcePath:
			"docs/what/language/developers/c-cpp/templates-concepts-classes-laws.md",
		questions: [],
	},
	{
		id: "c-cpp-methods-and-receiver-calls",
		partId: "developers",
		path: "/docs/book/developers/c-cpp/methods-and-receiver-calls",
		aliases: [
			"/docs/book/developers/guides/c-cpp/methods-and-receiver-calls",
			"/docs/book/developers/c/methods-and-receiver-calls",
			"/docs/book/developers/cpp/methods-and-receiver-calls",
			"/docs/book/developers/c-plus-plus/methods-and-receiver-calls",
			"/docs/language/developers/c-cpp/methods-and-receiver-calls",
			"/learn/language/developers/c-cpp/methods-and-receiver-calls",
		],
		sourcePath:
			"docs/what/language/developers/c-cpp/methods-and-receiver-calls.md",
		questions: [],
	},
	{
		id: "c-cpp-headers-modules-packages",
		partId: "developers",
		path: "/docs/book/developers/c-cpp/headers-modules-packages",
		aliases: [
			"/docs/book/developers/guides/c-cpp/headers-modules-packages",
			"/docs/book/developers/c/headers-modules-packages",
			"/docs/book/developers/cpp/headers-modules-packages",
			"/docs/book/developers/c-plus-plus/headers-modules-packages",
			"/docs/language/developers/c-cpp/headers-modules-packages",
			"/learn/language/developers/c-cpp/headers-modules-packages",
		],
		sourcePath:
			"docs/what/language/developers/c-cpp/headers-modules-packages.md",
		questions: [],
	},
	{
		id: "c-cpp-testing-tooling",
		partId: "developers",
		path: "/docs/book/developers/c-cpp/testing-tooling",
		aliases: [
			"/docs/book/developers/guides/c-cpp/testing-tooling",
			"/docs/book/developers/c/testing-tooling",
			"/docs/book/developers/cpp/testing-tooling",
			"/docs/book/developers/c-plus-plus/testing-tooling",
			"/docs/language/developers/c-cpp/testing-tooling",
			"/learn/language/developers/c-cpp/testing-tooling",
		],
		sourcePath: "docs/what/language/developers/c-cpp/testing-tooling.md",
		questions: [],
	},
	{
		id: "c-cpp-unsafe-ffi-native-boundaries",
		partId: "developers",
		path: "/docs/book/developers/c-cpp/unsafe-ffi-native-boundaries",
		aliases: [
			"/docs/book/developers/guides/c-cpp/unsafe-ffi-native-boundaries",
			"/docs/book/developers/c/unsafe-ffi-native-boundaries",
			"/docs/book/developers/cpp/unsafe-ffi-native-boundaries",
			"/docs/book/developers/c-plus-plus/unsafe-ffi-native-boundaries",
			"/docs/language/developers/c-cpp/unsafe-ffi-native-boundaries",
			"/learn/language/developers/c-cpp/unsafe-ffi-native-boundaries",
		],
		sourcePath:
			"docs/what/language/developers/c-cpp/unsafe-ffi-native-boundaries.md",
		questions: [],
	},
] satisfies readonly RawBookPageDefinition[];
