import type { RawBookPageDefinition } from "../../types";

export const c99DeveloperPages = [
	{
		id: "c99-overview",
		partId: "developers",
		path: "/docs/book/developers/c99/overview",
		aliases: [
			"/docs/book/developers/guides/c99/overview",
			"/docs/language/developers/c99/overview",
			"/learn/language/developers/c99/overview",
			"/docs/book/developers/c/overview",
			"/learn/book/developers/c/overview",
			"/docs/language/developers/c/overview",
			"/learn/language/developers/c/overview",
		],
		sourcePath: "docs/what/language/developers/c99/overview.md",
		questions: [],
	},
	{
		id: "c99-values-functions-expressions",
		partId: "developers",
		path: "/docs/book/developers/c99/values-functions-expressions",
		aliases: [
			"/docs/book/developers/guides/c99/values-functions-expressions",
			"/docs/language/developers/c99/values-functions-expressions",
			"/learn/language/developers/c99/values-functions-expressions",
			"/docs/book/developers/c/values-functions-expressions",
			"/learn/book/developers/c/values-functions-expressions",
			"/docs/language/developers/c/values-functions-expressions",
			"/learn/language/developers/c/values-functions-expressions",
		],
		sourcePath:
			"docs/what/language/developers/c99/values-functions-expressions.md",
		questions: [],
	},
	{
		id: "c99-blocks-control-flow",
		partId: "developers",
		path: "/docs/book/developers/c99/blocks-control-flow",
		aliases: [
			"/docs/book/developers/guides/c99/blocks-control-flow",
			"/docs/language/developers/c99/blocks-control-flow",
			"/learn/language/developers/c99/blocks-control-flow",
			"/docs/book/developers/c/blocks-control-flow",
			"/learn/book/developers/c/blocks-control-flow",
			"/docs/language/developers/c/blocks-control-flow",
			"/learn/language/developers/c/blocks-control-flow",
		],
		sourcePath: "docs/what/language/developers/c99/blocks-control-flow.md",
		questions: [],
	},
	{
		id: "c99-variables-mutation",
		partId: "developers",
		path: "/docs/book/developers/c99/variables-mutation",
		aliases: [
			"/docs/book/developers/guides/c99/variables-mutation",
			"/docs/language/developers/c99/variables-mutation",
			"/learn/language/developers/c99/variables-mutation",
			"/docs/book/developers/c/variables-mutation",
			"/learn/book/developers/c/variables-mutation",
			"/docs/language/developers/c/variables-mutation",
			"/learn/language/developers/c/variables-mutation",
		],
		sourcePath: "docs/what/language/developers/c99/variables-mutation.md",
		questions: [],
	},
	{
		id: "c99-structs-classes-records",
		partId: "developers",
		path: "/docs/book/developers/c99/structs-classes-records",
		aliases: [
			"/docs/book/developers/guides/c99/structs-classes-records",
			"/docs/language/developers/c99/structs-classes-records",
			"/learn/language/developers/c99/structs-classes-records",
			"/docs/book/developers/c/structs-classes-records",
			"/learn/book/developers/c/structs-classes-records",
			"/docs/language/developers/c/structs-classes-records",
			"/learn/language/developers/c/structs-classes-records",
		],
		sourcePath: "docs/what/language/developers/c99/structs-classes-records.md",
		questions: [],
	},
	{
		id: "c99-arrays-pointers-slices",
		partId: "developers",
		path: "/docs/book/developers/c99/arrays-pointers-slices",
		aliases: [
			"/docs/book/developers/guides/c99/arrays-pointers-slices",
			"/docs/language/developers/c99/arrays-pointers-slices",
			"/learn/language/developers/c99/arrays-pointers-slices",
			"/docs/book/developers/c/arrays-pointers-slices",
			"/learn/book/developers/c/arrays-pointers-slices",
			"/docs/language/developers/c/arrays-pointers-slices",
			"/learn/language/developers/c/arrays-pointers-slices",
		],
		sourcePath: "docs/what/language/developers/c99/arrays-pointers-slices.md",
		questions: [],
	},
	{
		id: "c99-null-option-result",
		partId: "developers",
		path: "/docs/book/developers/c99/null-option-result",
		aliases: [
			"/docs/book/developers/guides/c99/null-option-result",
			"/docs/language/developers/c99/null-option-result",
			"/learn/language/developers/c99/null-option-result",
			"/docs/book/developers/c/null-option-result",
			"/learn/book/developers/c/null-option-result",
			"/docs/language/developers/c/null-option-result",
			"/learn/language/developers/c/null-option-result",
		],
		sourcePath: "docs/what/language/developers/c99/null-option-result.md",
		questions: [],
	},
	{
		id: "c99-errors-results-effects",
		partId: "developers",
		path: "/docs/book/developers/c99/errors-results-effects",
		aliases: [
			"/docs/book/developers/guides/c99/errors-results-effects",
			"/docs/language/developers/c99/errors-results-effects",
			"/learn/language/developers/c99/errors-results-effects",
			"/docs/book/developers/c/errors-results-effects",
			"/learn/book/developers/c/errors-results-effects",
			"/docs/language/developers/c/errors-results-effects",
			"/learn/language/developers/c/errors-results-effects",
		],
		sourcePath: "docs/what/language/developers/c99/errors-results-effects.md",
		questions: [],
	},
	{
		id: "c99-enums-variants-patterns",
		partId: "developers",
		path: "/docs/book/developers/c99/enums-variants-patterns",
		aliases: [
			"/docs/book/developers/guides/c99/enums-variants-patterns",
			"/docs/language/developers/c99/enums-variants-patterns",
			"/learn/language/developers/c99/enums-variants-patterns",
			"/docs/book/developers/c/enums-variants-patterns",
			"/learn/book/developers/c/enums-variants-patterns",
			"/docs/language/developers/c/enums-variants-patterns",
			"/learn/language/developers/c/enums-variants-patterns",
		],
		sourcePath: "docs/what/language/developers/c99/enums-variants-patterns.md",
		questions: [],
	},
	{
		id: "c99-templates-concepts-classes-laws",
		partId: "developers",
		path: "/docs/book/developers/c99/templates-concepts-classes-laws",
		aliases: [
			"/docs/book/developers/guides/c99/templates-concepts-classes-laws",
			"/docs/language/developers/c99/templates-concepts-classes-laws",
			"/learn/language/developers/c99/templates-concepts-classes-laws",
			"/docs/book/developers/c/templates-concepts-classes-laws",
			"/learn/book/developers/c/templates-concepts-classes-laws",
			"/docs/language/developers/c/templates-concepts-classes-laws",
			"/learn/language/developers/c/templates-concepts-classes-laws",
		],
		sourcePath:
			"docs/what/language/developers/c99/templates-concepts-classes-laws.md",
		questions: [],
	},
	{
		id: "c99-methods-and-receiver-calls",
		partId: "developers",
		path: "/docs/book/developers/c99/methods-and-receiver-calls",
		aliases: [
			"/docs/book/developers/guides/c99/methods-and-receiver-calls",
			"/docs/language/developers/c99/methods-and-receiver-calls",
			"/learn/language/developers/c99/methods-and-receiver-calls",
			"/docs/book/developers/c/methods-and-receiver-calls",
			"/learn/book/developers/c/methods-and-receiver-calls",
			"/docs/language/developers/c/methods-and-receiver-calls",
			"/learn/language/developers/c/methods-and-receiver-calls",
		],
		sourcePath:
			"docs/what/language/developers/c99/methods-and-receiver-calls.md",
		questions: [],
	},
	{
		id: "c99-headers-modules-packages",
		partId: "developers",
		path: "/docs/book/developers/c99/headers-modules-packages",
		aliases: [
			"/docs/book/developers/guides/c99/headers-modules-packages",
			"/docs/language/developers/c99/headers-modules-packages",
			"/learn/language/developers/c99/headers-modules-packages",
			"/docs/book/developers/c/headers-modules-packages",
			"/learn/book/developers/c/headers-modules-packages",
			"/docs/language/developers/c/headers-modules-packages",
			"/learn/language/developers/c/headers-modules-packages",
		],
		sourcePath: "docs/what/language/developers/c99/headers-modules-packages.md",
		questions: [],
	},
	{
		id: "c99-testing-tooling",
		partId: "developers",
		path: "/docs/book/developers/c99/testing-tooling",
		aliases: [
			"/docs/book/developers/guides/c99/testing-tooling",
			"/docs/language/developers/c99/testing-tooling",
			"/learn/language/developers/c99/testing-tooling",
			"/docs/book/developers/c/testing-tooling",
			"/learn/book/developers/c/testing-tooling",
			"/docs/language/developers/c/testing-tooling",
			"/learn/language/developers/c/testing-tooling",
		],
		sourcePath: "docs/what/language/developers/c99/testing-tooling.md",
		questions: [],
	},
	{
		id: "c99-unsafe-ffi-native-boundaries",
		partId: "developers",
		path: "/docs/book/developers/c99/unsafe-ffi-native-boundaries",
		aliases: [
			"/docs/book/developers/guides/c99/unsafe-ffi-native-boundaries",
			"/docs/language/developers/c99/unsafe-ffi-native-boundaries",
			"/learn/language/developers/c99/unsafe-ffi-native-boundaries",
			"/docs/book/developers/c/unsafe-ffi-native-boundaries",
			"/learn/book/developers/c/unsafe-ffi-native-boundaries",
			"/docs/language/developers/c/unsafe-ffi-native-boundaries",
			"/learn/language/developers/c/unsafe-ffi-native-boundaries",
		],
		sourcePath:
			"docs/what/language/developers/c99/unsafe-ffi-native-boundaries.md",
		questions: [],
	},
] satisfies readonly RawBookPageDefinition[];
