import type { RawBookPageDefinition } from "../../types";

export const cpp17DeveloperPages = [
	{
		id: "cpp17-overview",
		partId: "developers",
		path: "/docs/book/developers/cpp17/overview",
		aliases: [
			"/docs/book/developers/guides/cpp17/overview",
			"/docs/language/developers/cpp17/overview",
			"/learn/language/developers/cpp17/overview",
			"/docs/book/developers/cpp/overview",
			"/learn/book/developers/cpp/overview",
			"/docs/book/developers/c-plus-plus/overview",
			"/learn/book/developers/c-plus-plus/overview",
			"/docs/book/developers/c-cpp/overview",
			"/learn/book/developers/c-cpp/overview",
			"/docs/book/developers/c-and-cpp/overview",
			"/learn/book/developers/c-and-cpp/overview",
			"/docs/book/developers/guides/c-cpp/overview",
			"/learn/book/developers/guides/c-cpp/overview",
			"/docs/book/developers/guides/c-and-cpp/overview",
			"/learn/book/developers/guides/c-and-cpp/overview",
			"/docs/language/developers/cpp/overview",
			"/learn/language/developers/cpp/overview",
			"/docs/language/developers/c-plus-plus/overview",
			"/learn/language/developers/c-plus-plus/overview",
			"/docs/language/developers/c-cpp/overview",
			"/learn/language/developers/c-cpp/overview",
		],
		sourcePath: "docs/what/language/developers/cpp17/overview.md",
		questions: [],
	},
	{
		id: "cpp17-values-functions-expressions",
		partId: "developers",
		path: "/docs/book/developers/cpp17/values-functions-expressions",
		aliases: [
			"/docs/book/developers/guides/cpp17/values-functions-expressions",
			"/docs/language/developers/cpp17/values-functions-expressions",
			"/learn/language/developers/cpp17/values-functions-expressions",
			"/docs/book/developers/cpp/values-functions-expressions",
			"/learn/book/developers/cpp/values-functions-expressions",
			"/docs/book/developers/c-plus-plus/values-functions-expressions",
			"/learn/book/developers/c-plus-plus/values-functions-expressions",
			"/docs/book/developers/c-cpp/values-functions-expressions",
			"/learn/book/developers/c-cpp/values-functions-expressions",
			"/docs/book/developers/c-and-cpp/values-functions-expressions",
			"/learn/book/developers/c-and-cpp/values-functions-expressions",
			"/docs/book/developers/guides/c-cpp/values-functions-expressions",
			"/learn/book/developers/guides/c-cpp/values-functions-expressions",
			"/docs/book/developers/guides/c-and-cpp/values-functions-expressions",
			"/learn/book/developers/guides/c-and-cpp/values-functions-expressions",
			"/docs/language/developers/cpp/values-functions-expressions",
			"/learn/language/developers/cpp/values-functions-expressions",
			"/docs/language/developers/c-plus-plus/values-functions-expressions",
			"/learn/language/developers/c-plus-plus/values-functions-expressions",
			"/docs/language/developers/c-cpp/values-functions-expressions",
			"/learn/language/developers/c-cpp/values-functions-expressions",
		],
		sourcePath:
			"docs/what/language/developers/cpp17/values-functions-expressions.md",
		questions: [],
	},
	{
		id: "cpp17-blocks-control-flow",
		partId: "developers",
		path: "/docs/book/developers/cpp17/blocks-control-flow",
		aliases: [
			"/docs/book/developers/guides/cpp17/blocks-control-flow",
			"/docs/language/developers/cpp17/blocks-control-flow",
			"/learn/language/developers/cpp17/blocks-control-flow",
			"/docs/book/developers/cpp/blocks-control-flow",
			"/learn/book/developers/cpp/blocks-control-flow",
			"/docs/book/developers/c-plus-plus/blocks-control-flow",
			"/learn/book/developers/c-plus-plus/blocks-control-flow",
			"/docs/book/developers/c-cpp/blocks-control-flow",
			"/learn/book/developers/c-cpp/blocks-control-flow",
			"/docs/book/developers/c-and-cpp/blocks-control-flow",
			"/learn/book/developers/c-and-cpp/blocks-control-flow",
			"/docs/book/developers/guides/c-cpp/blocks-control-flow",
			"/learn/book/developers/guides/c-cpp/blocks-control-flow",
			"/docs/book/developers/guides/c-and-cpp/blocks-control-flow",
			"/learn/book/developers/guides/c-and-cpp/blocks-control-flow",
			"/docs/language/developers/cpp/blocks-control-flow",
			"/learn/language/developers/cpp/blocks-control-flow",
			"/docs/language/developers/c-plus-plus/blocks-control-flow",
			"/learn/language/developers/c-plus-plus/blocks-control-flow",
			"/docs/language/developers/c-cpp/blocks-control-flow",
			"/learn/language/developers/c-cpp/blocks-control-flow",
		],
		sourcePath: "docs/what/language/developers/cpp17/blocks-control-flow.md",
		questions: [],
	},
	{
		id: "cpp17-variables-mutation",
		partId: "developers",
		path: "/docs/book/developers/cpp17/variables-mutation",
		aliases: [
			"/docs/book/developers/guides/cpp17/variables-mutation",
			"/docs/language/developers/cpp17/variables-mutation",
			"/learn/language/developers/cpp17/variables-mutation",
			"/docs/book/developers/cpp/variables-mutation",
			"/learn/book/developers/cpp/variables-mutation",
			"/docs/book/developers/c-plus-plus/variables-mutation",
			"/learn/book/developers/c-plus-plus/variables-mutation",
			"/docs/book/developers/c-cpp/variables-mutation",
			"/learn/book/developers/c-cpp/variables-mutation",
			"/docs/book/developers/c-and-cpp/variables-mutation",
			"/learn/book/developers/c-and-cpp/variables-mutation",
			"/docs/book/developers/guides/c-cpp/variables-mutation",
			"/learn/book/developers/guides/c-cpp/variables-mutation",
			"/docs/book/developers/guides/c-and-cpp/variables-mutation",
			"/learn/book/developers/guides/c-and-cpp/variables-mutation",
			"/docs/language/developers/cpp/variables-mutation",
			"/learn/language/developers/cpp/variables-mutation",
			"/docs/language/developers/c-plus-plus/variables-mutation",
			"/learn/language/developers/c-plus-plus/variables-mutation",
			"/docs/language/developers/c-cpp/variables-mutation",
			"/learn/language/developers/c-cpp/variables-mutation",
		],
		sourcePath: "docs/what/language/developers/cpp17/variables-mutation.md",
		questions: [],
	},
	{
		id: "cpp17-structs-classes-records",
		partId: "developers",
		path: "/docs/book/developers/cpp17/structs-classes-records",
		aliases: [
			"/docs/book/developers/guides/cpp17/structs-classes-records",
			"/docs/language/developers/cpp17/structs-classes-records",
			"/learn/language/developers/cpp17/structs-classes-records",
			"/docs/book/developers/cpp/structs-classes-records",
			"/learn/book/developers/cpp/structs-classes-records",
			"/docs/book/developers/c-plus-plus/structs-classes-records",
			"/learn/book/developers/c-plus-plus/structs-classes-records",
			"/docs/book/developers/c-cpp/structs-classes-records",
			"/learn/book/developers/c-cpp/structs-classes-records",
			"/docs/book/developers/c-and-cpp/structs-classes-records",
			"/learn/book/developers/c-and-cpp/structs-classes-records",
			"/docs/book/developers/guides/c-cpp/structs-classes-records",
			"/learn/book/developers/guides/c-cpp/structs-classes-records",
			"/docs/book/developers/guides/c-and-cpp/structs-classes-records",
			"/learn/book/developers/guides/c-and-cpp/structs-classes-records",
			"/docs/language/developers/cpp/structs-classes-records",
			"/learn/language/developers/cpp/structs-classes-records",
			"/docs/language/developers/c-plus-plus/structs-classes-records",
			"/learn/language/developers/c-plus-plus/structs-classes-records",
			"/docs/language/developers/c-cpp/structs-classes-records",
			"/learn/language/developers/c-cpp/structs-classes-records",
		],
		sourcePath:
			"docs/what/language/developers/cpp17/structs-classes-records.md",
		questions: [],
	},
	{
		id: "cpp17-arrays-pointers-slices",
		partId: "developers",
		path: "/docs/book/developers/cpp17/arrays-pointers-slices",
		aliases: [
			"/docs/book/developers/guides/cpp17/arrays-pointers-slices",
			"/docs/language/developers/cpp17/arrays-pointers-slices",
			"/learn/language/developers/cpp17/arrays-pointers-slices",
			"/docs/book/developers/cpp/arrays-pointers-slices",
			"/learn/book/developers/cpp/arrays-pointers-slices",
			"/docs/book/developers/c-plus-plus/arrays-pointers-slices",
			"/learn/book/developers/c-plus-plus/arrays-pointers-slices",
			"/docs/book/developers/c-cpp/arrays-pointers-slices",
			"/learn/book/developers/c-cpp/arrays-pointers-slices",
			"/docs/book/developers/c-and-cpp/arrays-pointers-slices",
			"/learn/book/developers/c-and-cpp/arrays-pointers-slices",
			"/docs/book/developers/guides/c-cpp/arrays-pointers-slices",
			"/learn/book/developers/guides/c-cpp/arrays-pointers-slices",
			"/docs/book/developers/guides/c-and-cpp/arrays-pointers-slices",
			"/learn/book/developers/guides/c-and-cpp/arrays-pointers-slices",
			"/docs/language/developers/cpp/arrays-pointers-slices",
			"/learn/language/developers/cpp/arrays-pointers-slices",
			"/docs/language/developers/c-plus-plus/arrays-pointers-slices",
			"/learn/language/developers/c-plus-plus/arrays-pointers-slices",
			"/docs/language/developers/c-cpp/arrays-pointers-slices",
			"/learn/language/developers/c-cpp/arrays-pointers-slices",
		],
		sourcePath: "docs/what/language/developers/cpp17/arrays-pointers-slices.md",
		questions: [],
	},
	{
		id: "cpp17-null-option-result",
		partId: "developers",
		path: "/docs/book/developers/cpp17/null-option-result",
		aliases: [
			"/docs/book/developers/guides/cpp17/null-option-result",
			"/docs/language/developers/cpp17/null-option-result",
			"/learn/language/developers/cpp17/null-option-result",
			"/docs/book/developers/cpp/null-option-result",
			"/learn/book/developers/cpp/null-option-result",
			"/docs/book/developers/c-plus-plus/null-option-result",
			"/learn/book/developers/c-plus-plus/null-option-result",
			"/docs/book/developers/c-cpp/null-option-result",
			"/learn/book/developers/c-cpp/null-option-result",
			"/docs/book/developers/c-and-cpp/null-option-result",
			"/learn/book/developers/c-and-cpp/null-option-result",
			"/docs/book/developers/guides/c-cpp/null-option-result",
			"/learn/book/developers/guides/c-cpp/null-option-result",
			"/docs/book/developers/guides/c-and-cpp/null-option-result",
			"/learn/book/developers/guides/c-and-cpp/null-option-result",
			"/docs/language/developers/cpp/null-option-result",
			"/learn/language/developers/cpp/null-option-result",
			"/docs/language/developers/c-plus-plus/null-option-result",
			"/learn/language/developers/c-plus-plus/null-option-result",
			"/docs/language/developers/c-cpp/null-option-result",
			"/learn/language/developers/c-cpp/null-option-result",
		],
		sourcePath: "docs/what/language/developers/cpp17/null-option-result.md",
		questions: [],
	},
	{
		id: "cpp17-errors-results-effects",
		partId: "developers",
		path: "/docs/book/developers/cpp17/errors-results-effects",
		aliases: [
			"/docs/book/developers/guides/cpp17/errors-results-effects",
			"/docs/language/developers/cpp17/errors-results-effects",
			"/learn/language/developers/cpp17/errors-results-effects",
			"/docs/book/developers/cpp/errors-results-effects",
			"/learn/book/developers/cpp/errors-results-effects",
			"/docs/book/developers/c-plus-plus/errors-results-effects",
			"/learn/book/developers/c-plus-plus/errors-results-effects",
			"/docs/book/developers/c-cpp/errors-results-effects",
			"/learn/book/developers/c-cpp/errors-results-effects",
			"/docs/book/developers/c-and-cpp/errors-results-effects",
			"/learn/book/developers/c-and-cpp/errors-results-effects",
			"/docs/book/developers/guides/c-cpp/errors-results-effects",
			"/learn/book/developers/guides/c-cpp/errors-results-effects",
			"/docs/book/developers/guides/c-and-cpp/errors-results-effects",
			"/learn/book/developers/guides/c-and-cpp/errors-results-effects",
			"/docs/language/developers/cpp/errors-results-effects",
			"/learn/language/developers/cpp/errors-results-effects",
			"/docs/language/developers/c-plus-plus/errors-results-effects",
			"/learn/language/developers/c-plus-plus/errors-results-effects",
			"/docs/language/developers/c-cpp/errors-results-effects",
			"/learn/language/developers/c-cpp/errors-results-effects",
		],
		sourcePath: "docs/what/language/developers/cpp17/errors-results-effects.md",
		questions: [],
	},
	{
		id: "cpp17-enums-variants-patterns",
		partId: "developers",
		path: "/docs/book/developers/cpp17/enums-variants-patterns",
		aliases: [
			"/docs/book/developers/guides/cpp17/enums-variants-patterns",
			"/docs/language/developers/cpp17/enums-variants-patterns",
			"/learn/language/developers/cpp17/enums-variants-patterns",
			"/docs/book/developers/cpp/enums-variants-patterns",
			"/learn/book/developers/cpp/enums-variants-patterns",
			"/docs/book/developers/c-plus-plus/enums-variants-patterns",
			"/learn/book/developers/c-plus-plus/enums-variants-patterns",
			"/docs/book/developers/c-cpp/enums-variants-patterns",
			"/learn/book/developers/c-cpp/enums-variants-patterns",
			"/docs/book/developers/c-and-cpp/enums-variants-patterns",
			"/learn/book/developers/c-and-cpp/enums-variants-patterns",
			"/docs/book/developers/guides/c-cpp/enums-variants-patterns",
			"/learn/book/developers/guides/c-cpp/enums-variants-patterns",
			"/docs/book/developers/guides/c-and-cpp/enums-variants-patterns",
			"/learn/book/developers/guides/c-and-cpp/enums-variants-patterns",
			"/docs/language/developers/cpp/enums-variants-patterns",
			"/learn/language/developers/cpp/enums-variants-patterns",
			"/docs/language/developers/c-plus-plus/enums-variants-patterns",
			"/learn/language/developers/c-plus-plus/enums-variants-patterns",
			"/docs/language/developers/c-cpp/enums-variants-patterns",
			"/learn/language/developers/c-cpp/enums-variants-patterns",
		],
		sourcePath:
			"docs/what/language/developers/cpp17/enums-variants-patterns.md",
		questions: [],
	},
	{
		id: "cpp17-templates-concepts-classes-laws",
		partId: "developers",
		path: "/docs/book/developers/cpp17/templates-concepts-classes-laws",
		aliases: [
			"/docs/book/developers/guides/cpp17/templates-concepts-classes-laws",
			"/docs/language/developers/cpp17/templates-concepts-classes-laws",
			"/learn/language/developers/cpp17/templates-concepts-classes-laws",
			"/docs/book/developers/cpp/templates-concepts-classes-laws",
			"/learn/book/developers/cpp/templates-concepts-classes-laws",
			"/docs/book/developers/c-plus-plus/templates-concepts-classes-laws",
			"/learn/book/developers/c-plus-plus/templates-concepts-classes-laws",
			"/docs/book/developers/c-cpp/templates-concepts-classes-laws",
			"/learn/book/developers/c-cpp/templates-concepts-classes-laws",
			"/docs/book/developers/c-and-cpp/templates-concepts-classes-laws",
			"/learn/book/developers/c-and-cpp/templates-concepts-classes-laws",
			"/docs/book/developers/guides/c-cpp/templates-concepts-classes-laws",
			"/learn/book/developers/guides/c-cpp/templates-concepts-classes-laws",
			"/docs/book/developers/guides/c-and-cpp/templates-concepts-classes-laws",
			"/learn/book/developers/guides/c-and-cpp/templates-concepts-classes-laws",
			"/docs/language/developers/cpp/templates-concepts-classes-laws",
			"/learn/language/developers/cpp/templates-concepts-classes-laws",
			"/docs/language/developers/c-plus-plus/templates-concepts-classes-laws",
			"/learn/language/developers/c-plus-plus/templates-concepts-classes-laws",
			"/docs/language/developers/c-cpp/templates-concepts-classes-laws",
			"/learn/language/developers/c-cpp/templates-concepts-classes-laws",
		],
		sourcePath:
			"docs/what/language/developers/cpp17/templates-concepts-classes-laws.md",
		questions: [],
	},
	{
		id: "cpp17-methods-and-receiver-calls",
		partId: "developers",
		path: "/docs/book/developers/cpp17/methods-and-receiver-calls",
		aliases: [
			"/docs/book/developers/guides/cpp17/methods-and-receiver-calls",
			"/docs/language/developers/cpp17/methods-and-receiver-calls",
			"/learn/language/developers/cpp17/methods-and-receiver-calls",
			"/docs/book/developers/cpp/methods-and-receiver-calls",
			"/learn/book/developers/cpp/methods-and-receiver-calls",
			"/docs/book/developers/c-plus-plus/methods-and-receiver-calls",
			"/learn/book/developers/c-plus-plus/methods-and-receiver-calls",
			"/docs/book/developers/c-cpp/methods-and-receiver-calls",
			"/learn/book/developers/c-cpp/methods-and-receiver-calls",
			"/docs/book/developers/c-and-cpp/methods-and-receiver-calls",
			"/learn/book/developers/c-and-cpp/methods-and-receiver-calls",
			"/docs/book/developers/guides/c-cpp/methods-and-receiver-calls",
			"/learn/book/developers/guides/c-cpp/methods-and-receiver-calls",
			"/docs/book/developers/guides/c-and-cpp/methods-and-receiver-calls",
			"/learn/book/developers/guides/c-and-cpp/methods-and-receiver-calls",
			"/docs/language/developers/cpp/methods-and-receiver-calls",
			"/learn/language/developers/cpp/methods-and-receiver-calls",
			"/docs/language/developers/c-plus-plus/methods-and-receiver-calls",
			"/learn/language/developers/c-plus-plus/methods-and-receiver-calls",
			"/docs/language/developers/c-cpp/methods-and-receiver-calls",
			"/learn/language/developers/c-cpp/methods-and-receiver-calls",
		],
		sourcePath:
			"docs/what/language/developers/cpp17/methods-and-receiver-calls.md",
		questions: [],
	},
	{
		id: "cpp17-headers-modules-packages",
		partId: "developers",
		path: "/docs/book/developers/cpp17/headers-modules-packages",
		aliases: [
			"/docs/book/developers/guides/cpp17/headers-modules-packages",
			"/docs/language/developers/cpp17/headers-modules-packages",
			"/learn/language/developers/cpp17/headers-modules-packages",
			"/docs/book/developers/cpp/headers-modules-packages",
			"/learn/book/developers/cpp/headers-modules-packages",
			"/docs/book/developers/c-plus-plus/headers-modules-packages",
			"/learn/book/developers/c-plus-plus/headers-modules-packages",
			"/docs/book/developers/c-cpp/headers-modules-packages",
			"/learn/book/developers/c-cpp/headers-modules-packages",
			"/docs/book/developers/c-and-cpp/headers-modules-packages",
			"/learn/book/developers/c-and-cpp/headers-modules-packages",
			"/docs/book/developers/guides/c-cpp/headers-modules-packages",
			"/learn/book/developers/guides/c-cpp/headers-modules-packages",
			"/docs/book/developers/guides/c-and-cpp/headers-modules-packages",
			"/learn/book/developers/guides/c-and-cpp/headers-modules-packages",
			"/docs/language/developers/cpp/headers-modules-packages",
			"/learn/language/developers/cpp/headers-modules-packages",
			"/docs/language/developers/c-plus-plus/headers-modules-packages",
			"/learn/language/developers/c-plus-plus/headers-modules-packages",
			"/docs/language/developers/c-cpp/headers-modules-packages",
			"/learn/language/developers/c-cpp/headers-modules-packages",
		],
		sourcePath:
			"docs/what/language/developers/cpp17/headers-modules-packages.md",
		questions: [],
	},
	{
		id: "cpp17-testing-tooling",
		partId: "developers",
		path: "/docs/book/developers/cpp17/testing-tooling",
		aliases: [
			"/docs/book/developers/guides/cpp17/testing-tooling",
			"/docs/language/developers/cpp17/testing-tooling",
			"/learn/language/developers/cpp17/testing-tooling",
			"/docs/book/developers/cpp/testing-tooling",
			"/learn/book/developers/cpp/testing-tooling",
			"/docs/book/developers/c-plus-plus/testing-tooling",
			"/learn/book/developers/c-plus-plus/testing-tooling",
			"/docs/book/developers/c-cpp/testing-tooling",
			"/learn/book/developers/c-cpp/testing-tooling",
			"/docs/book/developers/c-and-cpp/testing-tooling",
			"/learn/book/developers/c-and-cpp/testing-tooling",
			"/docs/book/developers/guides/c-cpp/testing-tooling",
			"/learn/book/developers/guides/c-cpp/testing-tooling",
			"/docs/book/developers/guides/c-and-cpp/testing-tooling",
			"/learn/book/developers/guides/c-and-cpp/testing-tooling",
			"/docs/language/developers/cpp/testing-tooling",
			"/learn/language/developers/cpp/testing-tooling",
			"/docs/language/developers/c-plus-plus/testing-tooling",
			"/learn/language/developers/c-plus-plus/testing-tooling",
			"/docs/language/developers/c-cpp/testing-tooling",
			"/learn/language/developers/c-cpp/testing-tooling",
		],
		sourcePath: "docs/what/language/developers/cpp17/testing-tooling.md",
		questions: [],
	},
	{
		id: "cpp17-unsafe-ffi-native-boundaries",
		partId: "developers",
		path: "/docs/book/developers/cpp17/unsafe-ffi-native-boundaries",
		aliases: [
			"/docs/book/developers/guides/cpp17/unsafe-ffi-native-boundaries",
			"/docs/language/developers/cpp17/unsafe-ffi-native-boundaries",
			"/learn/language/developers/cpp17/unsafe-ffi-native-boundaries",
			"/docs/book/developers/cpp/unsafe-ffi-native-boundaries",
			"/learn/book/developers/cpp/unsafe-ffi-native-boundaries",
			"/docs/book/developers/c-plus-plus/unsafe-ffi-native-boundaries",
			"/learn/book/developers/c-plus-plus/unsafe-ffi-native-boundaries",
			"/docs/book/developers/c-cpp/unsafe-ffi-native-boundaries",
			"/learn/book/developers/c-cpp/unsafe-ffi-native-boundaries",
			"/docs/book/developers/c-and-cpp/unsafe-ffi-native-boundaries",
			"/learn/book/developers/c-and-cpp/unsafe-ffi-native-boundaries",
			"/docs/book/developers/guides/c-cpp/unsafe-ffi-native-boundaries",
			"/learn/book/developers/guides/c-cpp/unsafe-ffi-native-boundaries",
			"/docs/book/developers/guides/c-and-cpp/unsafe-ffi-native-boundaries",
			"/learn/book/developers/guides/c-and-cpp/unsafe-ffi-native-boundaries",
			"/docs/language/developers/cpp/unsafe-ffi-native-boundaries",
			"/learn/language/developers/cpp/unsafe-ffi-native-boundaries",
			"/docs/language/developers/c-plus-plus/unsafe-ffi-native-boundaries",
			"/learn/language/developers/c-plus-plus/unsafe-ffi-native-boundaries",
			"/docs/language/developers/c-cpp/unsafe-ffi-native-boundaries",
			"/learn/language/developers/c-cpp/unsafe-ffi-native-boundaries",
		],
		sourcePath:
			"docs/what/language/developers/cpp17/unsafe-ffi-native-boundaries.md",
		questions: [],
	},
] satisfies readonly RawBookPageDefinition[];
