import type { RawBookPageDefinition } from "../../types";

export const rustDeveloperPages = [
	{
		id: "musi-for-rust-developers",
		partId: "developers",
		path: "/docs/book/developers/overview",
		aliases: [
			"/docs/book/developers/rust/overview",
			"/docs/language/developers/rust",
			"/learn/language/developers/rust",
		],
		sourcePath: "docs/what/language/developers/rust.md",
		questions: [],
	},
	{
		id: "rust-values-functions",
		partId: "developers",
		path: "/docs/book/developers/values-functions",
		aliases: [
			"/docs/book/developers/rust/values-functions",
			"/docs/language/developers/rust/values-functions",
			"/learn/language/developers/rust/values-functions",
		],
		sourcePath: "docs/what/language/developers/rust/values-functions.md",
		questions: [],
	},
	{
		id: "rust-mutation",
		partId: "developers",
		path: "/docs/book/developers/mutation",
		aliases: [
			"/docs/book/developers/rust/mutation",
			"/docs/language/developers/rust/mutation",
			"/learn/language/developers/rust/mutation",
		],
		sourcePath: "docs/what/language/developers/rust/mutation.md",
		questions: [],
	},
	{
		id: "rust-records-structs",
		partId: "developers",
		path: "/docs/book/developers/records-structs",
		aliases: [
			"/docs/book/developers/rust/records-structs",
			"/docs/language/developers/rust/records-structs",
			"/learn/language/developers/rust/records-structs",
		],
		sourcePath: "docs/what/language/developers/rust/records-structs.md",
		questions: [],
	},
	{
		id: "rust-enums-data",
		partId: "developers",
		path: "/docs/book/developers/enums-data",
		aliases: [
			"/docs/book/developers/rust/enums-data",
			"/docs/language/developers/rust/enums-data",
			"/learn/language/developers/rust/enums-data",
		],
		sourcePath: "docs/what/language/developers/rust/enums-data.md",
		questions: [],
	},
	{
		id: "rust-traits-classes-laws",
		partId: "developers",
		path: "/docs/book/developers/traits-classes-laws",
		aliases: [
			"/docs/book/developers/rust/traits-classes-laws",
			"/docs/language/developers/rust/traits-classes-laws",
			"/learn/language/developers/rust/traits-classes-laws",
		],
		sourcePath: "docs/what/language/developers/rust/traits-classes-laws.md",
		questions: [],
	},
	{
		id: "rust-generics",
		partId: "developers",
		path: "/docs/book/developers/generics",
		aliases: [
			"/docs/book/developers/rust/generics",
			"/docs/language/developers/rust/generics",
			"/learn/language/developers/rust/generics",
		],
		sourcePath: "docs/what/language/developers/rust/generics.md",
		questions: [],
	},
	{
		id: "rust-results-effects",
		partId: "developers",
		path: "/docs/book/developers/results-effects",
		aliases: [
			"/docs/book/developers/rust/results-effects",
			"/docs/language/developers/rust/results-effects",
			"/learn/language/developers/rust/results-effects",
		],
		sourcePath: "docs/what/language/developers/rust/results-effects.md",
		questions: [],
	},
	{
		id: "rust-modules-packages",
		partId: "developers",
		path: "/docs/book/developers/modules-packages",
		aliases: [
			"/docs/book/developers/rust/modules-packages",
			"/docs/language/developers/rust/modules-packages",
			"/learn/language/developers/rust/modules-packages",
		],
		sourcePath: "docs/what/language/developers/rust/modules-packages.md",
		questions: [],
	},
	{
		id: "rust-unsafe-ffi",
		partId: "developers",
		path: "/docs/book/developers/unsafe-ffi",
		aliases: [
			"/docs/book/developers/rust/unsafe-ffi",
			"/docs/language/developers/rust/unsafe-ffi",
			"/learn/language/developers/rust/unsafe-ffi",
		],
		sourcePath: "docs/what/language/developers/rust/unsafe-ffi.md",
		questions: [],
	},
	{
		id: "rust-testing-tooling",
		partId: "developers",
		path: "/docs/book/developers/testing-tooling",
		aliases: [
			"/docs/book/developers/rust/testing-tooling",
			"/docs/language/developers/rust/testing-tooling",
			"/learn/language/developers/rust/testing-tooling",
		],
		sourcePath: "docs/what/language/developers/rust/testing-tooling.md",
		questions: [],
	},
] satisfies readonly RawBookPageDefinition[];
