// @generated by musi_diaggen. Do not edit by hand.
#![allow(dead_code)]

use super::SeamDiagKind;
use music_base::diag::DiagContext;

struct CatalogEntry {
    kind: SeamDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    secondary: Option<&'static str>,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: SeamDiagKind::ArtifactValidationFailed,
        code: 5400,
        message: "artifact validation failed (`{source}`)",
        primary: "artifact validation failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::InvalidBinaryHeader,
        code: 5401,
        message: "invalid `SEAM` binary header",
        primary: "invalid `SEAM` binary header",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::UnsupportedBinaryVersion,
        code: 5402,
        message: "unsupported binary version `{version}`",
        primary: "unsupported binary version `{version}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::UnknownSectionTag,
        code: 5403,
        message: "unknown section tag `{tag}`",
        primary: "unknown section tag `{tag}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::BinaryPayloadTruncated,
        code: 5404,
        message: "binary payload truncated",
        primary: "binary payload truncated",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::UnknownOpcode,
        code: 5405,
        message: "unknown opcode `{opcode}`",
        primary: "unknown opcode `{opcode}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextParseFailed,
        code: 5406,
        message: "text parse failed (`{source}`)",
        primary: "text parse failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::InvalidReference,
        code: 5407,
        message: "invalid table reference `{table}`",
        primary: "invalid table reference `{table}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::DuplicateLabel,
        code: 5408,
        message: "duplicate label in procedure `{procedure}`",
        primary: "duplicate label in procedure `{procedure}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::MissingLabel,
        code: 5409,
        message: "missing label reference in procedure `{procedure}`",
        primary: "missing label reference in procedure `{procedure}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::InvalidEffectOp,
        code: 5410,
        message: "invalid effect operation reference `effect.op`",
        primary: "invalid effect operation reference `effect.op`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::OperandShapeMismatch,
        code: 5411,
        message: "opcode `{opcode}` operand shape mismatch",
        primary: "opcode `{opcode}` operand shape mismatch",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilMissingEntryBlock,
        code: 5412,
        message: "missing entry block in HIL function `{function}`",
        primary: "missing entry block in HIL function `{function}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilDuplicateBlock,
        code: 5413,
        message: "duplicate block `{block}` in HIL function `{function}`",
        primary: "duplicate HIL block `{block}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilDuplicateValue,
        code: 5414,
        message: "HIL value `{value}` defined more than once",
        primary: "duplicate HIL value `{value}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilUndefinedValue,
        code: 5415,
        message: "HIL value `{value}` used before definition",
        primary: "HIL value `{value}` undefined",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilTypeMismatch,
        code: 5416,
        message: "expected HIL value `{expected}`, found `{found}` for `{value}`",
        primary: "HIL value `{value}` type mismatch",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilMissingBlockTarget,
        code: 5417,
        message: "missing HIL branch target `{target}`",
        primary: "missing HIL branch target `{target}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilReturnTypeMismatch,
        code: 5418,
        message: "expected HIL return `{expected}`, found `{found}`",
        primary: "HIL return type mismatch",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilReturnValueMissing,
        code: 5419,
        message: "missing HIL return value for result `{expected}`",
        primary: "missing HIL return value for result `{expected}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilReturnValueUnexpected,
        code: 5420,
        message: "unexpected HIL return value for unit result `()`",
        primary: "unexpected HIL return value for unit result `()`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilShapeRequired,
        code: 5421,
        message: "HIL shape `{shape}` required",
        primary: "HIL shape `{shape}` required",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextExpectedForm,
        code: 5422,
        message: "expected SEAM text form `{form}`",
        primary: "expected `{form}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextMissingOperand,
        code: 5423,
        message: "missing SEAM text operand `{operand}`",
        primary: "missing operand `{operand}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextInvalidOperand,
        code: 5424,
        message: "invalid SEAM text operand `{operand}` value `{value}`",
        primary: "invalid operand `{operand}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextUnknownDirective,
        code: 5425,
        message: "unknown SEAM directive `{directive}`",
        primary: "unknown directive `{directive}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextUnknownOpcode,
        code: 5426,
        message: "unknown SEAM opcode `{opcode}`",
        primary: "unknown opcode `{opcode}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextUnknownSymbol,
        code: 5427,
        message: "unknown SEAM `{kind}` symbol `{symbol}`",
        primary: "unknown `{kind}` symbol `{symbol}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextDuplicateSymbol,
        code: 5428,
        message: "duplicate SEAM `{kind}` symbol `{symbol}`",
        primary: "duplicate `{kind}` symbol `{symbol}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextUnterminatedString,
        code: 5429,
        message: "unterminated SEAM string literal `{literal}`",
        primary: "unterminated string literal",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextUnexpectedEnd,
        code: 5430,
        message: "unexpected `.end` outside procedure",
        primary: "unexpected `.end`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextUnterminatedProcedure,
        code: 5431,
        message: "unterminated procedure block `{procedure}`",
        primary: "missing `.end` for procedure `{procedure}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextCountMismatch,
        code: 5432,
        message: "SEAM `{kind}` count expected `{expected}`, found `{found}`",
        primary: "`{kind}` count mismatch",
        secondary: None,
        help: None,
    },
];

fn entry(kind: SeamDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: SeamDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: SeamDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: SeamDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn render_message(kind: SeamDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).message)
}

pub fn render_primary(kind: SeamDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).primary)
}

pub fn secondary(kind: SeamDiagKind) -> Option<&'static str> {
    entry(kind).secondary
}

pub fn render_secondary(kind: SeamDiagKind, context: &DiagContext) -> Option<String> {
    entry(kind)
        .secondary
        .map(|secondary| context.render(secondary))
}

pub fn help(kind: SeamDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<SeamDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

pub const fn assembly_error_kind(source: &crate::AssemblyError) -> SeamDiagKind {
    match source {
        crate::AssemblyError::ArtifactValidationFailed(_) => SeamDiagKind::ArtifactValidationFailed,
        crate::AssemblyError::InvalidBinaryHeader => SeamDiagKind::InvalidBinaryHeader,
        crate::AssemblyError::UnsupportedBinaryVersion(_) => SeamDiagKind::UnsupportedBinaryVersion,
        crate::AssemblyError::UnknownSectionTag(_) => SeamDiagKind::UnknownSectionTag,
        crate::AssemblyError::BinaryPayloadTruncated => SeamDiagKind::BinaryPayloadTruncated,
        crate::AssemblyError::UnknownOpcode(_) => SeamDiagKind::UnknownOpcode,
        crate::AssemblyError::TextParseFailed(_) => SeamDiagKind::TextParseFailed,
    }
}

pub const fn artifact_error_kind(source: &crate::ArtifactError) -> SeamDiagKind {
    match source {
        crate::ArtifactError::InvalidReference { .. } => SeamDiagKind::InvalidReference,
        crate::ArtifactError::DuplicateLabel { .. } => SeamDiagKind::DuplicateLabel,
        crate::ArtifactError::MissingLabel { .. } => SeamDiagKind::MissingLabel,
        crate::ArtifactError::InvalidEffectOp => SeamDiagKind::InvalidEffectOp,
        crate::ArtifactError::OperandShapeMismatch { .. } => SeamDiagKind::OperandShapeMismatch,
    }
}

pub const fn hil_verify_error_kind(source: &crate::HilVerifyError) -> SeamDiagKind {
    match source {
        crate::HilVerifyError::MissingEntryBlock { .. } => SeamDiagKind::HilMissingEntryBlock,
        crate::HilVerifyError::DuplicateBlock { .. } => SeamDiagKind::HilDuplicateBlock,
        crate::HilVerifyError::DuplicateValue { .. } => SeamDiagKind::HilDuplicateValue,
        crate::HilVerifyError::UndefinedValue { .. } => SeamDiagKind::HilUndefinedValue,
        crate::HilVerifyError::TypeMismatch { .. } => SeamDiagKind::HilTypeMismatch,
        crate::HilVerifyError::MissingBlockTarget { .. } => SeamDiagKind::HilMissingBlockTarget,
        crate::HilVerifyError::ReturnTypeMismatch { .. } => SeamDiagKind::HilReturnTypeMismatch,
        crate::HilVerifyError::ReturnValueMissing { .. } => SeamDiagKind::HilReturnValueMissing,
        crate::HilVerifyError::ReturnValueUnexpected => SeamDiagKind::HilReturnValueUnexpected,
        crate::HilVerifyError::ShapeRequired { .. } => SeamDiagKind::HilShapeRequired,
    }
}
