// @generated by musi_diaggen. Do not edit by hand.

use super::SeamDiagKind;

struct CatalogEntry {
    kind: SeamDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: SeamDiagKind::ArtifactValidationFailed,
        code: 5400,
        message: "artifact validation failed (`{source}`)",
        primary: "artifact validation failed",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::InvalidBinaryHeader,
        code: 5401,
        message: "invalid binary header",
        primary: "invalid binary header",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::UnsupportedBinaryVersion,
        code: 5402,
        message: "unsupported binary version `{version}`",
        primary: "unsupported binary version `{version}`",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::UnknownSectionTag,
        code: 5403,
        message: "unknown section tag `{tag}`",
        primary: "unknown section tag `{tag}`",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::BinaryPayloadTruncated,
        code: 5404,
        message: "binary payload truncated",
        primary: "binary payload truncated",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::UnknownOpcode,
        code: 5405,
        message: "unknown opcode `{opcode}`",
        primary: "unknown opcode `{opcode}`",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::TextParseFailed,
        code: 5406,
        message: "text parse failed (`{source}`)",
        primary: "text parse failed",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::InvalidReference,
        code: 5407,
        message: "table reference `{table}` out of bounds",
        primary: "table reference `{table}` out of bounds",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::DuplicateLabel,
        code: 5408,
        message: "duplicate label in procedure `{procedure}`",
        primary: "duplicate label in procedure `{procedure}`",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::MissingLabel,
        code: 5409,
        message: "missing label reference in procedure `{procedure}`",
        primary: "missing label reference in procedure `{procedure}`",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::InvalidEffectOp,
        code: 5410,
        message: "invalid effect operation reference",
        primary: "invalid effect operation reference",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::OperandShapeMismatch,
        code: 5411,
        message: "opcode `{opcode}` operand shape mismatch",
        primary: "opcode `{opcode}` operand shape mismatch",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilMissingEntryBlock,
        code: 5412,
        message: "missing entry block in HIL function `{function}`",
        primary: "missing entry block in HIL function `{function}`",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilDuplicateBlock,
        code: 5413,
        message: "duplicate block `{block}` in HIL function `{function}`",
        primary: "duplicate HIL block `{block}`",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilDuplicateValue,
        code: 5414,
        message: "HIL value `{value}` defined more than once",
        primary: "duplicate HIL value `{value}`",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilUndefinedValue,
        code: 5415,
        message: "HIL value `{value}` used before definition",
        primary: "HIL value `{value}` undefined",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilTypeMismatch,
        code: 5416,
        message: "HIL value `{value}` expected `{expected}`, found `{found}`",
        primary: "HIL value `{value}` type mismatch",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilMissingBlockTarget,
        code: 5417,
        message: "missing HIL branch target `{target}`",
        primary: "missing HIL branch target `{target}`",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilReturnTypeMismatch,
        code: 5418,
        message: "HIL return expected `{expected}`, found `{found}`",
        primary: "HIL return type mismatch",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilReturnValueMissing,
        code: 5419,
        message: "missing HIL return value for result `{expected}`",
        primary: "missing HIL return value",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilReturnValueUnexpected,
        code: 5420,
        message: "HIL return value unexpected for unit result",
        primary: "HIL return value unexpected",
        help: None,
    },
    CatalogEntry {
        kind: SeamDiagKind::HilCapabilityRequired,
        code: 5421,
        message: "HIL capability `{capability}` required",
        primary: "HIL capability `{capability}` required",
        help: None,
    },
];

fn entry(kind: SeamDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: SeamDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: SeamDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: SeamDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn help(kind: SeamDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<SeamDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

pub const fn assembly_error_kind(source: &crate::AssemblyError) -> SeamDiagKind {
    match source {
        crate::AssemblyError::ArtifactValidationFailed(_) => SeamDiagKind::ArtifactValidationFailed,
        crate::AssemblyError::InvalidBinaryHeader => SeamDiagKind::InvalidBinaryHeader,
        crate::AssemblyError::UnsupportedBinaryVersion(_) => SeamDiagKind::UnsupportedBinaryVersion,
        crate::AssemblyError::UnknownSectionTag(_) => SeamDiagKind::UnknownSectionTag,
        crate::AssemblyError::BinaryPayloadTruncated => SeamDiagKind::BinaryPayloadTruncated,
        crate::AssemblyError::UnknownOpcode(_) => SeamDiagKind::UnknownOpcode,
        crate::AssemblyError::TextParseFailed(_) => SeamDiagKind::TextParseFailed,
    }
}

pub const fn artifact_error_kind(source: &crate::ArtifactError) -> SeamDiagKind {
    match source {
        crate::ArtifactError::InvalidReference { .. } => SeamDiagKind::InvalidReference,
        crate::ArtifactError::DuplicateLabel { .. } => SeamDiagKind::DuplicateLabel,
        crate::ArtifactError::MissingLabel { .. } => SeamDiagKind::MissingLabel,
        crate::ArtifactError::InvalidEffectOp => SeamDiagKind::InvalidEffectOp,
        crate::ArtifactError::OperandShapeMismatch { .. } => SeamDiagKind::OperandShapeMismatch,
    }
}

pub const fn hil_verify_error_kind(source: &crate::HilVerifyError) -> SeamDiagKind {
    match source {
        crate::HilVerifyError::MissingEntryBlock { .. } => SeamDiagKind::HilMissingEntryBlock,
        crate::HilVerifyError::DuplicateBlock { .. } => SeamDiagKind::HilDuplicateBlock,
        crate::HilVerifyError::DuplicateValue { .. } => SeamDiagKind::HilDuplicateValue,
        crate::HilVerifyError::UndefinedValue { .. } => SeamDiagKind::HilUndefinedValue,
        crate::HilVerifyError::TypeMismatch { .. } => SeamDiagKind::HilTypeMismatch,
        crate::HilVerifyError::MissingBlockTarget { .. } => SeamDiagKind::HilMissingBlockTarget,
        crate::HilVerifyError::ReturnTypeMismatch { .. } => SeamDiagKind::HilReturnTypeMismatch,
        crate::HilVerifyError::ReturnValueMissing { .. } => SeamDiagKind::HilReturnValueMissing,
        crate::HilVerifyError::ReturnValueUnexpected => SeamDiagKind::HilReturnValueUnexpected,
        crate::HilVerifyError::CapabilityRequired { .. } => SeamDiagKind::HilCapabilityRequired,
    }
}
