use crate::instruction::OperandShape;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OpcodeFamily {
    Core,
    Storage,
    Scalar,
    Branch,
    Call,
    Object,
    Type,
    Ref,
    Effect,
    Module,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Opcode {
    Nop,
    Trap,
    Pop,
    Dup,
    Swap,
    LdUnit,
    LdTrue,
    LdFalse,
    LdNull,
    LdC,
    LdCI4,
    LdCI8,
    LdCF4,
    LdCF8,
    LdStr,
    LdArg,
    StArg,
    LdLoc,
    StLoc,
    LdGlob,
    StGlob,
    LdFld,
    StFld,
    LdFldA,
    InitObj,
    LdDflt,
    Neg,
    Add,
    Sub,
    Mul,
    AddOvf,
    SubOvf,
    MulOvf,
    DivS,
    DivU,
    RemS,
    RemU,
    And,
    Or,
    Xor,
    Not,
    Shl,
    ShrS,
    ShrU,
    Rotl,
    Rotr,
    Clz,
    Ctz,
    Popcnt,
    Ceq,
    Cne,
    CltS,
    CltU,
    CgtS,
    CgtU,
    CleS,
    CleU,
    CgeS,
    CgeU,
    Br,
    BrTrue,
    BrFalse,
    BrTbl,
    Leave,
    Ret,
    Throw,
    Rethrow,
    Unreach,
    Call,
    CallInd,
    CallVirt,
    CallIface,
    CallDyn,
    CallFfi,
    TailCall,
    TailCallInd,
    TailCallVirt,
    TailCallIface,
    TailCallDyn,
    TailCallFfi,
    LdFn,
    NewFn,
    LdVirtFn,
    LdIfaceFn,
    LdDynFn,
    LdFfi,
    NewObj,
    NewArr,
    ArrNew,
    LdElem,
    StElem,
    LdElemA,
    LdLen,
    Slice,
    CpObj,
    DupObj,
    DropObj,
    LdType,
    TypeOf,
    IsInst,
    Cast,
    Conv,
    ConvOvf,
    ConvS,
    ConvU,
    ConvOvfS,
    ConvOvfU,
    Box,
    Unbox,
    SizeOf,
    AlignOf,
    LdTok,
    LdInd,
    StInd,
    RefAny,
    EndRef,
    Pin,
    Unpin,
    LdAddr,
    PtrEq,
    PtrCast,
    HdlPush,
    HdlPop,
    Raise,
    Resume,
    DropCont,
    LdImp,
    LdExp,
    MdlLoad,
    MdlGet,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OpcodeWire {
    Core(u8),
    Extended(u16),
}

const EXTENDED_OPCODE_PREFIX: u8 = 0xFF;

impl Opcode {
    #[must_use]
    pub fn family(self) -> OpcodeFamily {
        self.info().family
    }
    #[must_use]
    pub fn mnemonic(self) -> &'static str {
        self.info().mnemonic
    }
    #[must_use]
    pub fn operand_shape(self) -> OperandShape {
        self.info().operand_shape
    }
    #[must_use]
    pub fn wire_code(self) -> u16 {
        match self.info().wire {
            OpcodeWire::Core(code) => u16::from(code),
            OpcodeWire::Extended(code) => code,
        }
    }
    #[must_use]
    pub fn wire(self) -> OpcodeWire {
        self.info().wire
    }
    #[must_use]
    pub const fn extended_opcode_prefix() -> u8 {
        EXTENDED_OPCODE_PREFIX
    }
    #[must_use]
    pub fn from_mnemonic(text: &str) -> Option<Self> {
        OPCODE_INFOS
            .iter()
            .find(|info| info.mnemonic == text)
            .map(|info| info.opcode)
    }
    #[must_use]
    pub fn from_wire_code(code: u16) -> Option<Self> {
        OPCODE_INFOS
            .iter()
            .find(|info| match info.wire {
                OpcodeWire::Core(core_wire) => u16::from(core_wire) == code,
                OpcodeWire::Extended(extended) => extended == code,
            })
            .map(|info| info.opcode)
    }
    fn info(self) -> &'static OpcodeInfo {
        OPCODE_INFOS
            .iter()
            .find(|info| info.opcode == self)
            .unwrap_or(&OPCODE_INFOS[0])
    }
}

struct OpcodeInfo {
    opcode: Opcode,
    family: OpcodeFamily,
    mnemonic: &'static str,
    operand_shape: OperandShape,
    wire: OpcodeWire,
}

const fn info(
    opcode: Opcode,
    family: OpcodeFamily,
    mnemonic: &'static str,
    operand_shape: OperandShape,
    code: u8,
) -> OpcodeInfo {
    OpcodeInfo {
        opcode,
        family,
        mnemonic,
        operand_shape,
        wire: OpcodeWire::Core(code),
    }
}

const OPCODE_INFOS: &[OpcodeInfo] = &[
    info(
        Opcode::Nop,
        OpcodeFamily::Core,
        "nop",
        OperandShape::None,
        0x00,
    ),
    info(
        Opcode::Trap,
        OpcodeFamily::Core,
        "trap",
        OperandShape::String,
        0x01,
    ),
    info(
        Opcode::Pop,
        OpcodeFamily::Core,
        "pop",
        OperandShape::None,
        0x02,
    ),
    info(
        Opcode::Dup,
        OpcodeFamily::Core,
        "dup",
        OperandShape::None,
        0x03,
    ),
    info(
        Opcode::Swap,
        OpcodeFamily::Core,
        "swap",
        OperandShape::None,
        0x04,
    ),
    info(
        Opcode::LdUnit,
        OpcodeFamily::Core,
        "ld.unit",
        OperandShape::None,
        0x05,
    ),
    info(
        Opcode::LdTrue,
        OpcodeFamily::Core,
        "ld.true",
        OperandShape::None,
        0x06,
    ),
    info(
        Opcode::LdFalse,
        OpcodeFamily::Core,
        "ld.false",
        OperandShape::None,
        0x07,
    ),
    info(
        Opcode::LdNull,
        OpcodeFamily::Core,
        "ld.null",
        OperandShape::Type,
        0x08,
    ),
    info(
        Opcode::LdC,
        OpcodeFamily::Core,
        "ld.c",
        OperandShape::Constant,
        0x09,
    ),
    info(
        Opcode::LdCI4,
        OpcodeFamily::Core,
        "ld.c.i4",
        OperandShape::I16,
        0x0A,
    ),
    info(
        Opcode::LdCI8,
        OpcodeFamily::Core,
        "ld.c.i8",
        OperandShape::I16,
        0x0B,
    ),
    info(
        Opcode::LdCF4,
        OpcodeFamily::Core,
        "ld.c.f4",
        OperandShape::I16,
        0x0C,
    ),
    info(
        Opcode::LdCF8,
        OpcodeFamily::Core,
        "ld.c.f8",
        OperandShape::I16,
        0x0D,
    ),
    info(
        Opcode::LdStr,
        OpcodeFamily::Core,
        "ld.str",
        OperandShape::String,
        0x0E,
    ),
    info(
        Opcode::LdArg,
        OpcodeFamily::Storage,
        "ld.arg",
        OperandShape::Local,
        0x10,
    ),
    info(
        Opcode::StArg,
        OpcodeFamily::Storage,
        "st.arg",
        OperandShape::Local,
        0x11,
    ),
    info(
        Opcode::LdLoc,
        OpcodeFamily::Storage,
        "ld.loc",
        OperandShape::Local,
        0x12,
    ),
    info(
        Opcode::StLoc,
        OpcodeFamily::Storage,
        "st.loc",
        OperandShape::Local,
        0x13,
    ),
    info(
        Opcode::LdGlob,
        OpcodeFamily::Storage,
        "ld.glob",
        OperandShape::Global,
        0x14,
    ),
    info(
        Opcode::StGlob,
        OpcodeFamily::Storage,
        "st.glob",
        OperandShape::Global,
        0x15,
    ),
    info(
        Opcode::LdFld,
        OpcodeFamily::Storage,
        "ld.fld",
        OperandShape::I16,
        0x16,
    ),
    info(
        Opcode::StFld,
        OpcodeFamily::Storage,
        "st.fld",
        OperandShape::I16,
        0x17,
    ),
    info(
        Opcode::LdFldA,
        OpcodeFamily::Storage,
        "ld.fld.a",
        OperandShape::I16,
        0x18,
    ),
    info(
        Opcode::InitObj,
        OpcodeFamily::Storage,
        "init.obj",
        OperandShape::Type,
        0x19,
    ),
    info(
        Opcode::LdDflt,
        OpcodeFamily::Storage,
        "ld.dflt",
        OperandShape::Type,
        0x1A,
    ),
    info(
        Opcode::Neg,
        OpcodeFamily::Scalar,
        "neg",
        OperandShape::None,
        0x20,
    ),
    info(
        Opcode::Add,
        OpcodeFamily::Scalar,
        "add",
        OperandShape::None,
        0x21,
    ),
    info(
        Opcode::Sub,
        OpcodeFamily::Scalar,
        "sub",
        OperandShape::None,
        0x22,
    ),
    info(
        Opcode::Mul,
        OpcodeFamily::Scalar,
        "mul",
        OperandShape::None,
        0x23,
    ),
    info(
        Opcode::AddOvf,
        OpcodeFamily::Scalar,
        "add.ovf",
        OperandShape::None,
        0x24,
    ),
    info(
        Opcode::SubOvf,
        OpcodeFamily::Scalar,
        "sub.ovf",
        OperandShape::None,
        0x25,
    ),
    info(
        Opcode::MulOvf,
        OpcodeFamily::Scalar,
        "mul.ovf",
        OperandShape::None,
        0x26,
    ),
    info(
        Opcode::DivS,
        OpcodeFamily::Scalar,
        "div.s",
        OperandShape::None,
        0x27,
    ),
    info(
        Opcode::DivU,
        OpcodeFamily::Scalar,
        "div.u",
        OperandShape::None,
        0x28,
    ),
    info(
        Opcode::RemS,
        OpcodeFamily::Scalar,
        "rem.s",
        OperandShape::None,
        0x29,
    ),
    info(
        Opcode::RemU,
        OpcodeFamily::Scalar,
        "rem.u",
        OperandShape::None,
        0x2A,
    ),
    info(
        Opcode::And,
        OpcodeFamily::Scalar,
        "and",
        OperandShape::None,
        0x2B,
    ),
    info(
        Opcode::Or,
        OpcodeFamily::Scalar,
        "or",
        OperandShape::None,
        0x2C,
    ),
    info(
        Opcode::Xor,
        OpcodeFamily::Scalar,
        "xor",
        OperandShape::None,
        0x2D,
    ),
    info(
        Opcode::Not,
        OpcodeFamily::Scalar,
        "not",
        OperandShape::None,
        0x2E,
    ),
    info(
        Opcode::Shl,
        OpcodeFamily::Scalar,
        "shl",
        OperandShape::None,
        0x2F,
    ),
    info(
        Opcode::ShrS,
        OpcodeFamily::Scalar,
        "shr.s",
        OperandShape::None,
        0x30,
    ),
    info(
        Opcode::ShrU,
        OpcodeFamily::Scalar,
        "shr.u",
        OperandShape::None,
        0x31,
    ),
    info(
        Opcode::Rotl,
        OpcodeFamily::Scalar,
        "rotl",
        OperandShape::None,
        0x32,
    ),
    info(
        Opcode::Rotr,
        OpcodeFamily::Scalar,
        "rotr",
        OperandShape::None,
        0x33,
    ),
    info(
        Opcode::Clz,
        OpcodeFamily::Scalar,
        "clz",
        OperandShape::None,
        0x34,
    ),
    info(
        Opcode::Ctz,
        OpcodeFamily::Scalar,
        "ctz",
        OperandShape::None,
        0x35,
    ),
    info(
        Opcode::Popcnt,
        OpcodeFamily::Scalar,
        "popcnt",
        OperandShape::None,
        0x36,
    ),
    info(
        Opcode::Ceq,
        OpcodeFamily::Scalar,
        "ceq",
        OperandShape::None,
        0x37,
    ),
    info(
        Opcode::Cne,
        OpcodeFamily::Scalar,
        "cne",
        OperandShape::None,
        0x38,
    ),
    info(
        Opcode::CltS,
        OpcodeFamily::Scalar,
        "clt.s",
        OperandShape::None,
        0x39,
    ),
    info(
        Opcode::CltU,
        OpcodeFamily::Scalar,
        "clt.u",
        OperandShape::None,
        0x3A,
    ),
    info(
        Opcode::CgtS,
        OpcodeFamily::Scalar,
        "cgt.s",
        OperandShape::None,
        0x3B,
    ),
    info(
        Opcode::CgtU,
        OpcodeFamily::Scalar,
        "cgt.u",
        OperandShape::None,
        0x3C,
    ),
    info(
        Opcode::CleS,
        OpcodeFamily::Scalar,
        "cle.s",
        OperandShape::None,
        0x3D,
    ),
    info(
        Opcode::CleU,
        OpcodeFamily::Scalar,
        "cle.u",
        OperandShape::None,
        0x3E,
    ),
    info(
        Opcode::CgeS,
        OpcodeFamily::Scalar,
        "cge.s",
        OperandShape::None,
        0x40,
    ),
    info(
        Opcode::CgeU,
        OpcodeFamily::Scalar,
        "cge.u",
        OperandShape::None,
        0x41,
    ),
    info(
        Opcode::Br,
        OpcodeFamily::Branch,
        "br",
        OperandShape::Label,
        0x42,
    ),
    info(
        Opcode::BrTrue,
        OpcodeFamily::Branch,
        "br.true",
        OperandShape::Label,
        0x43,
    ),
    info(
        Opcode::BrFalse,
        OpcodeFamily::Branch,
        "br.false",
        OperandShape::Label,
        0x44,
    ),
    info(
        Opcode::BrTbl,
        OpcodeFamily::Branch,
        "br.tbl",
        OperandShape::BranchTable,
        0x45,
    ),
    info(
        Opcode::Leave,
        OpcodeFamily::Branch,
        "leave",
        OperandShape::Label,
        0x46,
    ),
    info(
        Opcode::Ret,
        OpcodeFamily::Branch,
        "ret",
        OperandShape::None,
        0x47,
    ),
    info(
        Opcode::Throw,
        OpcodeFamily::Branch,
        "throw",
        OperandShape::None,
        0x48,
    ),
    info(
        Opcode::Rethrow,
        OpcodeFamily::Branch,
        "rethrow",
        OperandShape::None,
        0x49,
    ),
    info(
        Opcode::Unreach,
        OpcodeFamily::Branch,
        "unreach",
        OperandShape::None,
        0x4A,
    ),
    info(
        Opcode::Call,
        OpcodeFamily::Call,
        "call",
        OperandShape::Procedure,
        0x50,
    ),
    info(
        Opcode::CallInd,
        OpcodeFamily::Call,
        "call.ind",
        OperandShape::None,
        0x51,
    ),
    info(
        Opcode::CallVirt,
        OpcodeFamily::Call,
        "call.virt",
        OperandShape::Procedure,
        0x52,
    ),
    info(
        Opcode::CallIface,
        OpcodeFamily::Call,
        "call.iface",
        OperandShape::Procedure,
        0x53,
    ),
    info(
        Opcode::CallDyn,
        OpcodeFamily::Call,
        "call.dyn",
        OperandShape::Procedure,
        0x54,
    ),
    info(
        Opcode::CallFfi,
        OpcodeFamily::Call,
        "call.ffi",
        OperandShape::Foreign,
        0x55,
    ),
    info(
        Opcode::TailCall,
        OpcodeFamily::Call,
        "tail.call",
        OperandShape::Procedure,
        0x56,
    ),
    info(
        Opcode::TailCallInd,
        OpcodeFamily::Call,
        "tail.call.ind",
        OperandShape::Procedure,
        0x57,
    ),
    info(
        Opcode::TailCallVirt,
        OpcodeFamily::Call,
        "tail.call.virt",
        OperandShape::Procedure,
        0x58,
    ),
    info(
        Opcode::TailCallIface,
        OpcodeFamily::Call,
        "tail.call.iface",
        OperandShape::Procedure,
        0x59,
    ),
    info(
        Opcode::TailCallDyn,
        OpcodeFamily::Call,
        "tail.call.dyn",
        OperandShape::Procedure,
        0x5A,
    ),
    info(
        Opcode::TailCallFfi,
        OpcodeFamily::Call,
        "tail.call.ffi",
        OperandShape::Foreign,
        0x5B,
    ),
    info(
        Opcode::LdFn,
        OpcodeFamily::Call,
        "ld.fn",
        OperandShape::Procedure,
        0x5C,
    ),
    info(
        Opcode::NewFn,
        OpcodeFamily::Call,
        "new.fn",
        OperandShape::WideProcedureCaptures,
        0x5D,
    ),
    info(
        Opcode::LdVirtFn,
        OpcodeFamily::Call,
        "ld.virt.fn",
        OperandShape::Procedure,
        0x5E,
    ),
    info(
        Opcode::LdIfaceFn,
        OpcodeFamily::Call,
        "ld.iface.fn",
        OperandShape::Procedure,
        0x5F,
    ),
    info(
        Opcode::LdDynFn,
        OpcodeFamily::Call,
        "ld.dyn.fn",
        OperandShape::Procedure,
        0x60,
    ),
    info(
        Opcode::LdFfi,
        OpcodeFamily::Call,
        "ld.ffi",
        OperandShape::Foreign,
        0x61,
    ),
    info(
        Opcode::NewObj,
        OpcodeFamily::Object,
        "new.obj",
        OperandShape::TypeLen,
        0x70,
    ),
    info(
        Opcode::NewArr,
        OpcodeFamily::Object,
        "new.arr",
        OperandShape::TypeLen,
        0x71,
    ),
    info(
        Opcode::ArrNew,
        OpcodeFamily::Object,
        "arr.new",
        OperandShape::Type,
        0x72,
    ),
    info(
        Opcode::LdElem,
        OpcodeFamily::Object,
        "ld.elem",
        OperandShape::None,
        0x73,
    ),
    info(
        Opcode::StElem,
        OpcodeFamily::Object,
        "st.elem",
        OperandShape::None,
        0x74,
    ),
    info(
        Opcode::LdElemA,
        OpcodeFamily::Object,
        "ld.elem.a",
        OperandShape::Type,
        0x75,
    ),
    info(
        Opcode::LdLen,
        OpcodeFamily::Object,
        "ld.len",
        OperandShape::None,
        0x76,
    ),
    info(
        Opcode::Slice,
        OpcodeFamily::Object,
        "slice",
        OperandShape::None,
        0x77,
    ),
    info(
        Opcode::CpObj,
        OpcodeFamily::Object,
        "cp.obj",
        OperandShape::Type,
        0x78,
    ),
    info(
        Opcode::DupObj,
        OpcodeFamily::Object,
        "dup.obj",
        OperandShape::Type,
        0x79,
    ),
    info(
        Opcode::DropObj,
        OpcodeFamily::Object,
        "drop.obj",
        OperandShape::Type,
        0x7A,
    ),
    info(
        Opcode::LdType,
        OpcodeFamily::Type,
        "ld.type",
        OperandShape::Type,
        0x80,
    ),
    info(
        Opcode::TypeOf,
        OpcodeFamily::Type,
        "type.of",
        OperandShape::None,
        0x81,
    ),
    info(
        Opcode::IsInst,
        OpcodeFamily::Type,
        "is.inst",
        OperandShape::Type,
        0x82,
    ),
    info(
        Opcode::Cast,
        OpcodeFamily::Type,
        "cast",
        OperandShape::Type,
        0x83,
    ),
    info(
        Opcode::Conv,
        OpcodeFamily::Type,
        "conv",
        OperandShape::Type,
        0x84,
    ),
    info(
        Opcode::ConvOvf,
        OpcodeFamily::Type,
        "conv.ovf",
        OperandShape::Type,
        0x85,
    ),
    info(
        Opcode::ConvS,
        OpcodeFamily::Type,
        "conv.s",
        OperandShape::Type,
        0x86,
    ),
    info(
        Opcode::ConvU,
        OpcodeFamily::Type,
        "conv.u",
        OperandShape::Type,
        0x87,
    ),
    info(
        Opcode::ConvOvfS,
        OpcodeFamily::Type,
        "conv.ovf.s",
        OperandShape::Type,
        0x88,
    ),
    info(
        Opcode::ConvOvfU,
        OpcodeFamily::Type,
        "conv.ovf.u",
        OperandShape::Type,
        0x89,
    ),
    info(
        Opcode::Box,
        OpcodeFamily::Type,
        "box",
        OperandShape::Type,
        0x8A,
    ),
    info(
        Opcode::Unbox,
        OpcodeFamily::Type,
        "unbox",
        OperandShape::Type,
        0x8B,
    ),
    info(
        Opcode::SizeOf,
        OpcodeFamily::Type,
        "size.of",
        OperandShape::Type,
        0x8C,
    ),
    info(
        Opcode::AlignOf,
        OpcodeFamily::Type,
        "align.of",
        OperandShape::Type,
        0x8D,
    ),
    info(
        Opcode::LdTok,
        OpcodeFamily::Type,
        "ld.tok",
        OperandShape::Type,
        0x8E,
    ),
    info(
        Opcode::LdInd,
        OpcodeFamily::Ref,
        "ld.ind",
        OperandShape::Type,
        0x90,
    ),
    info(
        Opcode::StInd,
        OpcodeFamily::Ref,
        "st.ind",
        OperandShape::Type,
        0x91,
    ),
    info(
        Opcode::RefAny,
        OpcodeFamily::Ref,
        "ref.any",
        OperandShape::None,
        0x92,
    ),
    info(
        Opcode::EndRef,
        OpcodeFamily::Ref,
        "end.ref",
        OperandShape::None,
        0x93,
    ),
    info(
        Opcode::Pin,
        OpcodeFamily::Ref,
        "pin",
        OperandShape::None,
        0x94,
    ),
    info(
        Opcode::Unpin,
        OpcodeFamily::Ref,
        "unpin",
        OperandShape::None,
        0x95,
    ),
    info(
        Opcode::LdAddr,
        OpcodeFamily::Ref,
        "ld.addr",
        OperandShape::Type,
        0x96,
    ),
    info(
        Opcode::PtrEq,
        OpcodeFamily::Ref,
        "ptr.eq",
        OperandShape::None,
        0x97,
    ),
    info(
        Opcode::PtrCast,
        OpcodeFamily::Ref,
        "ptr.cast",
        OperandShape::Type,
        0x98,
    ),
    info(
        Opcode::HdlPush,
        OpcodeFamily::Effect,
        "hdl.push",
        OperandShape::EffectId,
        0xA0,
    ),
    info(
        Opcode::HdlPop,
        OpcodeFamily::Effect,
        "hdl.pop",
        OperandShape::None,
        0xA1,
    ),
    info(
        Opcode::Raise,
        OpcodeFamily::Effect,
        "raise",
        OperandShape::Effect,
        0xA2,
    ),
    info(
        Opcode::Resume,
        OpcodeFamily::Effect,
        "resume",
        OperandShape::None,
        0xA3,
    ),
    info(
        Opcode::DropCont,
        OpcodeFamily::Effect,
        "drop.cont",
        OperandShape::None,
        0xA4,
    ),
    info(
        Opcode::LdImp,
        OpcodeFamily::Module,
        "ld.imp",
        OperandShape::String,
        0xB0,
    ),
    info(
        Opcode::LdExp,
        OpcodeFamily::Module,
        "ld.exp",
        OperandShape::String,
        0xB1,
    ),
    info(
        Opcode::MdlLoad,
        OpcodeFamily::Module,
        "mdl.load",
        OperandShape::None,
        0xB2,
    ),
    info(
        Opcode::MdlGet,
        OpcodeFamily::Module,
        "mdl.get",
        OperandShape::String,
        0xB3,
    ),
];

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    mod success {
        use super::*;

        #[test]
        fn opcode_catalog_has_unique_mnemonics_and_wire_codes() {
            let mut mnemonics = BTreeSet::new();
            let mut wire_codes = BTreeSet::new();
            for info in OPCODE_INFOS {
                let wire = match info.wire {
                    OpcodeWire::Core(code) => u16::from(code),
                    OpcodeWire::Extended(code) => code,
                };
                assert!(
                    mnemonics.insert(info.mnemonic),
                    "duplicate mnemonic `{}`",
                    info.mnemonic
                );
                assert!(wire_codes.insert(wire), "duplicate wire code `{wire:#06x}`");
            }
            assert_eq!(mnemonics.len(), OPCODE_INFOS.len());
            assert_eq!(wire_codes.len(), OPCODE_INFOS.len());
        }

        #[test]
        fn opcode_mnemonics_fit_seam_style_constraints() {
            for info in OPCODE_INFOS {
                assert!(
                    info.mnemonic
                        .chars()
                        .all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '.'),
                    "mnemonic has invalid chars `{}`",
                    info.mnemonic
                );
            }
        }
    }

    mod failure {}
}
