import type { BookSectionDefinition } from "./types";

export const bookSections = [
	{
		id: "start-foundations",
		partId: "start",
		path: "/docs/book/start/foundations",
		aliases: [
			"/docs/language/start/foundations",
			"/learn/language/start/foundations",
		],
		title: "Foundations",
		description:
			"Install Musi, read one file, and learn expression-first flow.",
		group: "Start",
		section: "Foundations",
		order: 1,
		slug: "foundations",
		summary:
			"First setup and first-file habits: values, blocks, and explicit mutation.",
	},
	{
		id: "core-expressions",
		partId: "core",
		path: "/docs/book/core/expressions",
		aliases: [
			"/docs/language/core/expressions",
			"/learn/language/core/expressions",
		],
		title: "Expressions",
		description:
			"Learn literals, tuples, operators, and ranges for everyday calculations.",
		group: "Core Syntax",
		section: "Expressions",
		order: 1,
		slug: "expressions",
		summary: "Core value and operator forms used across normal Musi code.",
	},
	{
		id: "core-functions",
		partId: "core",
		path: "/docs/book/core/functions-and-calls",
		aliases: [
			"/docs/language/core/functions-and-calls",
			"/learn/language/core/functions-and-calls",
		],
		title: "Functions and Calls",
		description:
			"Define reusable functions, write lambdas, and choose call and method forms.",
		group: "Core Syntax",
		section: "Functions and Calls",
		order: 2,
		slug: "functions-and-calls",
		summary: "Function declarations, lambdas, and call-site reading patterns.",
	},
	{
		id: "data-modeling",
		partId: "data",
		path: "/docs/book/data/modeling",
		aliases: ["/docs/language/data/modeling", "/learn/language/data/modeling"],
		title: "Data Modeling",
		description: "Model records, variants, collections, and matching patterns.",
		group: "Data and Patterns",
		section: "Data Modeling",
		order: 1,
		slug: "modeling",
		summary:
			"Build domain data with records and variants, then read and transform with patterns.",
	},
	{
		id: "organization-modules",
		partId: "organization",
		path: "/docs/book/organization/modules",
		aliases: [
			"/docs/language/organization/modules",
			"/learn/language/organization/modules",
		],
		title: "Files and Modules",
		description:
			"Structure files, packages, and imports so projects stay navigable.",
		group: "Organization and Modules",
		section: "Files and Modules",
		order: 1,
		slug: "modules",
		summary:
			"Project layout, package boundaries, and import/export discipline.",
	},
	{
		id: "types-foundations",
		partId: "types",
		path: "/docs/book/types/foundations",
		aliases: [
			"/docs/language/types/foundations",
			"/learn/language/types/foundations",
		],
		title: "Type Foundations",
		description:
			"Type annotations, inference, generics, callable types, and checks.",
		group: "Types and Generic Design",
		section: "Type Foundations",
		order: 1,
		slug: "foundations",
		summary:
			"Type reading and design patterns from everyday annotations to advanced forms.",
	},
	{
		id: "abstractions-laws",
		partId: "abstractions",
		path: "/docs/book/abstractions/classes-instances-laws",
		aliases: [
			"/docs/language/abstractions/classes-instances-laws",
			"/learn/language/abstractions/classes-instances-laws",
		],
		title: "Classes, Instances, and Laws",
		description:
			"Define reusable interfaces, implementations, and behavior constraints.",
		group: "Abstractions",
		section: "Classes and Laws",
		order: 1,
		slug: "classes-instances-laws",
		summary:
			"Shared behavior contracts and law-oriented implementation discipline.",
	},
	{
		id: "effects-handling",
		partId: "effects-runtime",
		path: "/docs/book/effects-runtime/handling",
		aliases: [
			"/docs/language/effects-runtime/handling",
			"/learn/language/effects-runtime/handling",
		],
		title: "Effect Handling",
		description:
			"Request operations and handle them with explicit handler scopes.",
		group: "Effects and Runtime",
		section: "Effect Handling",
		order: 1,
		slug: "handling",
		summary: "Effect requests, using scopes, and handler composition.",
	},
	{
		id: "effects-runtime-model",
		partId: "effects-runtime",
		path: "/docs/book/effects-runtime/runtime-model",
		aliases: [
			"/docs/language/effects-runtime/runtime-model",
			"/learn/language/effects-runtime/runtime-model",
		],
		title: "Runtime Model",
		description: "Understand runtime boundaries and stdlib effect patterns.",
		group: "Effects and Runtime",
		section: "Runtime Model",
		order: 2,
		slug: "runtime-model",
		summary:
			"Runtime behavior, operational model, and standard library integration.",
	},
	{
		id: "developers-guides",
		partId: "developers",
		path: "/docs/book/developers/guides",
		aliases: [
			"/docs/language/developers/guides",
			"/learn/language/developers/guides",
		],
		title: "Language Guides",
		description:
			"Map existing language habits to Musi with practical side-by-side guidance.",
		group: "Musi for Developers",
		section: "Language Guides",
		order: 1,
		slug: "guides",
		summary:
			"Comparative guides for teams moving from other language ecosystems.",
	},
	{
		id: "developers-c-cpp",
		partId: "developers",
		parentId: "developers-guides",
		path: "/docs/book/developers/guides/c-cpp",
		aliases: [
			"/docs/book/developers/guides/c",
			"/learn/book/developers/guides/c",
			"/docs/book/developers/guides/cpp",
			"/learn/book/developers/guides/cpp",
			"/docs/book/developers/guides/c-plus-plus",
			"/learn/book/developers/guides/c-plus-plus",
			"/docs/book/developers/c",
			"/learn/book/developers/c",
			"/docs/book/developers/cpp",
			"/learn/book/developers/cpp",
			"/docs/book/developers/c-plus-plus",
			"/learn/book/developers/c-plus-plus",
			"/docs/book/developers/c-and-cpp",
			"/learn/book/developers/c-and-cpp",
			"/docs/language/developers/c",
			"/learn/language/developers/c",
			"/docs/language/developers/cpp",
			"/learn/language/developers/cpp",
			"/docs/language/developers/c-plus-plus",
			"/learn/language/developers/c-plus-plus",
		],
		title: "Musi for C/C++ Developers",
		description:
			"Translate C23 and C++23 habits into Musi's expression, data, effect, and FFI model.",
		group: "Musi for Developers",
		section: "C/C++ Developers",
		order: 1,
		slug: "c-cpp",
		summary:
			"C/C++-specific contrasts for functions, structs, arrays, pointers, errors, templates, packages, tests, and native boundaries.",
	},
	{
		id: "developers-rust",
		partId: "developers",
		parentId: "developers-guides",
		path: "/docs/book/developers/guides/rust",
		aliases: [
			"/docs/book/developers/rust",
			"/docs/language/developers/rust-guide",
			"/learn/language/developers/rust-guide",
		],
		title: "Musi for Rust Developers",
		description:
			"Translate Rust habits into Musi's expression, data, abstraction, and mutation model.",
		group: "Musi for Developers",
		section: "Rust Developers",
		order: 8,
		slug: "rust",
		summary:
			"Rust-specific contrasts for mutation, data, traits, effects, and native boundaries.",
	},
	{
		id: "developers-csharp",
		partId: "developers",
		parentId: "developers-guides",
		path: "/docs/book/developers/guides/csharp",
		aliases: [
			"/docs/book/developers/guides/c-sharp",
			"/learn/book/developers/guides/c-sharp",
			"/docs/book/developers/csharp",
			"/docs/book/developers/c-sharp",
			"/learn/book/developers/c-sharp",
			"/docs/language/developers/csharp",
			"/docs/language/developers/c-sharp",
			"/learn/language/developers/csharp",
			"/learn/language/developers/c-sharp",
		],
		title: "Musi for C# Developers",
		description:
			"Translate .NET 8.0 and C# 12.0 habits into Musi's expression, data, effect, and package model.",
		group: "Musi for Developers",
		section: "C# Developers",
		order: 2,
		slug: "csharp",
		summary:
			"C#-specific contrasts for methods, records, collections, nullability, exceptions, interfaces, packages, tests, and native boundaries.",
	},
	{
		id: "developers-go",
		partId: "developers",
		parentId: "developers-guides",
		path: "/docs/book/developers/guides/go",
		aliases: [
			"/docs/book/developers/go",
			"/learn/book/developers/go",
			"/docs/language/developers/go",
			"/learn/language/developers/go",
		],
		title: "Musi for Go Developers",
		description:
			"Translate Go 1.26.2 habits into Musi's expression, data, effect, and package model.",
		group: "Musi for Developers",
		section: "Go Developers",
		order: 3,
		slug: "go",
		summary:
			"Go-specific contrasts for functions, structs, slices, nil, errors, concurrency, interfaces, packages, tests, and native boundaries.",
	},
	{
		id: "developers-javascript-typescript",
		partId: "developers",
		parentId: "developers-guides",
		path: "/docs/book/developers/guides/javascript-typescript",
		aliases: [
			"/docs/book/developers/guides/javascript",
			"/docs/book/developers/guides/typescript",
			"/docs/book/developers/javascript",
			"/docs/book/developers/typescript",
			"/docs/language/developers/javascript",
			"/docs/language/developers/typescript",
			"/learn/language/developers/javascript",
			"/learn/language/developers/typescript",
		],
		title: "Musi for JavaScript and TypeScript Developers",
		description:
			"Translate JavaScript runtime habits and TypeScript 6.0.2 type habits into Musi.",
		group: "Musi for Developers",
		section: "JavaScript and TypeScript Developers",
		order: 5,
		slug: "javascript-typescript",
		summary:
			"Side-by-side contrasts for objects, functions, unions, generics, promises, modules, and tests.",
	},
	{
		id: "developers-lua",
		partId: "developers",
		parentId: "developers-guides",
		path: "/docs/book/developers/guides/lua",
		aliases: [
			"/docs/book/developers/lua",
			"/learn/book/developers/lua",
			"/docs/language/developers/lua",
			"/learn/language/developers/lua",
		],
		title: "Musi for Lua Developers",
		description:
			"Translate Lua 5.4.8 habits into Musi's expression, data, effect, and package model.",
		group: "Musi for Developers",
		section: "Lua Developers",
		order: 6,
		slug: "lua",
		summary:
			"Lua-specific contrasts for locals, functions, tables, nil, errors, coroutines, metatables, modules, tests, and native boundaries.",
	},
	{
		id: "developers-java",
		partId: "developers",
		parentId: "developers-guides",
		path: "/docs/book/developers/guides/java",
		aliases: [
			"/docs/book/developers/java",
			"/learn/book/developers/java",
			"/docs/language/developers/java",
			"/learn/language/developers/java",
		],
		title: "Musi for Java Developers",
		description:
			"Translate Java 17 habits into Musi's expression, data, effect, and package model.",
		group: "Musi for Developers",
		section: "Java Developers",
		order: 4,
		slug: "java",
		summary:
			"Java-specific contrasts for methods, records, collections, nullability, exceptions, sealed types, interfaces, packages, tests, and native boundaries.",
	},
	{
		id: "developers-python",
		partId: "developers",
		parentId: "developers-guides",
		path: "/docs/book/developers/guides/python",
		aliases: [
			"/docs/book/developers/python",
			"/docs/language/developers/python",
			"/learn/language/developers/python",
		],
		title: "Musi for Python Developers",
		description:
			"Translate Python 3.14 habits into Musi's expression, data, effect, and package model.",
		group: "Musi for Developers",
		section: "Python Developers",
		order: 7,
		slug: "python",
		summary:
			"Python-specific contrasts for functions, blocks, objects, collections, errors, protocols, modules, tests, and native boundaries.",
	},
	{
		id: "advanced-interop",
		partId: "advanced",
		path: "/docs/book/advanced/interop",
		aliases: [
			"/docs/language/advanced/interop",
			"/learn/language/advanced/interop",
		],
		title: "Interop and Safety",
		description:
			"Use attributes, foreign declarations, and unsafe FFI boundaries.",
		group: "Advanced and Tooling",
		section: "Interop and Safety",
		order: 1,
		slug: "interop",
		summary: "Native interop boundaries and explicit unsafe operations.",
	},
	{
		id: "advanced-meta-tooling",
		partId: "advanced",
		path: "/docs/book/advanced/meta-tooling",
		aliases: [
			"/docs/language/advanced/meta-tooling",
			"/learn/language/advanced/meta-tooling",
		],
		title: "Meta and Tooling",
		description:
			"Operator declarations, syntax tools, templates, testing, and run flow.",
		group: "Advanced and Tooling",
		section: "Meta and Tooling",
		order: 2,
		slug: "meta-tooling",
		summary:
			"Syntax-oriented authoring tools and day-to-day development workflow.",
	},
] satisfies readonly BookSectionDefinition[];
