// @generated by musi_diaggen. Do not edit by hand.

use super::SyntaxDiagKind;

struct CatalogEntry {
    kind: SyntaxDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: SyntaxDiagKind::InvalidChar,
        code: 1200,
        message: "invalid character `{ch}`",
        primary: "character `{ch}` not valid here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::UnterminatedStringLiteral,
        code: 1201,
        message: "unterminated string literal",
        primary: "string starts here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::UnterminatedRuneLiteral,
        code: 1202,
        message: "unterminated rune literal",
        primary: "rune starts here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::EmptyRuneLiteral,
        code: 1203,
        message: "empty rune literal",
        primary: "rune literal needs unicode scalar",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::RuneLiteralTooLong,
        code: 1204,
        message: "rune literal contains multiple unicode scalars",
        primary: "rune literal payload too long",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::UnterminatedBlockComment,
        code: 1205,
        message: "unterminated block comment",
        primary: "comment starts here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::UnterminatedTemplateLiteral,
        code: 1206,
        message: "unterminated template literal",
        primary: "template starts here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::MissingDigitsAfterBasePrefix,
        code: 1207,
        message: "base `{base}` literal requires digits",
        primary: "missing digits after base prefix",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::InvalidDigitForBase,
        code: 1208,
        message: "invalid digit `{ch}` in base `{base}` literal",
        primary: "digit `{ch}` not valid for base `{base}`",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::UnexpectedUnderscoreInNumberLiteral,
        code: 1209,
        message: "unexpected `_` in number literal",
        primary: "underscore cannot appear here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::MissingDigitAfterUnderscoreInNumberLiteral,
        code: 1210,
        message: "number literal requires digit after `_`",
        primary: "missing digit after `_`",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::MissingExponentDigits,
        code: 1211,
        message: "exponent requires digits",
        primary: "missing exponent digits",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::MissingEscapeCode,
        code: 1212,
        message: "escape requires code",
        primary: "missing escape code after `\\`",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::UnexpectedEscape,
        code: 1213,
        message: "unsupported escape `\\{ch}`",
        primary: "unsupported escape `\\{ch}`",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::MissingHexDigitsInByteEscape,
        code: 1214,
        message: "`\\x` escape requires hex digits",
        primary: "missing hex digits after `\\x`",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::InvalidHexDigitInByteEscape,
        code: 1215,
        message: "invalid hex digit `{ch}` in `\\x` escape",
        primary: "hex digit `{ch}` not valid here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::MissingHexDigitsInUnicodeEscape,
        code: 1216,
        message: "`\\u` escape requires hex digits",
        primary: "missing hex digits after `\\u`",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::InvalidHexDigitInUnicodeEscape,
        code: 1217,
        message: "invalid hex digit `{ch}` in `\\u` escape",
        primary: "hex digit `{ch}` not valid here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedFourOrSixHexDigitsInUnicodeEscape,
        code: 1218,
        message: "`\\u` escape requires 4 or 6 hex digits",
        primary: "invalid unicode escape length",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::InvalidUnicodeScalar,
        code: 1219,
        message: "invalid unicode scalar `U+{value}`",
        primary: "unicode scalar `U+{value}` not valid",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedToken,
        code: 1300,
        message: "expected {expected}, found {found}",
        primary: "found {found} here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedExpression,
        code: 1301,
        message: "expected expression, found {found}",
        primary: "found {found} here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedPattern,
        code: 1302,
        message: "expected pattern, found {found}",
        primary: "found {found} here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedMember,
        code: 1303,
        message: "expected member, found {found}",
        primary: "found {found} here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedIdentifier,
        code: 1304,
        message: "expected identifier, found {found}",
        primary: "found {found} here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedSpliceTarget,
        code: 1305,
        message: "expected splice target, found {found}",
        primary: "found {found} here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedOperatorMemberName,
        code: 1306,
        message: "expected operator member name, found {found}",
        primary: "found {found} here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedFieldTarget,
        code: 1307,
        message: "expected field name or tuple index, found {found}",
        primary: "found {found} here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedConstraintOperator,
        code: 1308,
        message: "expected constraint operator `<:` or `:`, found {found}",
        primary: "found {found} here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::ExpectedAttrValue,
        code: 1309,
        message: "expected attribute value, found {found}",
        primary: "found {found} here",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::SpliceOutsideQuote,
        code: 1310,
        message: "splice only valid inside quote",
        primary: "splice appears outside quote",
        help: None,
    },
    CatalogEntry {
        kind: SyntaxDiagKind::NonAssociativeChain,
        code: 1311,
        message: "comparison chain requires grouping",
        primary: "chain continues here",
        help: Some("parenthesize comparison"),
    },
];

fn entry(kind: SyntaxDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: SyntaxDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: SyntaxDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: SyntaxDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn help(kind: SyntaxDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<SyntaxDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

pub const fn lex_error_kind(source: super::LexErrorKind) -> SyntaxDiagKind {
    match source {
        super::LexErrorKind::InvalidChar { .. } => SyntaxDiagKind::InvalidChar,
        super::LexErrorKind::UnterminatedStringLiteral => SyntaxDiagKind::UnterminatedStringLiteral,
        super::LexErrorKind::UnterminatedRuneLiteral => SyntaxDiagKind::UnterminatedRuneLiteral,
        super::LexErrorKind::EmptyRuneLiteral => SyntaxDiagKind::EmptyRuneLiteral,
        super::LexErrorKind::RuneLiteralTooLong => SyntaxDiagKind::RuneLiteralTooLong,
        super::LexErrorKind::UnterminatedBlockComment => SyntaxDiagKind::UnterminatedBlockComment,
        super::LexErrorKind::UnterminatedTemplateLiteral => SyntaxDiagKind::UnterminatedTemplateLiteral,
        super::LexErrorKind::MissingDigitsAfterBasePrefix { .. } => SyntaxDiagKind::MissingDigitsAfterBasePrefix,
        super::LexErrorKind::InvalidDigitForBase { .. } => SyntaxDiagKind::InvalidDigitForBase,
        super::LexErrorKind::UnexpectedUnderscoreInNumberLiteral => SyntaxDiagKind::UnexpectedUnderscoreInNumberLiteral,
        super::LexErrorKind::MissingDigitAfterUnderscoreInNumberLiteral => SyntaxDiagKind::MissingDigitAfterUnderscoreInNumberLiteral,
        super::LexErrorKind::MissingExponentDigits => SyntaxDiagKind::MissingExponentDigits,
        super::LexErrorKind::MissingEscapeCode => SyntaxDiagKind::MissingEscapeCode,
        super::LexErrorKind::UnexpectedEscape { .. } => SyntaxDiagKind::UnexpectedEscape,
        super::LexErrorKind::MissingHexDigitsInByteEscape => SyntaxDiagKind::MissingHexDigitsInByteEscape,
        super::LexErrorKind::InvalidHexDigitInByteEscape { .. } => SyntaxDiagKind::InvalidHexDigitInByteEscape,
        super::LexErrorKind::MissingHexDigitsInUnicodeEscape => SyntaxDiagKind::MissingHexDigitsInUnicodeEscape,
        super::LexErrorKind::InvalidHexDigitInUnicodeEscape { .. } => SyntaxDiagKind::InvalidHexDigitInUnicodeEscape,
        super::LexErrorKind::ExpectedFourOrSixHexDigitsInUnicodeEscape => SyntaxDiagKind::ExpectedFourOrSixHexDigitsInUnicodeEscape,
        super::LexErrorKind::InvalidUnicodeScalar { .. } => SyntaxDiagKind::InvalidUnicodeScalar,
    }
}

pub const fn parse_error_kind(source: super::ParseErrorKind) -> SyntaxDiagKind {
    match source {
        super::ParseErrorKind::ExpectedToken { .. } => SyntaxDiagKind::ExpectedToken,
        super::ParseErrorKind::ExpectedExpression { .. } => SyntaxDiagKind::ExpectedExpression,
        super::ParseErrorKind::ExpectedPattern { .. } => SyntaxDiagKind::ExpectedPattern,
        super::ParseErrorKind::ExpectedMember { .. } => SyntaxDiagKind::ExpectedMember,
        super::ParseErrorKind::ExpectedIdentifier { .. } => SyntaxDiagKind::ExpectedIdentifier,
        super::ParseErrorKind::ExpectedSpliceTarget { .. } => SyntaxDiagKind::ExpectedSpliceTarget,
        super::ParseErrorKind::ExpectedOperatorMemberName { .. } => SyntaxDiagKind::ExpectedOperatorMemberName,
        super::ParseErrorKind::ExpectedFieldTarget { .. } => SyntaxDiagKind::ExpectedFieldTarget,
        super::ParseErrorKind::ExpectedConstraintOperator { .. } => SyntaxDiagKind::ExpectedConstraintOperator,
        super::ParseErrorKind::ExpectedAttrValue { .. } => SyntaxDiagKind::ExpectedAttrValue,
        super::ParseErrorKind::SpliceOutsideQuote => SyntaxDiagKind::SpliceOutsideQuote,
        super::ParseErrorKind::NonAssociativeChain => SyntaxDiagKind::NonAssociativeChain,
    }
}
