// @generated by musi_diaggen. Do not edit by hand.

use super::MusicCliDiagKind;

struct CatalogEntry {
    kind: MusicCliDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: MusicCliDiagKind::UnsupportedRunArgs,
        code: 5500,
        message: "unsupported music `run` argument `{argument}`",
        primary: "unsupported music `run` argument `{argument}`",
        help: None,
    },
    CatalogEntry {
        kind: MusicCliDiagKind::CheckCommandFailed,
        code: 5501,
        message: "music `check` command failed",
        primary: "music `check` command failed",
        help: None,
    },
];

fn entry(kind: MusicCliDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: MusicCliDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: MusicCliDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: MusicCliDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn help(kind: MusicCliDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<MusicCliDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

pub const fn music_cli_error_kind(source: &crate::MusicError) -> Option<MusicCliDiagKind> {
    match source {
        crate::MusicError::DirectToolingFailed(_)
        | crate::MusicError::SessionCompilationFailed(_)
        | crate::MusicError::ArtifactTransportFailed(_)
        | crate::MusicError::VmExecutionFailed(_)
        | crate::MusicError::JsonSerializationFailed(_) => None,
        crate::MusicError::UnsupportedRunArgs { .. } => Some(MusicCliDiagKind::UnsupportedRunArgs),
        crate::MusicError::CheckCommandFailed => Some(MusicCliDiagKind::CheckCommandFailed),
    }
}
