(* ========================================================================= *)
(* LEXICAL TOKENS                                                            *)
(* ========================================================================= *)
letter = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z";

digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";

symbol = "_" | " " | "!" | "#" | "$" | "%" | "&" | "(" | ")" | "*" | "+" | "," | "-" | "." | "/" | ":" | ";" | "<" | "=" | ">" | "?" | "@" | "[" | "\\" | "]" | "^" | "`" | "{" | "|" | "}" | "~";

ident = letter, {letter | digit | "_"};

number = ["-"], digit, {digit}, [".", digit, {digit}];

string = '"', {letter | digit | symbol}, '"';

tmpl_string = "$", '"', {letter | digit | symbol | tmpl_expr}, '"';

tmpl_expr = "{", expr, "}";

rune = "'", (letter | digit | symbol), "'";

lit = number | string | rune;

(* ========================================================================= *)
(* PROGRAM STRUCTURE                                                         *)
(* ========================================================================= *)
prog = {stmt_import | stmt_export | stmt};

stmt_import = "import", aux_import_clause, "from", string, ";";

stmt_export = "export", aux_export_clause, ["from", string], ";";

(* ========================================================================= *)
(* STATEMENTS                                                                *)
(* ========================================================================= *)
stmt = [aux_attr], stmt_inner, ";";

stmt_inner = stmt_bind | stmt_extern | expr;

stmt_bind = ("val" | "var"), ident, [":", typ], ":=", expr;

stmt_extern = "extern", [string], "unsafe", "{", {aux_extern_fn_decl}, "}";

(* ========================================================================= *)
(* EXPRESSIONS                                                               *)
(* ========================================================================= *)
expr = expr_una;

expr_una = ["-" | "not" | "~" | "@"], expr_postfix;

expr_postfix = expr_atom, {aux_postfix_op};

expr_atom = expr_lit | expr_tmpl | expr_ident | expr_tuple | expr_block | expr_if | expr_match | expr_for | expr_while | expr_defer | expr_break | expr_cycle | expr_unsafe | expr_assign | expr_record_lit | expr_fn | expr_record | expr_choice | expr_trait;

expr_lit = lit;

expr_tmpl = tmpl_string;

expr_ident = ident;

expr_tuple = "(", expr, ",", {expr, ","}, [expr], ")";

expr_block = aux_block;

expr_if = "if", aux_cond, {",", aux_cond}, aux_block, ["else", aux_block];

expr_match = "match", expr, "{", {aux_match_arm}, "}";

expr_for = "for", aux_for_binding, "in", expr, aux_guard, aux_block;

expr_while = "while", aux_cond, aux_guard, aux_block;

expr_defer = "defer", expr;

expr_break = "break", [expr];

expr_cycle = "cycle";

expr_unsafe = "unsafe", aux_block;

expr_assign = ident, "<-", expr;

expr_record_lit = [ident], "{", aux_record_field_init, {",", aux_record_field_init}, "}";

expr_fn = ["extern", [string]], "fn", [ident], [aux_typ_params], aux_fn_params, ["->", typ], aux_block;

expr_record = "record", [aux_typ_params], [":", typ], "{", aux_record_item, {",", aux_record_item}, "}";

expr_choice = "choice", [aux_typ_params], "{", aux_choice_case, {",", aux_choice_case}, "}";

expr_trait = "trait", [aux_typ_params], [":", typ], "{", aux_trait_item, {",", aux_trait_item}, "}";

(* ========================================================================= *)
(* PATTERNS                                                                  *)
(* ========================================================================= *)
pat = pat_bind | pat_lit | pat_wild | pat_ident | pat_record | pat_ctor | pat_tup;

pat_bind = ("val" | "var"), ident;

pat_lit = lit;

pat_wild = "_";

pat_ident = ident;

pat_record = ident, "{", aux_pat_field, {",", aux_pat_field}, "}";

pat_ctor = ident, ["(", pat, {",", pat}, ")"];

pat_tup = "(", pat, ",", {pat, ","}, [pat], ")";

(* ========================================================================= *)
(* TYPE EXPRESSIONS                                                          *)
(* ========================================================================= *)
typ = typ_sum;

typ_sum = typ_atom, ["?"];

typ_atom = typ_ptr | typ_arr | typ_ident | typ_tup | typ_fn | typ_record;

typ_ptr = "^", typ;

typ_arr = "[", [expr], "]", typ;

typ_ident = ident, [aux_typ_args];

typ_tup = "(", typ, ",", {typ, ","}, [typ], ")";

typ_fn = "fn", "(", [typ, {",", typ}], ")", ["->", typ];

typ_record = "{", aux_typ_record_field, {",", aux_typ_record_field}, "}";

(* ========================================================================= *)
(* AUXILIARIES                                                               *)
(* ========================================================================= *)
aux_import_clause = ("*", "as", ident) | ("{", ident, {",", ident}, "}");

aux_export_clause = ("*", "as", ident) | ("{", ident, {",", ident}, "}");

aux_attr = "@[", ident, ["(", aux_attr_arg, {",", aux_attr_arg}, ")"], "]";

aux_attr_arg = ident | number | string;

aux_extern_fn_decl = "fn", ident, aux_fn_params, ["->", typ];

aux_block = "{", {stmt}, ["return", expr, ";"], "}";

aux_cond = aux_case_binding | expr;

aux_case_binding = "case", pat, ":=", expr;

aux_for_binding = ident | ("case", pat);

aux_guard = ["if", expr];

aux_match_arm = "case", pat, aux_guard, "=>", expr, [","];

aux_postfix_op = (".", ident) | ("[", expr, "]") | ([aux_typ_args], "(", [aux_expr_args], ")") | ("?.", ident) | ("?[", expr, "]") | ("?", [aux_typ_args], "(", [aux_expr_args], ")");

aux_expr_args = expr, {",", expr};

aux_fn_params = "(", [aux_fn_param, {",", aux_fn_param}], ")";

aux_fn_param = ident, [":", typ];

aux_record_field_init = ["."], ident, ":=", expr;

aux_record_item = aux_record_field_decl | aux_record_method_decl;

aux_record_field_decl = ident, ":", typ;

aux_record_method_decl = ident, ":=", expr;

aux_choice_case = "case", ident, ["(", typ, {",", typ}, ")"];

aux_trait_item = ident, ":", typ;

aux_pat_field = ".", ident, [":=", pat];

aux_typ_record_field = ident, ":", typ;

aux_typ_params = "<", ident, {",", ident}, ">";

aux_typ_args = "<", typ, {",", typ}, ">";
