(* ========================================================================= *)
(* LEXICAL TOKENS                                                            *)
(* ========================================================================= *)
letter = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z";

digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";

symbol = " " | "!" | "$" | "%" | "&" | "(" | ")" | "*" | "+" | "," | "-" | "." | "/" | ":" | ";" | "<" | "=" | ">" | "?" | "@" | "[" | "]" | "^" | "`" | "{" | "|" | "}" | "~" | "'" | '"' | '"';

char = letter | digit | symbol;

escape_char = '\\', char;

any_char_except_single_quote = char - "'";

any_char_except_double_quote = char - '"';

aux_text_content = escape_char | any_char_except_double_quote;

aux_text_part = any_char_except_double_quote | escape_char;

aux_ident = letter, {letter | digit | "_"};

aux_escaped_ident = "`", {char}, "`";

ident = aux_ident | aux_escaped_ident;

xdigit = digit | "A" | "B" | "C" | "D" | "E" | "F" | "a" | "b" | "c" | "d" | "e" | "f";

odigit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7";

bdigit = "0" | "1";

aux_dec = digit, {digit}, [".", digit, {digit}];

aux_hex = "0x", xdigit, {xdigit};

aux_oct = "0o", odigit, {odigit};

aux_bin = "0b", bdigit, {bdigit};

aux_lit_number = aux_dec | aux_hex | aux_oct | aux_bin;

aux_lit_text = '"', {aux_text_content}, '"';

aux_lit_rune = "'", char, "'";

aux_lit_template_part = "{", expr, "}";

aux_lit_template_text = "$", '"', {aux_text_part | aux_lit_template_part}, '"';

aux_lit = aux_lit_number | aux_lit_text | aux_lit_template_text | aux_lit_rune | "true" | "false";

aux_modifier_extern = "extern", [aux_lit_text], "unsafe";

(* ========================================================================= *)
(* ATTRIBUTES                                                                *)
(* ========================================================================= *)
aux_attr = "[<", ident, [aux_attr_args], {",", ident, [aux_attr_args]}, ">]";

aux_attr_args = "(", [(ident | aux_lit), [":=", (ident | aux_lit)], {",", (ident | aux_lit), [":=", (ident | aux_lit)]}], ")";

(* ========================================================================= *)
(* TYPES                                                                     *)
(* ========================================================================= *)
ty_params = "<", ident, {",", ident}, ">";

ty_args = ty, {",", ty};

ty_app = ident, "<", ty_args, ">";

ty_optional = "?", ty;

ty_array = "[", [aux_lit_number], "]", ty;

ty_ptr = "^", ty;

ty_fn = ty, "->", ty;

ty_tuple = "(", ty, {",", ty}, ")";

ty_primary = ident | ty_tuple | "(", ty, ")";

ty = ty_fn | ty_ptr | ty_array | ty_optional | ty_app | ty_primary;

(* ========================================================================= *)
(* AUXILIARY HELPERS                                                         *)
(* ========================================================================= *)
aux_ty_annot = ":", ty;

aux_init = ":=", expr;

aux_param = ["var"], ident, [aux_ty_annot], [aux_init];

aux_param_list = aux_param, {",", aux_param};

aux_params = "(", [aux_param_list], ")";

aux_fn_sig = [ident], [ty_params], [aux_params], [aux_ty_annot];

aux_args = expr, {",", expr};

aux_record_field = ["var"], ident, [aux_ty_annot], [aux_init];

aux_record_fields = aux_record_field, {",", aux_record_field};

aux_record_content = aux_record_fields | expr, "with", aux_record_fields;

aux_sum_case = "case", ident, [ty_args], ["(", [ty_args], ")"];

aux_sum_cases = aux_sum_case, {",", aux_sum_case};

aux_pat_field = ident;

aux_pat_fields = aux_pat_field, {",", aux_pat_field};

aux_match_case = "case", pat, "=>", expr;

aux_match_cases = aux_match_case, {",", aux_match_case};

(* ========================================================================= *)
(* PATTERNS                                                                  *)
(* ========================================================================= *)
pat_ident = ident;

pat_lit = aux_lit;

pat_wild = "_";

pat_lit_tuple = "(", pat, {",", pat}, ")";

pat_lit_array = "[", pat, {",", pat}, "]";

pat_lit_record = ident, ".{", aux_pat_fields, "}";

pat_variant = ident, [ty_args], ["(", [pat], ")"];

pat_primary = pat_ident | pat_lit | pat_wild | pat_lit_tuple | pat_lit_array | pat_lit_record | pat_variant | "(", pat, ")";

pat_cons = pat_primary, {"::", pat_primary};

pat = pat_cons;

(* ========================================================================= *)
(* EXPRESSIONS                                                               *)
(* ========================================================================= *)
expr_lit = aux_lit;

expr_ident = ident;

expr_lit_tuple = "(", expr, {",", expr}, ")";

expr_lit_array = "[", expr, {",", expr}, "]";

expr_lit_record = [ident], ".{", [aux_record_content], "}";

expr_block = "{", {stmt}, [expr], "}";

expr_if = "if", expr, expr_block, "else", expr_block;

expr_while = "while", expr, expr_block;

expr_for = "for", ident, "in", expr, expr_block;

expr_match = "match", expr, "{", aux_match_cases, "}";

expr_return = "return", [expr];

expr_defer = "defer", expr;

expr_break = "break", [expr];

expr_cycle = "cycle";

expr_unsafe = "unsafe", expr_block;

expr_import = "import", aux_lit_text;

expr_extern = aux_modifier_extern, "{", {aux_fn_sig, ";"}, "}";

expr_record = [aux_attr], [aux_modifiers], "record", ident, [ty_params], "{", aux_record_fields, "}";

expr_sum = [aux_attr], [aux_modifiers], "sum", ident, [ty_params], "{", aux_sum_cases, "}";

expr_fn = [aux_attr], [aux_modifiers], "fn", aux_fn_sig, expr_block;

expr_bind = [aux_modifiers], ("val" | "var"), ident, [aux_ty_annot], aux_init, expr;

expr_primary = expr_lit | expr_ident | expr_lit_tuple | expr_lit_array | expr_lit_record | expr_block | expr_if | expr_while | expr_for | expr_match | expr_return | expr_defer | expr_break | expr_cycle | expr_unsafe | expr_import | expr_extern | expr_record | expr_sum | expr_fn | expr_bind | "(", expr, ")";

expr_postfix = expr_primary, {postfix_op};

postfix_op = "(", [aux_args], ")" (* call *) | "[", expr, "]" (* index *) | ".", ident (* member access *) | ".^" (* deref *) | "?" (* optional chain *);

expr_unary = ("-" | "not" | "~" | "@"), expr_unary | expr_postfix;

expr_exp = expr_unary, ["**", expr_exp];

expr_mult = expr_exp, {("*" | "/" | "%", "mod", "<<" | ">>"), expr_exp};

expr_add = expr_mult, {("+" | "-"), expr_mult};

expr_cons = expr_add, {"::", expr_add};

expr_range = expr_cons, [(".." | "..<"), expr_cons];

expr_rel = expr_range, [("<" | ">" | "<=" | ">=", "is", "as"), expr_range];

expr_eq = expr_rel, [("=" | "/="), expr_rel];

expr_bitand = expr_eq, {"&", expr_eq};

expr_bitxor = expr_bitand, {"^", expr_bitand};

expr_bitor = expr_bitxor, {"|", expr_bitxor};

expr_conj = expr_bitor, {"and", expr_bitor};

expr_disj = expr_conj, {"or", expr_conj};

expr_coalesce = expr_or, {"??", expr_or};

expr_pipe = expr_coalesce, {"|>", expr_coalesce};

expr_assign = expr_pipe, [(":=" | "<-"), expr_assign];

expr = expr_assign;

aux_modifiers = {("export" | aux_modifier_extern | "unsafe")};

(* ========================================================================= *)
(* STATEMENTS                                                                *)
(* ========================================================================= *)
stmt = expr, ";";

(* ========================================================================= *)
(* PROGRAM                                                                   *)
(* ========================================================================= *)
prog = {stmt};
