export interface BookPartDefinition {
	id: string;
	path: string;
	sourcePath: string;
}

export interface BookPageQuestion {
	labels: Record<"en", string>;
}

export interface BookPageDefinition {
	id: string;
	partId: string;
	path: string;
	aliases: string[];
	sourcePath: string;
	questions: BookPageQuestion[];
}

export const bookParts = [
	{
		id: "start",
		path: "/docs/language/start",
		sourcePath: "www/src/content/book/language/start/index.md",
	},
	{
		id: "core",
		path: "/docs/language/core",
		sourcePath: "www/src/content/book/language/core/index.md",
	},
	{
		id: "data",
		path: "/docs/language/data",
		sourcePath: "www/src/content/book/language/data/index.md",
	},
	{
		id: "organization",
		path: "/docs/language/organization",
		sourcePath: "www/src/content/book/language/organization/index.md",
	},
	{
		id: "types",
		path: "/docs/language/types",
		sourcePath: "www/src/content/book/language/types/index.md",
	},
	{
		id: "abstractions",
		path: "/docs/language/abstractions",
		sourcePath: "www/src/content/book/language/abstractions/index.md",
	},
	{
		id: "effects-runtime",
		path: "/docs/language/effects-runtime",
		sourcePath: "www/src/content/book/language/effects-runtime/index.md",
	},
	{
		id: "advanced",
		path: "/docs/language/advanced",
		sourcePath: "www/src/content/book/language/advanced/index.md",
	},
] satisfies readonly BookPartDefinition[];

export const bookPages = [
	{
		id: "getting-started",
		partId: "start",
		path: "/docs/language/start/getting-started",
		aliases: [],
		sourcePath: "docs/what/language/start/getting-started.md",
		questions: [],
	},
	{
		id: "first-program",
		partId: "start",
		path: "/docs/language/start/first-program",
		aliases: [],
		sourcePath: "docs/what/language/start/first-program.md",
		questions: [],
	},
	{
		id: "values-and-let",
		partId: "start",
		path: "/docs/language/start/values-and-let",
		aliases: [],
		sourcePath: "docs/what/language/start/values-and-let.md",
		questions: [],
	},
	{
		id: "blocks-and-expressions",
		partId: "start",
		path: "/docs/language/start/blocks-and-expressions",
		aliases: [],
		sourcePath: "docs/what/language/start/blocks-and-expressions.md",
		questions: [],
	},
	{
		id: "mutation",
		partId: "start",
		path: "/docs/language/start/mutation",
		aliases: [],
		sourcePath: "docs/what/language/start/mutation.md",
		questions: [],
	},
	{
		id: "literals",
		partId: "core",
		path: "/docs/language/core/literals",
		aliases: [],
		sourcePath: "docs/what/language/core/literals.md",
		questions: [],
	},
	{
		id: "tuples-and-unit",
		partId: "core",
		path: "/docs/language/core/tuples-and-unit",
		aliases: [],
		sourcePath: "docs/what/language/core/tuples-and-unit.md",
		questions: [],
	},
	{
		id: "operators",
		partId: "core",
		path: "/docs/language/core/operators",
		aliases: [],
		sourcePath: "docs/what/language/core/operators.md",
		questions: [],
	},
	{
		id: "ranges",
		partId: "core",
		path: "/docs/language/core/ranges",
		aliases: [],
		sourcePath: "docs/what/language/core/ranges.md",
		questions: [],
	},
	{
		id: "functions",
		partId: "core",
		path: "/docs/language/core/functions",
		aliases: [],
		sourcePath: "docs/what/language/core/functions.md",
		questions: [],
	},
	{
		id: "lambdas",
		partId: "core",
		path: "/docs/language/core/lambdas",
		aliases: [],
		sourcePath: "docs/what/language/core/lambdas.md",
		questions: [],
	},
	{
		id: "calls",
		partId: "core",
		path: "/docs/language/core/calls",
		aliases: [],
		sourcePath: "docs/what/language/core/calls.md",
		questions: [],
	},
	{
		id: "methods",
		partId: "core",
		path: "/docs/language/core/methods",
		aliases: [],
		sourcePath: "docs/what/language/core/methods.md",
		questions: [],
	},
	{
		id: "records",
		partId: "data",
		path: "/docs/language/data/records",
		aliases: [],
		sourcePath: "docs/what/language/data/records.md",
		questions: [],
	},
	{
		id: "indexing-and-fields",
		partId: "data",
		path: "/docs/language/data/indexing-and-fields",
		aliases: [],
		sourcePath: "docs/what/language/data/indexing-and-fields.md",
		questions: [],
	},
	{
		id: "data-definitions",
		partId: "data",
		path: "/docs/language/data/data-definitions",
		aliases: [],
		sourcePath: "docs/what/language/data/data-definitions.md",
		questions: [],
	},
	{
		id: "arrays-and-slices",
		partId: "data",
		path: "/docs/language/data/arrays-and-slices",
		aliases: [],
		sourcePath: "docs/what/language/data/arrays-and-slices.md",
		questions: [],
	},
	{
		id: "patterns",
		partId: "data",
		path: "/docs/language/data/patterns",
		aliases: [],
		sourcePath: "docs/what/language/data/patterns.md",
		questions: [],
	},
	{
		id: "files",
		partId: "organization",
		path: "/docs/language/organization/files",
		aliases: [],
		sourcePath: "docs/what/language/organization/files.md",
		questions: [],
	},
	{
		id: "packages",
		partId: "organization",
		path: "/docs/language/organization/packages",
		aliases: [],
		sourcePath: "docs/what/language/organization/packages.md",
		questions: [],
	},
	{
		id: "imports-and-exports",
		partId: "organization",
		path: "/docs/language/organization/imports-and-exports",
		aliases: [],
		sourcePath: "docs/what/language/organization/imports-and-exports.md",
		questions: [],
	},
	{
		id: "type-annotations",
		partId: "types",
		path: "/docs/language/types/type-annotations",
		aliases: [],
		sourcePath: "docs/what/language/types/type-annotations.md",
		questions: [],
	},
	{
		id: "callable-types",
		partId: "types",
		path: "/docs/language/types/callable-types",
		aliases: [],
		sourcePath: "docs/what/language/types/callable-types.md",
		questions: [],
	},
	{
		id: "type-inference",
		partId: "types",
		path: "/docs/language/types/type-inference",
		aliases: [],
		sourcePath: "docs/what/language/types/type-inference.md",
		questions: [],
	},
	{
		id: "generics",
		partId: "types",
		path: "/docs/language/types/generics",
		aliases: [],
		sourcePath: "docs/what/language/types/generics.md",
		questions: [],
	},
	{
		id: "type-tests-and-casts",
		partId: "types",
		path: "/docs/language/types/type-tests-and-casts",
		aliases: [],
		sourcePath: "docs/what/language/types/type-tests-and-casts.md",
		questions: [],
	},
	{
		id: "forall-types",
		partId: "types",
		path: "/docs/language/types/forall-types",
		aliases: [],
		sourcePath: "docs/what/language/types/forall-types.md",
		questions: [],
	},
	{
		id: "dependent-types",
		partId: "types",
		path: "/docs/language/types/dependent-types",
		aliases: [],
		sourcePath: "docs/what/language/types/dependent-types.md",
		questions: [],
	},
	{
		id: "classes",
		partId: "abstractions",
		path: "/docs/language/abstractions/classes",
		aliases: [],
		sourcePath: "docs/what/language/abstractions/classes.md",
		questions: [],
	},
	{
		id: "instances",
		partId: "abstractions",
		path: "/docs/language/abstractions/instances",
		aliases: [],
		sourcePath: "docs/what/language/abstractions/instances.md",
		questions: [],
	},
	{
		id: "laws",
		partId: "abstractions",
		path: "/docs/language/abstractions/laws",
		aliases: [],
		sourcePath: "docs/what/language/abstractions/laws.md",
		questions: [],
	},
	{
		id: "effects",
		partId: "effects-runtime",
		path: "/docs/language/effects-runtime/effects",
		aliases: [],
		sourcePath: "docs/what/language/effects-runtime/effects.md",
		questions: [],
	},
	{
		id: "using",
		partId: "effects-runtime",
		path: "/docs/language/effects-runtime/using",
		aliases: [],
		sourcePath: "docs/what/language/effects-runtime/using.md",
		questions: [],
	},
	{
		id: "handlers",
		partId: "effects-runtime",
		path: "/docs/language/effects-runtime/handlers",
		aliases: [],
		sourcePath: "docs/what/language/effects-runtime/handlers.md",
		questions: [],
	},
	{
		id: "foundation",
		partId: "effects-runtime",
		path: "/docs/language/effects-runtime/foundation",
		aliases: [],
		sourcePath: "docs/what/language/effects-runtime/foundation.md",
		questions: [],
	},
	{
		id: "runtime",
		partId: "effects-runtime",
		path: "/docs/language/effects-runtime/runtime",
		aliases: [],
		sourcePath: "docs/what/language/effects-runtime/runtime.md",
		questions: [],
	},
	{
		id: "stdlib",
		partId: "effects-runtime",
		path: "/docs/language/effects-runtime/stdlib",
		aliases: [],
		sourcePath: "docs/what/language/effects-runtime/stdlib.md",
		questions: [],
	},
	{
		id: "attributes",
		partId: "advanced",
		path: "/docs/language/advanced/attributes",
		aliases: [],
		sourcePath: "docs/what/language/advanced/attributes.md",
		questions: [],
	},
	{
		id: "foreign",
		partId: "advanced",
		path: "/docs/language/advanced/foreign",
		aliases: [],
		sourcePath: "docs/what/language/advanced/foreign.md",
		questions: [],
	},
	{
		id: "unsafe-and-ffi",
		partId: "advanced",
		path: "/docs/language/advanced/unsafe-and-ffi",
		aliases: [],
		sourcePath: "docs/what/language/advanced/unsafe-and-ffi.md",
		questions: [],
	},
	{
		id: "operator-forms",
		partId: "advanced",
		path: "/docs/language/advanced/operator-forms",
		aliases: [],
		sourcePath: "docs/what/language/advanced/operator-forms.md",
		questions: [],
	},
	{
		id: "quote-and-syntax",
		partId: "advanced",
		path: "/docs/language/advanced/quote-and-syntax",
		aliases: [],
		sourcePath: "docs/what/language/advanced/quote-and-syntax.md",
		questions: [],
	},
	{
		id: "templates-and-splices",
		partId: "advanced",
		path: "/docs/language/advanced/templates-and-splices",
		aliases: [],
		sourcePath: "docs/what/language/advanced/templates-and-splices.md",
		questions: [],
	},
	{
		id: "testing",
		partId: "advanced",
		path: "/docs/language/advanced/testing",
		aliases: [],
		sourcePath: "docs/what/language/advanced/testing.md",
		questions: [],
	},
	{
		id: "running-and-tooling",
		partId: "advanced",
		path: "/docs/language/advanced/running-and-tooling",
		aliases: [],
		sourcePath: "docs/what/language/advanced/running-and-tooling.md",
		questions: [],
	},
] satisfies readonly BookPageDefinition[];
