// @generated by musi_diaggen. Do not edit by hand.

use super::SessionDiagKind;

struct CatalogEntry {
    kind: SessionDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: SessionDiagKind::ModuleNotRegistered,
        code: 5200,
        message: "module `{key}` not registered",
        primary: "module `{key}` not registered",
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::SourceMapUpdateFailed,
        code: 5201,
        message: "source map update failed (`{kind}`)",
        primary: "source map update failed",
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::ModuleParseFailed,
        code: 5202,
        message: "module `{module}` parse failed",
        primary: "module `{module}` parse failed",
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::ModuleResolveFailed,
        code: 5203,
        message: "module `{module}` resolve failed",
        primary: "module `{module}` resolve failed",
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::ModuleSemanticCheckFailed,
        code: 5204,
        message: "module `{module}` semantic check failed",
        primary: "module `{module}` semantic check failed",
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::ModuleLoweringFailed,
        code: 5205,
        message: "module `{module}` lowering failed",
        primary: "module `{module}` lowering failed",
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::ModuleEmissionFailed,
        code: 5206,
        message: "module `{module}` emission failed",
        primary: "module `{module}` emission failed",
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::LawSuiteSynthesisFailed,
        code: 5207,
        message: "module `{module}` law-suite synthesis failed (`{reason}`)",
        primary: "module `{module}` law-suite synthesis failed",
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::ArtifactTransportFailed,
        code: 5208,
        message: "artifact transport failed (`{source}`)",
        primary: "artifact transport failed",
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::SourceRegistryOverflow,
        code: 5209,
        message: "source registry overflow",
        primary: "source registry overflow",
        help: None,
    },
    CatalogEntry {
        kind: SessionDiagKind::SourceTooLarge,
        code: 5210,
        message: "source text `{len}` bytes exceeds limit",
        primary: "source text `{len}` bytes exceeds limit",
        help: None,
    },
];

fn entry(kind: SessionDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: SessionDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: SessionDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: SessionDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn help(kind: SessionDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<SessionDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

pub const fn session_error_kind(source: &crate::SessionError) -> SessionDiagKind {
    match source {
        crate::SessionError::ModuleNotRegistered { .. } => SessionDiagKind::ModuleNotRegistered,
        crate::SessionError::SourceMapUpdateFailed { .. } => SessionDiagKind::SourceMapUpdateFailed,
        crate::SessionError::ModuleParseFailed { .. } => SessionDiagKind::ModuleParseFailed,
        crate::SessionError::ModuleResolveFailed { .. } => SessionDiagKind::ModuleResolveFailed,
        crate::SessionError::ModuleSemanticCheckFailed { .. } => SessionDiagKind::ModuleSemanticCheckFailed,
        crate::SessionError::ModuleLoweringFailed { .. } => SessionDiagKind::ModuleLoweringFailed,
        crate::SessionError::ModuleEmissionFailed { .. } => SessionDiagKind::ModuleEmissionFailed,
        crate::SessionError::LawSuiteSynthesisFailed { .. } => SessionDiagKind::LawSuiteSynthesisFailed,
        crate::SessionError::ArtifactTransportFailed(_) => SessionDiagKind::ArtifactTransportFailed,
    }
}

pub const fn session_source_map_error_kind(source: &crate::SessionSourceMapError) -> SessionDiagKind {
    match source {
        crate::SessionSourceMapError::SourceRegistryOverflow => SessionDiagKind::SourceRegistryOverflow,
        crate::SessionSourceMapError::SourceTooLarge { .. } => SessionDiagKind::SourceTooLarge,
    }
}
