use crate::basic::interner::Interner;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Token {
    Ident(u32),
    LitInt(u32),
    LitReal(u32),
    LitString(u32),
    LitRune(char),
    LitTemplateNoSubst(u32),
    TemplateHead(u32),
    TemplateMiddle(u32),
    TemplateTail(u32),

    // Keywords (alphabetically)
    KwAlias,
    KwAnd,
    KwAs,
    KwBreak,
    KwCase,
    KwCycle,
    KwDefer,
    KwElse,
    KwExtern,
    KwFalse,
    KwFn,
    KwFor,
    KwIf,
    KwImport,
    KwIn,
    KwIs,
    KwMatch,
    KwMod,
    KwNot,
    KwOr,
    KwRecord,
    KwReturn,
    KwSum,
    KwTrue,
    KwTry,
    KwUnsafe,
    KwVal,
    KwVar,
    KwWhile,
    KwWith,

    // Symbols
    LBrace,
    RBrace,
    LBrack,
    RBrack,
    LBrackLt,
    GtRBrack,
    LParen,
    RParen,
    Comma,
    Dot,
    Colon,
    Semicolon,
    Eq,
    SlashEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    LtLt,
    GtGt,
    StarStar,
    Amp,
    Bar,
    BarGt,
    Caret,
    Tilde,
    At,
    DotCaret,
    ColonColon,
    QuestionQuestion,
    DotDot,
    DotDotLt,
    MinusGt,
    LtMinus,
    ColonEq,
    EqGt,
    Question,
    Underscore,
    Dollar,

    // Special
    EOF,
    Invalid(u32),
}

impl Token {
    pub fn display<'a>(&'a self, interner: &'a Interner) -> TokenDisplay<'a> {
        TokenDisplay {
            token: self,
            interner,
        }
    }
}

pub struct TokenDisplay<'a> {
    token: &'a Token,
    interner: &'a Interner,
}

impl<'a> std::fmt::Display for TokenDisplay<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.token {
            Token::Ident(id) => write!(f, "{}", self.interner.lookup(*id).unwrap_or("<ident>")),
            Token::LitInt(id) => write!(f, "{}", self.interner.lookup(*id).unwrap_or("<int>")),
            Token::LitReal(id) => write!(f, "{}", self.interner.lookup(*id).unwrap_or("<real>")),
            Token::LitString(id) => write!(f, "\"{}\"", self.interner.lookup(*id).unwrap_or("")),
            Token::LitRune(c) => write!(f, "'{}'", c),
            Token::LitTemplateNoSubst(id) => {
                write!(f, "$\"{}\"", self.interner.lookup(*id).unwrap_or(""))
            }
            Token::TemplateHead(id) => write!(f, "$\"{}", self.interner.lookup(*id).unwrap_or("")),
            Token::TemplateMiddle(id) => write!(f, "{}", self.interner.lookup(*id).unwrap_or("")),
            Token::TemplateTail(id) => write!(f, "{}\"", self.interner.lookup(*id).unwrap_or("")),
            Token::KwAlias => write!(f, "alias"),
            Token::KwAnd => write!(f, "and"),
            Token::KwAs => write!(f, "as"),
            Token::KwBreak => write!(f, "break"),
            Token::KwCase => write!(f, "case"),
            Token::KwCycle => write!(f, "cycle"),
            Token::KwDefer => write!(f, "defer"),
            Token::KwElse => write!(f, "else"),
            Token::KwExtern => write!(f, "extern"),
            Token::KwFalse => write!(f, "false"),
            Token::KwFn => write!(f, "fn"),
            Token::KwFor => write!(f, "for"),
            Token::KwIf => write!(f, "if"),
            Token::KwImport => write!(f, "import"),
            Token::KwIn => write!(f, "in"),
            Token::KwIs => write!(f, "is"),
            Token::KwMatch => write!(f, "match"),
            Token::KwMod => write!(f, "mod"),
            Token::KwNot => write!(f, "not"),
            Token::KwOr => write!(f, "or"),
            Token::KwRecord => write!(f, "record"),
            Token::KwReturn => write!(f, "return"),
            Token::KwSum => write!(f, "sum"),
            Token::KwTrue => write!(f, "true"),
            Token::KwTry => write!(f, "try"),
            Token::KwUnsafe => write!(f, "unsafe"),
            Token::KwVal => write!(f, "val"),
            Token::KwVar => write!(f, "var"),
            Token::KwWhile => write!(f, "while"),
            Token::KwWith => write!(f, "with"),
            Token::LBrace => write!(f, "{{"),
            Token::RBrace => write!(f, "}}"),
            Token::LBrack => write!(f, "["),
            Token::RBrack => write!(f, "]"),
            Token::LBrackLt => write!(f, "[<"),
            Token::GtRBrack => write!(f, ">]"),
            Token::LParen => write!(f, "("),
            Token::RParen => write!(f, ")"),
            Token::Comma => write!(f, ","),
            Token::Dot => write!(f, "."),
            Token::Colon => write!(f, ":"),
            Token::Semicolon => write!(f, ";"),
            Token::Eq => write!(f, "="),
            Token::SlashEq => write!(f, "/="),
            Token::Lt => write!(f, "<"),
            Token::LtEq => write!(f, "<="),
            Token::Gt => write!(f, ">"),
            Token::GtEq => write!(f, ">="),
            Token::Plus => write!(f, "+"),
            Token::Minus => write!(f, "-"),
            Token::Star => write!(f, "*"),
            Token::Slash => write!(f, "/"),
            Token::Percent => write!(f, "%"),
            Token::LtLt => write!(f, "<<"),
            Token::GtGt => write!(f, ">>"),
            Token::StarStar => write!(f, "**"),
            Token::Amp => write!(f, "&"),
            Token::Bar => write!(f, "|"),
            Token::BarGt => write!(f, "|>"),
            Token::Caret => write!(f, "^"),
            Token::Tilde => write!(f, "~"),
            Token::At => write!(f, "@"),
            Token::DotCaret => write!(f, ".^"),
            Token::ColonColon => write!(f, "::"),
            Token::QuestionQuestion => write!(f, "??"),
            Token::DotDot => write!(f, ".."),
            Token::DotDotLt => write!(f, "..<"),
            Token::MinusGt => write!(f, "->"),
            Token::LtMinus => write!(f, "<-"),
            Token::ColonEq => write!(f, ":="),
            Token::EqGt => write!(f, "=>"),
            Token::Question => write!(f, "?"),
            Token::Underscore => write!(f, "_"),
            Token::Dollar => write!(f, "$"),
            Token::EOF => write!(f, "EOF"),
            Token::Invalid(id) => write!(f, "{}", self.interner.lookup(*id).unwrap_or("<invalid>")),
        }
    }
}

pub const KEYWORDS: &[(&str, Token)] = &[
    ("alias", Token::KwAlias),
    ("and", Token::KwAnd),
    ("as", Token::KwAs),
    ("break", Token::KwBreak),
    ("case", Token::KwCase),
    ("cycle", Token::KwCycle),
    ("defer", Token::KwDefer),
    ("else", Token::KwElse),
    ("extern", Token::KwExtern),
    ("false", Token::KwFalse),
    ("fn", Token::KwFn),
    ("for", Token::KwFor),
    ("if", Token::KwIf),
    ("import", Token::KwImport),
    ("in", Token::KwIn),
    ("is", Token::KwIs),
    ("match", Token::KwMatch),
    ("mod", Token::KwMod),
    ("not", Token::KwNot),
    ("or", Token::KwOr),
    ("record", Token::KwRecord),
    ("return", Token::KwReturn),
    ("sum", Token::KwSum),
    ("true", Token::KwTrue),
    ("try", Token::KwTry),
    ("unsafe", Token::KwUnsafe),
    ("val", Token::KwVal),
    ("var", Token::KwVar),
    ("while", Token::KwWhile),
    ("with", Token::KwWith),
];

pub const SYMBOLS: &[(&str, Token)] = &[
    ("..<", Token::DotDotLt),
    ("<<", Token::LtLt),
    ("<=", Token::LtEq),
    ("<-", Token::LtMinus),
    ("::", Token::ColonColon),
    (":=", Token::ColonEq),
    ("=>", Token::EqGt),
    (">=", Token::GtEq),
    (">>", Token::GtGt),
    (">]", Token::GtRBrack),
    ("??", Token::QuestionQuestion),
    (".^", Token::DotCaret),
    ("..", Token::DotDot),
    ("/=", Token::SlashEq),
    ("->", Token::MinusGt),
    ("**", Token::StarStar),
    ("[<", Token::LBrackLt),
    ("|>", Token::BarGt),
    ("%", Token::Percent),
    ("&", Token::Amp),
    ("(", Token::LParen),
    (")", Token::RParen),
    ("*", Token::Star),
    ("+", Token::Plus),
    (",", Token::Comma),
    ("-", Token::Minus),
    (".", Token::Dot),
    ("/", Token::Slash),
    (":", Token::Colon),
    (";", Token::Semicolon),
    ("<", Token::Lt),
    ("=", Token::Eq),
    (">", Token::Gt),
    ("?", Token::Question),
    ("@", Token::At),
    ("[", Token::LBrack),
    ("]", Token::RBrack),
    ("^", Token::Caret),
    ("_", Token::Underscore),
    ("{", Token::LBrace),
    ("|", Token::Bar),
    ("}", Token::RBrace),
    ("~", Token::Tilde),
    ("$", Token::Dollar),
];
