#[derive(Clone, Copy, Debug)]
pub enum Instr {
    Nop,
    Pop,
    Dup,
    LdC(u32),
    LdCI4(i32),
    LdCStr(u32),
    LdLoc(u32),
    StLoc(u32),
    LdArg(u32),
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    Neg,
    And,
    Or,
    Xor,
    Not,
    Shl,
    Shr,
    CmpEq,
    CmpNe,
    CmpLt,
    CmpGt,
    CmpLe,
    CmpGe,
    Br(i32),
    BrTrue(i32),
    BrFalse(i32),
    Call(u32),
    CallTail(u32),
    Ret,
    NewObj(u32),
    LdFld(u32),
    StFld(u32),
    LdElem,
    StElem,
    LdLen,
    IsInst(u32),
    AsInst(u32),
    RefInc,
    RefDec,
}

pub fn decode(code: &[u8], ip: &mut usize) -> Instr {
    use crate::binary::{read_i32_le, read_u32_le};

    let op = code[*ip];
    *ip += 1;

    match op {
        0x00 => Instr::Nop,
        0x01 => Instr::Pop,
        0x02 => Instr::Dup,
        0x10 => Instr::LdC(read_u32_le(code, ip)),
        0x11 => Instr::LdCI4(read_i32_le(code, ip)),
        0x12 => Instr::LdCStr(read_u32_le(code, ip)),
        0x20 => Instr::LdLoc(read_u32_le(code, ip)),
        0x21 => Instr::StLoc(read_u32_le(code, ip)),
        0x22 => Instr::LdArg(read_u32_le(code, ip)),
        0x30 => Instr::Add,
        0x31 => Instr::Sub,
        0x32 => Instr::Mul,
        0x33 => Instr::Div,
        0x34 => Instr::Mod,
        0x35 => Instr::Neg,
        0x40 => Instr::And,
        0x41 => Instr::Or,
        0x42 => Instr::Xor,
        0x43 => Instr::Not,
        0x44 => Instr::Shl,
        0x45 => Instr::Shr,
        0x50 => Instr::CmpEq,
        0x51 => Instr::CmpNe,
        0x52 => Instr::CmpLt,
        0x53 => Instr::CmpGt,
        0x54 => Instr::CmpLe,
        0x55 => Instr::CmpGe,
        0x60 => Instr::Br(read_i32_le(code, ip)),
        0x61 => Instr::BrTrue(read_i32_le(code, ip)),
        0x62 => Instr::BrFalse(read_i32_le(code, ip)),
        0x70 => Instr::Call(read_u32_le(code, ip)),
        0x71 => Instr::CallTail(read_u32_le(code, ip)),
        0x72 => Instr::Ret,
        0x80 => Instr::NewObj(read_u32_le(code, ip)),
        0x81 => Instr::LdFld(read_u32_le(code, ip)),
        0x82 => Instr::StFld(read_u32_le(code, ip)),
        0x83 => Instr::LdElem,
        0x84 => Instr::StElem,
        0x86 => Instr::LdLen,
        0x90 => Instr::IsInst(read_u32_le(code, ip)),
        0x91 => Instr::AsInst(read_u32_le(code, ip)),
        0xA0 => Instr::RefInc,
        0xA1 => Instr::RefDec,
        _ => panic!("unknown opcode: {op:#x}"),
    }
}
