mod class;
mod constant;
mod data;
mod effect;
mod export;
mod foreign;
mod global;
mod meta;
mod procedure;
mod type_desc;

pub use class::ClassDescriptor;
pub use constant::{ConstantDescriptor, ConstantValue};
pub use data::{DataDescriptor, DataVariantDescriptor};
pub use effect::{EffectDescriptor, EffectOpDescriptor};
pub use export::{ExportDescriptor, ExportTarget};
pub use foreign::ForeignDescriptor;
pub use global::GlobalDescriptor;
pub use meta::MetaDescriptor;
pub use procedure::ProcedureDescriptor;
pub use type_desc::TypeDescriptor;
