// @generated by musi_diaggen. Do not edit by hand.
#![allow(dead_code)]

use super::EmitDiagKind;
use music_base::diag::DiagContext;

struct CatalogEntry {
    kind: EmitDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    secondary: Option<&'static str>,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: EmitDiagKind::MissingExportTarget,
        code: 3500,
        message: "missing target for export `{export}`",
        primary: "missing target for export `{export}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownTypeValue,
        code: 3501,
        message: "unknown emitted type value `{type}`",
        primary: "unknown emitted type value `{type}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownTypeNameForOp,
        code: 3502,
        message: "unknown type name `{type}` for operation `{operation}`",
        primary: "unknown type name `{type}` for operation `{operation}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnsupportedBinaryOperator,
        code: 3503,
        message: "unsupported binary operator `{operator}`",
        primary: "unsupported binary operator `{operator}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::CaseVariantDispatchRequiresSingleDataType,
        code: 3504,
        message: "case variant dispatch needs single data type",
        primary: "case variant dispatch needs single data type",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownDataType,
        code: 3505,
        message: "unknown emitted data type `{type}`",
        primary: "unknown emitted data type `{type}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::SpreadCallArgsNotEmitted,
        code: 3506,
        message: "spread call arguments have no emitted form",
        primary: "spread call arguments have no emitted form",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownClosureTarget,
        code: 3507,
        message: "unknown emitted closure target `{target}`",
        primary: "unknown emitted closure target `{target}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownEffect,
        code: 3508,
        message: "unknown emitted effect `{effect}`",
        primary: "unknown emitted effect `{effect}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownHandlerType,
        code: 3509,
        message: "unknown emitted answer type `{type}`",
        primary: "unknown emitted answer type `{type}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownRecordType,
        code: 3510,
        message: "unknown emitted record type `{type}`",
        primary: "unknown emitted record type `{type}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::RecordLiteralMissingFieldValue,
        code: 3511,
        message: "missing value for record literal field `{field}`",
        primary: "missing value for record literal field `{field}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::RecordUpdateMissingFieldValue,
        code: 3512,
        message: "missing value for record update field `{field}`",
        primary: "missing value for record update field `{field}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownSequenceType,
        code: 3513,
        message: "unknown emitted sequence type `{type}`",
        primary: "unknown emitted sequence type `{type}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::InvalidSyntaxLiteral,
        code: 3514,
        message: "invalid syntax literal `{literal}`",
        primary: "invalid syntax literal `{literal}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::InvalidIntegerLiteral,
        code: 3515,
        message: "invalid integer literal `{literal}`",
        primary: "invalid integer literal `{literal}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::InvalidFloatLiteral,
        code: 3516,
        message: "invalid float literal `{literal}`",
        primary: "invalid float literal `{literal}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnsupportedNameRef,
        code: 3517,
        message: "unsupported name reference `{name}`",
        primary: "unsupported name reference `{name}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnsupportedAssignTarget,
        code: 3518,
        message: "unsupported emitted assignment target `{target}`",
        primary: "unsupported emitted assignment target `{target}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::EmitInvariantViolated,
        code: 3519,
        message: "emit invariant violated",
        primary: "{detail}",
        secondary: None,
        help: None,
    },
];

fn entry(kind: EmitDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: EmitDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: EmitDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: EmitDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn render_message(kind: EmitDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).message)
}

pub fn render_primary(kind: EmitDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).primary)
}

pub fn secondary(kind: EmitDiagKind) -> Option<&'static str> {
    entry(kind).secondary
}

pub fn render_secondary(kind: EmitDiagKind, context: &DiagContext) -> Option<String> {
    entry(kind)
        .secondary
        .map(|secondary| context.render(secondary))
}

pub fn help(kind: EmitDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<EmitDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}
