// @generated by musi_diaggen. Do not edit by hand.

use super::EmitDiagKind;

struct CatalogEntry {
    kind: EmitDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: EmitDiagKind::MissingExportTarget,
        code: 3500,
        message: "missing export target",
        primary: "missing export target",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownTypeValue,
        code: 3501,
        message: "unknown emitted type value `{type}`",
        primary: "unknown emitted type value `{type}`",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownTypeNameForOp,
        code: 3502,
        message: "unknown type name `{type}` for operation `{operation}`",
        primary: "unknown type name `{type}` for operation `{operation}`",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnsupportedBinaryOperator,
        code: 3503,
        message: "unsupported binary operator `{operator}`",
        primary: "unsupported binary operator `{operator}`",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::CaseVariantDispatchRequiresSingleDataType,
        code: 3504,
        message: "case variant dispatch requires single data type",
        primary: "case variant dispatch requires single data type",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownDataType,
        code: 3505,
        message: "unknown emitted data type `{type}`",
        primary: "unknown emitted data type `{type}`",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::SpreadCallArgsNotEmitted,
        code: 3506,
        message: "spread call arguments have no emitted form",
        primary: "spread call arguments have no emitted form",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownClosureTarget,
        code: 3507,
        message: "unknown emitted closure target `{target}`",
        primary: "unknown emitted closure target `{target}`",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownEffect,
        code: 3508,
        message: "unknown emitted effect `{effect}`",
        primary: "unknown emitted effect `{effect}`",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownHandlerType,
        code: 3509,
        message: "unknown emitted handler type `{type}`",
        primary: "unknown emitted handler type `{type}`",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownRecordType,
        code: 3510,
        message: "unknown emitted record type `{type}`",
        primary: "unknown emitted record type `{type}`",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::RecordLiteralMissingFieldValue,
        code: 3511,
        message: "missing record literal field value",
        primary: "missing record literal field value",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::RecordUpdateMissingFieldValue,
        code: 3512,
        message: "missing record update field value",
        primary: "missing record update field value",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnknownSequenceType,
        code: 3513,
        message: "unknown emitted sequence type `{type}`",
        primary: "unknown emitted sequence type `{type}`",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::InvalidSyntaxLiteral,
        code: 3514,
        message: "invalid syntax literal",
        primary: "invalid syntax literal",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::InvalidIntegerLiteral,
        code: 3515,
        message: "invalid integer literal",
        primary: "invalid integer literal",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::InvalidFloatLiteral,
        code: 3516,
        message: "invalid float literal",
        primary: "invalid float literal",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnsupportedNameRef,
        code: 3517,
        message: "unsupported name reference `{name}`",
        primary: "unsupported name reference `{name}`",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::UnsupportedAssignTarget,
        code: 3518,
        message: "unsupported assignment target `{target}`",
        primary: "unsupported assignment target `{target}`",
        help: None,
    },
    CatalogEntry {
        kind: EmitDiagKind::EmitInvariantViolated,
        code: 3519,
        message: "emit invariant violated",
        primary: "emit invariant violated",
        help: None,
    },
];

fn entry(kind: EmitDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: EmitDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: EmitDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: EmitDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn help(kind: EmitDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<EmitDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}
