use crate::{Interner, Symbol};

#[derive(Debug, Clone, Copy)]
pub struct KnownSymbols {
    pub type_: Symbol,
    pub array: Symbol,
    pub any: Symbol,
    pub unknown: Symbol,
    pub syntax: Symbol,
    pub empty: Symbol,
    pub unit: Symbol,
    pub bool_: Symbol,
    pub nat: Symbol,
    pub int_: Symbol,
    pub int8: Symbol,
    pub int16: Symbol,
    pub int32: Symbol,
    pub int64: Symbol,
    pub nat8: Symbol,
    pub nat16: Symbol,
    pub nat32: Symbol,
    pub nat64: Symbol,
    pub float_: Symbol,
    pub float32: Symbol,
    pub float64: Symbol,
    pub string_: Symbol,
    pub rune: Symbol,
    pub range: Symbol,
    pub closed_range: Symbol,
    pub partial_range_from: Symbol,
    pub partial_range_up_to: Symbol,
    pub partial_range_thru: Symbol,
    pub handler: Symbol,
    pub rangeable: Symbol,
    pub range_bounds: Symbol,
    pub compare: Symbol,
    pub next: Symbol,
    pub prev: Symbol,
    pub default_lower_bound: Symbol,
    pub default_upper_bound: Symbol,
    pub cstring: Symbol,
    pub cptr: Symbol,
    pub abort: Symbol,
    pub abort_op: Symbol,
    pub known: Symbol,
    pub intrinsic: Symbol,
    pub name_key: Symbol,
    pub symbol_key: Symbol,
    pub message_key: Symbol,
    pub replace_key: Symbol,
    pub version_key: Symbol,
    pub lang_option: Symbol,
    pub some: Symbol,
    pub none: Symbol,
}

impl KnownSymbols {
    #[must_use]
    pub fn new(interner: &mut Interner) -> Self {
        Self {
            type_: interner.intern("Type"),
            array: interner.intern("Array"),
            any: interner.intern("Any"),
            unknown: interner.intern("Unknown"),
            syntax: interner.intern("Syntax"),
            empty: interner.intern("Empty"),
            unit: interner.intern("Unit"),
            bool_: interner.intern("Bool"),
            nat: interner.intern("Nat"),
            int_: interner.intern("Int"),
            int8: interner.intern("Int8"),
            int16: interner.intern("Int16"),
            int32: interner.intern("Int32"),
            int64: interner.intern("Int64"),
            nat8: interner.intern("Nat8"),
            nat16: interner.intern("Nat16"),
            nat32: interner.intern("Nat32"),
            nat64: interner.intern("Nat64"),
            float_: interner.intern("Float"),
            float32: interner.intern("Float32"),
            float64: interner.intern("Float64"),
            string_: interner.intern("String"),
            rune: interner.intern("Rune"),
            range: interner.intern("Range"),
            closed_range: interner.intern("ClosedRange"),
            partial_range_from: interner.intern("PartialRangeFrom"),
            partial_range_up_to: interner.intern("PartialRangeUpTo"),
            partial_range_thru: interner.intern("PartialRangeThru"),
            handler: interner.intern("Handler"),
            rangeable: interner.intern("Rangeable"),
            range_bounds: interner.intern("RangeBounds"),
            compare: interner.intern("compare"),
            next: interner.intern("next"),
            prev: interner.intern("prev"),
            default_lower_bound: interner.intern("defaultLowerBound"),
            default_upper_bound: interner.intern("defaultUpperBound"),
            cstring: interner.intern("CString"),
            cptr: interner.intern("CPtr"),
            abort: interner.intern("Abort"),
            abort_op: interner.intern("abort"),
            known: interner.intern("known"),
            intrinsic: interner.intern("intrinsic"),
            name_key: interner.intern("name"),
            symbol_key: interner.intern("symbol"),
            message_key: interner.intern("message"),
            replace_key: interner.intern("replace"),
            version_key: interner.intern("version"),
            lang_option: interner.intern("Option"),
            some: interner.intern("Some"),
            none: interner.intern("None"),
        }
    }

    #[must_use]
    pub const fn compiler_prelude(self) -> [Symbol; 33] {
        [
            self.type_,
            self.array,
            self.any,
            self.unknown,
            self.syntax,
            self.empty,
            self.unit,
            self.bool_,
            self.nat,
            self.int_,
            self.int8,
            self.int16,
            self.int32,
            self.int64,
            self.nat8,
            self.nat16,
            self.nat32,
            self.nat64,
            self.float_,
            self.float32,
            self.float64,
            self.string_,
            self.rune,
            self.range,
            self.closed_range,
            self.partial_range_from,
            self.partial_range_up_to,
            self.partial_range_thru,
            self.rangeable,
            self.range_bounds,
            self.cstring,
            self.cptr,
            self.abort,
        ]
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::panic)]
mod tests;
