pub const STD_PACKAGE_NAME: &str = "@std";
pub const STD_MANIFEST_PATH: &str = "builtin:/@std/musi.json";
pub const STD_ROOT_DIR: &str = "builtin:/@std";
pub const STD_MANIFEST: &str = include_str!("../../../packages/std/musi.json");
pub const STD_FILES: &[(&str, &str)] = &[
    (
        "assert/index.ms",
        include_str!("../../../packages/std/assert/index.ms"),
    ),
    (
        "bytes/core.ms",
        include_str!("../../../packages/std/bytes/core.ms"),
    ),
    (
        "bytes/index.ms",
        include_str!("../../../packages/std/bytes/index.ms"),
    ),
    (
        "cli/index.ms",
        include_str!("../../../packages/std/cli/index.ms"),
    ),
    (
        "cli/prompt.ms",
        include_str!("../../../packages/std/cli/prompt.ms"),
    ),
    (
        "cmp/core.ms",
        include_str!("../../../packages/std/cmp/core.ms"),
    ),
    (
        "cmp/index.ms",
        include_str!("../../../packages/std/cmp/index.ms"),
    ),
    (
        "collections/array/core.ms",
        include_str!("../../../packages/std/collections/array/core.ms"),
    ),
    (
        "collections/array/index.ms",
        include_str!("../../../packages/std/collections/array/index.ms"),
    ),
    (
        "collections/index.ms",
        include_str!("../../../packages/std/collections/index.ms"),
    ),
    (
        "collections/iter/core.ms",
        include_str!("../../../packages/std/collections/iter/core.ms"),
    ),
    (
        "collections/iter/index.ms",
        include_str!("../../../packages/std/collections/iter/index.ms"),
    ),
    (
        "collections/list/core.ms",
        include_str!("../../../packages/std/collections/list/core.ms"),
    ),
    (
        "collections/list/index.ms",
        include_str!("../../../packages/std/collections/list/index.ms"),
    ),
    (
        "collections/slice/core.ms",
        include_str!("../../../packages/std/collections/slice/core.ms"),
    ),
    (
        "collections/slice/index.ms",
        include_str!("../../../packages/std/collections/slice/index.ms"),
    ),
    (
        "crypto/index.ms",
        include_str!("../../../packages/std/crypto/index.ms"),
    ),
    (
        "datetime/core.ms",
        include_str!("../../../packages/std/datetime/core.ms"),
    ),
    (
        "datetime/index.ms",
        include_str!("../../../packages/std/datetime/index.ms"),
    ),
    (
        "encoding/base64/index.ms",
        include_str!("../../../packages/std/encoding/base64/index.ms"),
    ),
    (
        "encoding/hex/index.ms",
        include_str!("../../../packages/std/encoding/hex/index.ms"),
    ),
    (
        "encoding/index.ms",
        include_str!("../../../packages/std/encoding/index.ms"),
    ),
    (
        "encoding/utf8/index.ms",
        include_str!("../../../packages/std/encoding/utf8/index.ms"),
    ),
    (
        "env/index.ms",
        include_str!("../../../packages/std/env/index.ms"),
    ),
    (
        "errors/index.ms",
        include_str!("../../../packages/std/errors/index.ms"),
    ),
    (
        "ffi/index.ms",
        include_str!("../../../packages/std/ffi/index.ms"),
    ),
    (
        "fmt/index.ms",
        include_str!("../../../packages/std/fmt/index.ms"),
    ),
    (
        "fs/index.ms",
        include_str!("../../../packages/std/fs/index.ms"),
    ),
    ("index.ms", include_str!("../../../packages/std/index.ms")),
    (
        "io/index.ms",
        include_str!("../../../packages/std/io/index.ms"),
    ),
    (
        "json/index.ms",
        include_str!("../../../packages/std/json/index.ms"),
    ),
    (
        "log/index.ms",
        include_str!("../../../packages/std/log/index.ms"),
    ),
    (
        "math/_float.ms",
        include_str!("../../../packages/std/math/_float.ms"),
    ),
    (
        "math/_int.ms",
        include_str!("../../../packages/std/math/_int.ms"),
    ),
    (
        "math/index.ms",
        include_str!("../../../packages/std/math/index.ms"),
    ),
    (
        "option/core.ms",
        include_str!("../../../packages/std/option/core.ms"),
    ),
    (
        "option/index.ms",
        include_str!("../../../packages/std/option/index.ms"),
    ),
    (
        "os/core.ms",
        include_str!("../../../packages/std/os/core.ms"),
    ),
    (
        "os/index.ms",
        include_str!("../../../packages/std/os/index.ms"),
    ),
    (
        "path/core.ms",
        include_str!("../../../packages/std/path/core.ms"),
    ),
    (
        "path/index.ms",
        include_str!("../../../packages/std/path/index.ms"),
    ),
    (
        "prelude/index.ms",
        include_str!("../../../packages/std/prelude/index.ms"),
    ),
    (
        "process/index.ms",
        include_str!("../../../packages/std/process/index.ms"),
    ),
    (
        "random/index.ms",
        include_str!("../../../packages/std/random/index.ms"),
    ),
    (
        "result/core.ms",
        include_str!("../../../packages/std/result/core.ms"),
    ),
    (
        "result/index.ms",
        include_str!("../../../packages/std/result/index.ms"),
    ),
    (
        "semver/index.ms",
        include_str!("../../../packages/std/semver/index.ms"),
    ),
    (
        "sys/index.ms",
        include_str!("../../../packages/std/sys/index.ms"),
    ),
    (
        "testing/index.ms",
        include_str!("../../../packages/std/testing/index.ms"),
    ),
    (
        "text/index.ms",
        include_str!("../../../packages/std/text/index.ms"),
    ),
    (
        "text/string.ms",
        include_str!("../../../packages/std/text/string.ms"),
    ),
    (
        "uuid/index.ms",
        include_str!("../../../packages/std/uuid/index.ms"),
    ),
];
