pub const STD_PACKAGE_NAME: &str = "@std";
pub const STD_MANIFEST_PATH: &str = "builtin:/@std/musi.json";
pub const STD_ROOT_DIR: &str = "builtin:/@std";
pub const STD_MANIFEST: &str = include_str!("../../../packages/std/musi.json");
pub const STD_FILES: &[(&str, &str)] = &[
    (
        "array/_core.ms",
        include_str!("../../../packages/std/array/_core.ms"),
    ),
    (
        "array/index.ms",
        include_str!("../../../packages/std/array/index.ms"),
    ),
    (
        "assert/index.ms",
        include_str!("../../../packages/std/assert/index.ms"),
    ),
    (
        "bytes/_core.ms",
        include_str!("../../../packages/std/bytes/_core.ms"),
    ),
    (
        "bytes/index.ms",
        include_str!("../../../packages/std/bytes/index.ms"),
    ),
    (
        "cmp/_core.ms",
        include_str!("../../../packages/std/cmp/_core.ms"),
    ),
    (
        "cmp/index.ms",
        include_str!("../../../packages/std/cmp/index.ms"),
    ),
    (
        "encoding/base64/index.ms",
        include_str!("../../../packages/std/encoding/base64/index.ms"),
    ),
    (
        "encoding/hex/index.ms",
        include_str!("../../../packages/std/encoding/hex/index.ms"),
    ),
    (
        "encoding/index.ms",
        include_str!("../../../packages/std/encoding/index.ms"),
    ),
    (
        "encoding/utf8/index.ms",
        include_str!("../../../packages/std/encoding/utf8/index.ms"),
    ),
    (
        "env/index.ms",
        include_str!("../../../packages/std/env/index.ms"),
    ),
    (
        "ffi/index.ms",
        include_str!("../../../packages/std/ffi/index.ms"),
    ),
    (
        "fs/index.ms",
        include_str!("../../../packages/std/fs/index.ms"),
    ),
    ("index.ms", include_str!("../../../packages/std/index.ms")),
    (
        "io/index.ms",
        include_str!("../../../packages/std/io/index.ms"),
    ),
    (
        "io/prompt.ms",
        include_str!("../../../packages/std/io/prompt.ms"),
    ),
    (
        "iter/_core.ms",
        include_str!("../../../packages/std/iter/_core.ms"),
    ),
    (
        "iter/index.ms",
        include_str!("../../../packages/std/iter/index.ms"),
    ),
    (
        "json/index.ms",
        include_str!("../../../packages/std/json/index.ms"),
    ),
    (
        "list/_core.ms",
        include_str!("../../../packages/std/list/_core.ms"),
    ),
    (
        "list/index.ms",
        include_str!("../../../packages/std/list/index.ms"),
    ),
    (
        "log/index.ms",
        include_str!("../../../packages/std/log/index.ms"),
    ),
    (
        "math/_float.ms",
        include_str!("../../../packages/std/math/_float.ms"),
    ),
    (
        "math/_int.ms",
        include_str!("../../../packages/std/math/_int.ms"),
    ),
    (
        "math/index.ms",
        include_str!("../../../packages/std/math/index.ms"),
    ),
    (
        "option/_core.ms",
        include_str!("../../../packages/std/option/_core.ms"),
    ),
    (
        "option/index.ms",
        include_str!("../../../packages/std/option/index.ms"),
    ),
    (
        "os/_core.ms",
        include_str!("../../../packages/std/os/_core.ms"),
    ),
    (
        "os/index.ms",
        include_str!("../../../packages/std/os/index.ms"),
    ),
    (
        "path/_core.ms",
        include_str!("../../../packages/std/path/_core.ms"),
    ),
    (
        "path/index.ms",
        include_str!("../../../packages/std/path/index.ms"),
    ),
    (
        "prelude/index.ms",
        include_str!("../../../packages/std/prelude/index.ms"),
    ),
    (
        "process/index.ms",
        include_str!("../../../packages/std/process/index.ms"),
    ),
    (
        "random/index.ms",
        include_str!("../../../packages/std/random/index.ms"),
    ),
    (
        "result/_core.ms",
        include_str!("../../../packages/std/result/_core.ms"),
    ),
    (
        "result/index.ms",
        include_str!("../../../packages/std/result/index.ms"),
    ),
    (
        "slice/_core.ms",
        include_str!("../../../packages/std/slice/_core.ms"),
    ),
    (
        "slice/index.ms",
        include_str!("../../../packages/std/slice/index.ms"),
    ),
    (
        "sys/index.ms",
        include_str!("../../../packages/std/sys/index.ms"),
    ),
    (
        "testing/index.ms",
        include_str!("../../../packages/std/testing/index.ms"),
    ),
    (
        "text/_string.ms",
        include_str!("../../../packages/std/text/_string.ms"),
    ),
    (
        "text/index.ms",
        include_str!("../../../packages/std/text/index.ms"),
    ),
    (
        "time/_core.ms",
        include_str!("../../../packages/std/time/_core.ms"),
    ),
    (
        "time/index.ms",
        include_str!("../../../packages/std/time/index.ms"),
    ),
];
