// @generated by musi_diaggen. Do not edit by hand.
#![allow(dead_code)]

use super::ProjectDiagKind;
use music_base::diag::DiagContext;

struct CatalogEntry {
    kind: ProjectDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    secondary: Option<&'static str>,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: ProjectDiagKind::MissingManifest,
        code: 5000,
        message: "missing manifest `{path}`",
        primary: "missing manifest `{path}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::MissingManifestAncestor,
        code: 5001,
        message: "missing manifest ancestor from `{path}`",
        primary: "missing manifest ancestor from `{path}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::MissingPackageRoot,
        code: 5002,
        message: "missing package root `{path}`",
        primary: "missing package root `{path}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::MissingModule,
        code: 5003,
        message: "missing module path `{path}`",
        primary: "missing module path `{path}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::InvalidManifestJson,
        code: 5004,
        message: "invalid manifest `{path}` JSON (`{source}`)",
        primary: "invalid manifest `{path}` JSON",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::ProjectIoFailed,
        code: 5005,
        message: "project path `{path}` I/O failed (`{source}`)",
        primary: "project path `{path}` I/O failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestValidationFailed,
        code: 5006,
        message: "manifest validation failed (`{message}`)",
        primary: "manifest validation failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::DuplicateWorkspaceMember,
        code: 5007,
        message: "duplicate workspace member `{member}`",
        primary: "duplicate workspace member `{member}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::DuplicatePackageName,
        code: 5008,
        message: "duplicate package `{name}` in project graph",
        primary: "duplicate package `{name}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::MissingPackageVersion,
        code: 5009,
        message: "missing version for package `{name}`",
        primary: "missing version for package `{name}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::NoRootPackage,
        code: 5010,
        message: "missing root package entry `root`",
        primary: "missing root package entry `root`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::MissingPackageEntryModule,
        code: 5011,
        message: "missing entry module for package `{package}`",
        primary: "missing entry module for package `{package}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::UnknownTask,
        code: 5012,
        message: "unknown task `{name}`",
        primary: "unknown task `{name}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::TaskDependencyCycle,
        code: 5013,
        message: "task dependency cycle reaches `{name}`",
        primary: "task dependency cycle reaches `{name}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::PackageDependencyCycle,
        code: 5014,
        message: "package dependency cycle reaches `{name}`",
        primary: "package dependency cycle reaches `{name}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::UnresolvedImport,
        code: 5015,
        message: "unresolved import specifier `{spec}`",
        primary: "unresolved import specifier `{spec}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::MissingRegistryRoot,
        code: 5016,
        message: "missing registry root for `{name}`",
        primary: "missing registry root for `{name}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::MissingGlobalCacheRoot,
        code: 5017,
        message: "missing global cache directory",
        primary: "missing global cache directory",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::RegistryVersionNotFound,
        code: 5018,
        message: "missing registry version for `{name}` matching `{requirement}`",
        primary: "missing registry version for `{name}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::InvalidVersionRequirement,
        code: 5019,
        message: "invalid semver requirement `{requirement}` for `{name}`",
        primary: "invalid semver requirement `{requirement}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::MissingFrozenLockfile,
        code: 5020,
        message: "missing frozen lockfile `{path}`",
        primary: "missing frozen lockfile `{path}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::FrozenLockfileOutOfDate,
        code: 5021,
        message: "frozen lockfile `{path}` out of date",
        primary: "frozen lockfile `{path}` out of date",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::UnknownPackage,
        code: 5022,
        message: "unknown package `{name}`",
        primary: "unknown package `{name}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::PackageGraphEntryMissing,
        code: 5023,
        message: "missing package graph entry `{name}`",
        primary: "missing package graph entry `{name}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::InvalidGitDependency,
        code: 5024,
        message: "invalid git dependency `{requirement}` for `{name}`",
        primary: "invalid git dependency `{requirement}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::GitCommandFailed,
        code: 5025,
        message: "git command `{command}` failed at `{path}`",
        primary: "git command `{command}` failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::GitReferenceNotFound,
        code: 5026,
        message: "missing git reference `{reference}` for `{name}`",
        primary: "missing git reference `{reference}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::SessionCompilationFailed,
        code: 5027,
        message: "project session compilation failed (`{source}`)",
        primary: "project session compilation failed",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestPackageNameMissing,
        code: 5028,
        message: "missing manifest package name for `{path}`",
        primary: "missing `name` field",
        secondary: None,
        help: Some("add `name` to this package manifest"),
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestPackageNameEmpty,
        code: 5029,
        message: "empty package name for `{path}`",
        primary: "`name` must not be empty",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestPackageVersionMissing,
        code: 5030,
        message: "missing package version for `{name}`",
        primary: "missing `version` field",
        secondary: None,
        help: Some("add `version` to this package manifest"),
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestLibUnknown,
        code: 5031,
        message: "unknown lib `{lib}`",
        primary: "unsupported lib `{lib}`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestPublishUnsupported,
        code: 5032,
        message: "unsupported publish value `{value}`",
        primary: "`publish` boolean must be false",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestModulesDirUnsupported,
        code: 5033,
        message: "unsupported musiModulesDir value `{value}`",
        primary: "`musiModulesDir` boolean must be false",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestExportKeyInvalid,
        code: 5034,
        message: "invalid export key `{key}`",
        primary: "export key `{key}` must be `.` or start with `./`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestExportTargetInvalid,
        code: 5035,
        message: "invalid export target `{target}`",
        primary: "export target `{target}` must start with `./`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestFmtLineWidthInvalid,
        code: 5036,
        message: "invalid fmt.lineWidth `{value}`",
        primary: "`fmt.lineWidth` must be at least `1`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestFmtIndentWidthInvalid,
        code: 5037,
        message: "invalid fmt.indentWidth `{value}`",
        primary: "`fmt.indentWidth` must be at least `1`",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestFmtIncludeDuplicate,
        code: 5038,
        message: "duplicate fmt.include pattern `{pattern}`",
        primary: "`fmt.include` pattern `{pattern}` repeats",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestFmtExcludeDuplicate,
        code: 5039,
        message: "duplicate fmt.exclude pattern `{pattern}`",
        primary: "`fmt.exclude` pattern `{pattern}` repeats",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestTaskDependencyUnknown,
        code: 5040,
        message: "unknown task dependency `{dependency}` in task `{task}`",
        primary: "task dependency `{dependency}` not found",
        secondary: None,
        help: None,
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestEntryTargetMissing,
        code: 5041,
        message: "missing entry target `{target}` for package `{package}`",
        primary: "entry target `{target}` does not resolve",
        secondary: None,
        help: Some("update `entry` to existing module path"),
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestEntryDefaultMissing,
        code: 5042,
        message: "missing default entry module for package `{package}`",
        primary: "missing `entry` field and root `index.ms`",
        secondary: None,
        help: Some("add `entry`, or create `index.ms` at package root"),
    },
    CatalogEntry {
        kind: ProjectDiagKind::ManifestExportTargetMissing,
        code: 5043,
        message: "missing export target `{target}` for export `{export}` in package `{package}`",
        primary: "export target `{target}` does not resolve",
        secondary: None,
        help: Some("update export target or add target module"),
    },
    CatalogEntry {
        kind: ProjectDiagKind::SourceImportUnresolved,
        code: 5044,
        message: "unresolved import `{spec}`",
        primary: "import `{spec}` does not resolve",
        secondary: None,
        help: Some("declare import target or fix import spec"),
    },
];

fn entry(kind: ProjectDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: ProjectDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: ProjectDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: ProjectDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn render_message(kind: ProjectDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).message)
}

pub fn render_primary(kind: ProjectDiagKind, context: &DiagContext) -> String {
    context.render(entry(kind).primary)
}

pub fn secondary(kind: ProjectDiagKind) -> Option<&'static str> {
    entry(kind).secondary
}

pub fn render_secondary(kind: ProjectDiagKind, context: &DiagContext) -> Option<String> {
    entry(kind)
        .secondary
        .map(|secondary| context.render(secondary))
}

pub fn help(kind: ProjectDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<ProjectDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

pub const fn project_error_kind(source: &crate::ProjectError) -> Option<ProjectDiagKind> {
    match source {
        crate::ProjectError::MissingManifest { .. } => Some(ProjectDiagKind::MissingManifest),
        crate::ProjectError::MissingManifestAncestor { .. } => {
            Some(ProjectDiagKind::MissingManifestAncestor)
        }
        crate::ProjectError::MissingPackageRoot { .. } => Some(ProjectDiagKind::MissingPackageRoot),
        crate::ProjectError::MissingModule { .. } => Some(ProjectDiagKind::MissingModule),
        crate::ProjectError::InvalidManifestJson { .. } => {
            Some(ProjectDiagKind::InvalidManifestJson)
        }
        crate::ProjectError::SourceDiagnostic(_) => None,
        crate::ProjectError::ProjectIoFailed { .. } => Some(ProjectDiagKind::ProjectIoFailed),
        crate::ProjectError::ManifestValidationFailed { .. } => {
            Some(ProjectDiagKind::ManifestValidationFailed)
        }
        crate::ProjectError::DuplicateWorkspaceMember { .. } => {
            Some(ProjectDiagKind::DuplicateWorkspaceMember)
        }
        crate::ProjectError::DuplicatePackageName { .. } => {
            Some(ProjectDiagKind::DuplicatePackageName)
        }
        crate::ProjectError::MissingPackageVersion { .. } => {
            Some(ProjectDiagKind::MissingPackageVersion)
        }
        crate::ProjectError::NoRootPackage => Some(ProjectDiagKind::NoRootPackage),
        crate::ProjectError::MissingPackageEntryModule { .. } => {
            Some(ProjectDiagKind::MissingPackageEntryModule)
        }
        crate::ProjectError::UnknownTask { .. } => Some(ProjectDiagKind::UnknownTask),
        crate::ProjectError::TaskDependencyCycle { .. } => {
            Some(ProjectDiagKind::TaskDependencyCycle)
        }
        crate::ProjectError::PackageDependencyCycle { .. } => {
            Some(ProjectDiagKind::PackageDependencyCycle)
        }
        crate::ProjectError::UnresolvedImport { .. } => Some(ProjectDiagKind::UnresolvedImport),
        crate::ProjectError::UnknownPackage { .. } => Some(ProjectDiagKind::UnknownPackage),
        crate::ProjectError::PackageGraphEntryMissing { .. } => {
            Some(ProjectDiagKind::PackageGraphEntryMissing)
        }
        crate::ProjectError::MissingRegistryRoot { .. } => {
            Some(ProjectDiagKind::MissingRegistryRoot)
        }
        crate::ProjectError::MissingGlobalCacheRoot => {
            Some(ProjectDiagKind::MissingGlobalCacheRoot)
        }
        crate::ProjectError::RegistryVersionNotFound { .. } => {
            Some(ProjectDiagKind::RegistryVersionNotFound)
        }
        crate::ProjectError::InvalidVersionRequirement { .. } => {
            Some(ProjectDiagKind::InvalidVersionRequirement)
        }
        crate::ProjectError::InvalidGitDependency { .. } => {
            Some(ProjectDiagKind::InvalidGitDependency)
        }
        crate::ProjectError::GitCommandFailed { .. } => Some(ProjectDiagKind::GitCommandFailed),
        crate::ProjectError::GitReferenceNotFound { .. } => {
            Some(ProjectDiagKind::GitReferenceNotFound)
        }
        crate::ProjectError::MissingFrozenLockfile { .. } => {
            Some(ProjectDiagKind::MissingFrozenLockfile)
        }
        crate::ProjectError::FrozenLockfileOutOfDate { .. } => {
            Some(ProjectDiagKind::FrozenLockfileOutOfDate)
        }
        crate::ProjectError::SessionCompilationFailed(_) => {
            Some(ProjectDiagKind::SessionCompilationFailed)
        }
    }
}
