// @generated by musi_diaggen. Do not edit by hand.

use super::ResolveDiagKind;

struct CatalogEntry {
    kind: ResolveDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: ResolveDiagKind::ExpectedName,
        code: 3200,
        message: "expected binding name",
        primary: "expected binding name here",
        help: None,
    },
    CatalogEntry {
        kind: ResolveDiagKind::InvalidStmt,
        code: 3201,
        message: "invalid top-level statement",
        primary: "top-level item or expression expected here",
        help: None,
    },
    CatalogEntry {
        kind: ResolveDiagKind::UnboundName,
        code: 3202,
        message: "unbound name `{name}`",
        primary: "name `{name}` unresolved in this scope",
        help: None,
    },
    CatalogEntry {
        kind: ResolveDiagKind::ImportResolveFailed,
        code: 3203,
        message: "unresolved source import specifier `{spec}`",
        primary: "import environment lacks specifier `{spec}`",
        help: None,
    },
    CatalogEntry {
        kind: ResolveDiagKind::InvalidImportSpec,
        code: 3204,
        message: "invalid import specifier",
        primary: "string literal import specifier expected here",
        help: None,
    },
];

fn entry(kind: ResolveDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: ResolveDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: ResolveDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: ResolveDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn help(kind: ResolveDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<ResolveDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}
