use super::*;

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Opcode {
    LdLoc = 0x00,
    LdConst = 0x01,
    LdGlob = 0x02,
    LdUpv = 0x03,
    LdUnit = 0x04,
    LdTru = 0x05,
    LdFls = 0x06,
    LdSmi = 0x07,
    StLoc = 0x08,
    StGlob = 0x09,
    StUpv = 0x0A,
    LdLocW = 0x0B,
    StLocW = 0x0C,
    Pop = 0x10,
    Dup = 0x11,
    Swap = 0x12,
    Rot = 0x13,
    IAdd = 0x14,
    ISub = 0x15,
    IMul = 0x16,
    IDiv = 0x17,
    IRem = 0x18,
    INeg = 0x19,
    FAdd = 0x1A,
    FSub = 0x1B,
    FMul = 0x1C,
    FDiv = 0x1D,
    FNeg = 0x1E,
    And = 0x1F,
    Or = 0x20,
    Not = 0x21,
    Xor = 0x22,
    Shl = 0x23,
    Shr = 0x24,
    CmpEq = 0x25,
    CmpNeq = 0x26,
    CmpLt = 0x27,
    CmpGt = 0x28,
    CmpLeq = 0x29,
    CmpGeq = 0x2A,
    BrTrue = 0x2B,
    BrFalse = 0x2C,
    BrJmp = 0x2D,
    BrTbl = 0x2E,
    Call = 0x31,
    CallTail = 0x32,
    Ret = 0x33,
    ClsNew = 0x34,
    SeqNew = 0x37,
    SeqGet = 0x38,
    SeqSet = 0x39,
    SeqLen = 0x3A,
    SeqSlice = 0x3B,
    SeqFill = 0x3F,
    SeqCopy = 0x40,
    SeqConcat = 0x41,
    DataNew = 0x42,
    DataGet = 0x43,
    DataSet = 0x44,
    DataTag = 0x45,
    TyChk = 0x4A,
    TyCast = 0x4B,
    TyId = 0x4C,
    HdlPush = 0x4E,
    HdlPop = 0x4F,
    EffInvk = 0x50,
    EffCont = 0x51,
    FfiCall = 0x58,
}

pub const ALL_OPCODES: &[Opcode] = &[
    Opcode::LdLoc,
    Opcode::LdConst,
    Opcode::LdGlob,
    Opcode::LdUpv,
    Opcode::LdUnit,
    Opcode::LdTru,
    Opcode::LdFls,
    Opcode::LdSmi,
    Opcode::StLoc,
    Opcode::StGlob,
    Opcode::StUpv,
    Opcode::LdLocW,
    Opcode::StLocW,
    Opcode::Pop,
    Opcode::Dup,
    Opcode::Swap,
    Opcode::Rot,
    Opcode::IAdd,
    Opcode::ISub,
    Opcode::IMul,
    Opcode::IDiv,
    Opcode::IRem,
    Opcode::INeg,
    Opcode::FAdd,
    Opcode::FSub,
    Opcode::FMul,
    Opcode::FDiv,
    Opcode::FNeg,
    Opcode::And,
    Opcode::Or,
    Opcode::Not,
    Opcode::Xor,
    Opcode::Shl,
    Opcode::Shr,
    Opcode::CmpEq,
    Opcode::CmpNeq,
    Opcode::CmpLt,
    Opcode::CmpGt,
    Opcode::CmpLeq,
    Opcode::CmpGeq,
    Opcode::BrTrue,
    Opcode::BrFalse,
    Opcode::BrJmp,
    Opcode::BrTbl,
    Opcode::Call,
    Opcode::CallTail,
    Opcode::Ret,
    Opcode::ClsNew,
    Opcode::SeqNew,
    Opcode::SeqGet,
    Opcode::SeqSet,
    Opcode::SeqLen,
    Opcode::SeqSlice,
    Opcode::SeqFill,
    Opcode::SeqCopy,
    Opcode::SeqConcat,
    Opcode::DataNew,
    Opcode::DataGet,
    Opcode::DataSet,
    Opcode::DataTag,
    Opcode::TyChk,
    Opcode::TyCast,
    Opcode::TyId,
    Opcode::HdlPush,
    Opcode::HdlPop,
    Opcode::EffInvk,
    Opcode::EffCont,
    Opcode::FfiCall,
];

impl Opcode {
    #[must_use]
    pub const fn to_byte(self) -> u8 {
        match self {
            Self::LdLoc => 0x00,
            Self::LdConst => 0x01,
            Self::LdGlob => 0x02,
            Self::LdUpv => 0x03,
            Self::LdUnit => 0x04,
            Self::LdTru => 0x05,
            Self::LdFls => 0x06,
            Self::LdSmi => 0x07,
            Self::StLoc => 0x08,
            Self::StGlob => 0x09,
            Self::StUpv => 0x0A,
            Self::LdLocW => 0x0B,
            Self::StLocW => 0x0C,
            Self::Pop => 0x10,
            Self::Dup => 0x11,
            Self::Swap => 0x12,
            Self::Rot => 0x13,
            Self::IAdd => 0x14,
            Self::ISub => 0x15,
            Self::IMul => 0x16,
            Self::IDiv => 0x17,
            Self::IRem => 0x18,
            Self::INeg => 0x19,
            Self::FAdd => 0x1A,
            Self::FSub => 0x1B,
            Self::FMul => 0x1C,
            Self::FDiv => 0x1D,
            Self::FNeg => 0x1E,
            Self::And => 0x1F,
            Self::Or => 0x20,
            Self::Not => 0x21,
            Self::Xor => 0x22,
            Self::Shl => 0x23,
            Self::Shr => 0x24,
            Self::CmpEq => 0x25,
            Self::CmpNeq => 0x26,
            Self::CmpLt => 0x27,
            Self::CmpGt => 0x28,
            Self::CmpLeq => 0x29,
            Self::CmpGeq => 0x2A,
            Self::BrTrue => 0x2B,
            Self::BrFalse => 0x2C,
            Self::BrJmp => 0x2D,
            Self::BrTbl => 0x2E,
            Self::Call => 0x31,
            Self::CallTail => 0x32,
            Self::Ret => 0x33,
            Self::ClsNew => 0x34,
            Self::SeqNew => 0x37,
            Self::SeqGet => 0x38,
            Self::SeqSet => 0x39,
            Self::SeqLen => 0x3A,
            Self::SeqSlice => 0x3B,
            Self::SeqFill => 0x3F,
            Self::SeqCopy => 0x40,
            Self::SeqConcat => 0x41,
            Self::DataNew => 0x42,
            Self::DataGet => 0x43,
            Self::DataSet => 0x44,
            Self::DataTag => 0x45,
            Self::TyChk => 0x4A,
            Self::TyCast => 0x4B,
            Self::TyId => 0x4C,
            Self::HdlPush => 0x4E,
            Self::HdlPop => 0x4F,
            Self::EffInvk => 0x50,
            Self::EffCont => 0x51,
            Self::FfiCall => 0x58,
        }
    }

    #[must_use]
    pub const fn family(self) -> OpcodeFamily {
        match self {
            Self::LdLoc
            | Self::LdConst
            | Self::LdGlob
            | Self::LdUpv
            | Self::LdUnit
            | Self::LdTru
            | Self::LdFls
            | Self::LdSmi
            | Self::StLoc
            | Self::StGlob
            | Self::StUpv
            | Self::LdLocW
            | Self::StLocW => OpcodeFamily::Data,
            Self::Pop | Self::Dup | Self::Swap | Self::Rot => OpcodeFamily::Stack,
            Self::IAdd
            | Self::ISub
            | Self::IMul
            | Self::IDiv
            | Self::IRem
            | Self::INeg
            | Self::FAdd
            | Self::FSub
            | Self::FMul
            | Self::FDiv
            | Self::FNeg => OpcodeFamily::Scalar,
            Self::And | Self::Or | Self::Not | Self::Xor | Self::Shl | Self::Shr => {
                OpcodeFamily::Logic
            }
            Self::CmpEq
            | Self::CmpNeq
            | Self::CmpLt
            | Self::CmpGt
            | Self::CmpLeq
            | Self::CmpGeq => OpcodeFamily::Compare,
            Self::BrTrue | Self::BrFalse | Self::BrJmp | Self::BrTbl => OpcodeFamily::Branch,
            Self::Call | Self::CallTail | Self::Ret | Self::ClsNew => OpcodeFamily::Call,
            Self::SeqNew
            | Self::SeqGet
            | Self::SeqSet
            | Self::SeqLen
            | Self::SeqSlice
            | Self::SeqFill
            | Self::SeqCopy
            | Self::SeqConcat => OpcodeFamily::Sequence,
            Self::DataNew | Self::DataGet | Self::DataSet | Self::DataTag => {
                OpcodeFamily::Aggregate
            }
            Self::TyChk | Self::TyCast | Self::TyId => OpcodeFamily::Type,
            Self::HdlPush | Self::HdlPop | Self::EffInvk | Self::EffCont => OpcodeFamily::Effect,
            Self::FfiCall => OpcodeFamily::Runtime,
        }
    }

    #[must_use]
    pub const fn mnemonic(self) -> &'static str {
        match self {
            Self::LdLoc => "ld.loc",
            Self::LdConst => "ld.const",
            Self::LdGlob => "ld.glob",
            Self::LdUpv => "ld.upv",
            Self::LdUnit => "ld.unit",
            Self::LdTru => "ld.tru",
            Self::LdFls => "ld.fls",
            Self::LdSmi => "ld.smi",
            Self::StLoc => "st.loc",
            Self::StGlob => "st.glob",
            Self::StUpv => "st.upv",
            Self::LdLocW => "ld.loc.w",
            Self::StLocW => "st.loc.w",
            Self::Pop => "pop",
            Self::Dup => "dup",
            Self::Swap => "swap",
            Self::Rot => "rot",
            Self::IAdd => "i.add",
            Self::ISub => "i.sub",
            Self::IMul => "i.mul",
            Self::IDiv => "i.div",
            Self::IRem => "i.rem",
            Self::INeg => "i.neg",
            Self::FAdd => "f.add",
            Self::FSub => "f.sub",
            Self::FMul => "f.mul",
            Self::FDiv => "f.div",
            Self::FNeg => "f.neg",
            Self::And => "and",
            Self::Or => "or",
            Self::Not => "not",
            Self::Xor => "xor",
            Self::Shl => "shl",
            Self::Shr => "shr",
            Self::CmpEq => "cmp.eq",
            Self::CmpNeq => "cmp.neq",
            Self::CmpLt => "cmp.lt",
            Self::CmpGt => "cmp.gt",
            Self::CmpLeq => "cmp.leq",
            Self::CmpGeq => "cmp.geq",
            Self::BrTrue => "br.true",
            Self::BrFalse => "br.false",
            Self::BrJmp => "br.jmp",
            Self::BrTbl => "br.tbl",
            Self::Call => "call",
            Self::CallTail => "call.tail",
            Self::Ret => "ret",
            Self::ClsNew => "cls.new",
            Self::SeqNew => "seq.new",
            Self::SeqGet => "seq.get",
            Self::SeqSet => "seq.set",
            Self::SeqLen => "seq.len",
            Self::SeqSlice => "seq.slice",
            Self::SeqFill => "seq.fill",
            Self::SeqCopy => "seq.copy",
            Self::SeqConcat => "seq.concat",
            Self::DataNew => "data.new",
            Self::DataGet => "data.get",
            Self::DataSet => "data.set",
            Self::DataTag => "data.tag",
            Self::TyChk => "ty.chk",
            Self::TyCast => "ty.cast",
            Self::TyId => "ty.id",
            Self::HdlPush => "hdl.push",
            Self::HdlPop => "hdl.pop",
            Self::EffInvk => "eff.invk",
            Self::EffCont => "eff.cont",
            Self::FfiCall => "ffi.call",
        }
    }

    #[must_use]
    pub const fn from_byte(byte: u8) -> Option<Self> {
        match byte {
            0x00 => Some(Self::LdLoc),
            0x01 => Some(Self::LdConst),
            0x02 => Some(Self::LdGlob),
            0x03 => Some(Self::LdUpv),
            0x04 => Some(Self::LdUnit),
            0x05 => Some(Self::LdTru),
            0x06 => Some(Self::LdFls),
            0x07 => Some(Self::LdSmi),
            0x08 => Some(Self::StLoc),
            0x09 => Some(Self::StGlob),
            0x0A => Some(Self::StUpv),
            0x0B => Some(Self::LdLocW),
            0x0C => Some(Self::StLocW),
            0x10 => Some(Self::Pop),
            0x11 => Some(Self::Dup),
            0x12 => Some(Self::Swap),
            0x13 => Some(Self::Rot),
            0x14 => Some(Self::IAdd),
            0x15 => Some(Self::ISub),
            0x16 => Some(Self::IMul),
            0x17 => Some(Self::IDiv),
            0x18 => Some(Self::IRem),
            0x19 => Some(Self::INeg),
            0x1A => Some(Self::FAdd),
            0x1B => Some(Self::FSub),
            0x1C => Some(Self::FMul),
            0x1D => Some(Self::FDiv),
            0x1E => Some(Self::FNeg),
            0x1F => Some(Self::And),
            0x20 => Some(Self::Or),
            0x21 => Some(Self::Not),
            0x22 => Some(Self::Xor),
            0x23 => Some(Self::Shl),
            0x24 => Some(Self::Shr),
            0x25 => Some(Self::CmpEq),
            0x26 => Some(Self::CmpNeq),
            0x27 => Some(Self::CmpLt),
            0x28 => Some(Self::CmpGt),
            0x29 => Some(Self::CmpLeq),
            0x2A => Some(Self::CmpGeq),
            0x2B => Some(Self::BrTrue),
            0x2C => Some(Self::BrFalse),
            0x2D => Some(Self::BrJmp),
            0x2E => Some(Self::BrTbl),
            0x31 => Some(Self::Call),
            0x32 => Some(Self::CallTail),
            0x33 => Some(Self::Ret),
            0x34 => Some(Self::ClsNew),
            0x37 => Some(Self::SeqNew),
            0x38 => Some(Self::SeqGet),
            0x39 => Some(Self::SeqSet),
            0x3A => Some(Self::SeqLen),
            0x3B => Some(Self::SeqSlice),
            0x3F => Some(Self::SeqFill),
            0x40 => Some(Self::SeqCopy),
            0x41 => Some(Self::SeqConcat),
            0x42 => Some(Self::DataNew),
            0x43 => Some(Self::DataGet),
            0x44 => Some(Self::DataSet),
            0x45 => Some(Self::DataTag),
            0x4A => Some(Self::TyChk),
            0x4B => Some(Self::TyCast),
            0x4C => Some(Self::TyId),
            0x4E => Some(Self::HdlPush),
            0x4F => Some(Self::HdlPop),
            0x50 => Some(Self::EffInvk),
            0x51 => Some(Self::EffCont),
            0x58 => Some(Self::FfiCall),
            _ => None,
        }
    }

    #[must_use]
    pub fn from_mnemonic(input: &str) -> Option<Self> {
        ALL_OPCODES
            .iter()
            .find(|opcode| opcode.mnemonic() == input)
            .copied()
    }
}
