// @generated by musi_diaggen. Do not edit by hand.

use super::IrDiagKind;

struct CatalogEntry {
    kind: IrDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: IrDiagKind::InvalidSurfaceTypeId,
        code: 3400,
        message: "invalid surface type identifier",
        primary: "invalid surface type identifier",
        help: None,
    },
    CatalogEntry {
        kind: IrDiagKind::LoweringRequiresSemaCleanModule,
        code: 3401,
        message: "IR lowering requires semantic-clean module",
        primary: "IR lowering requires semantic-clean module",
        help: None,
    },
    CatalogEntry {
        kind: IrDiagKind::LoweringInvariantViolated,
        code: 3402,
        message: "IR lowering invariant violated",
        primary: "IR lowering invariant violated",
        help: None,
    },
];

fn entry(kind: IrDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: IrDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: IrDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: IrDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn help(kind: IrDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<IrDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}
