// @generated by musi_diaggen. Do not edit by hand.

use super::VmDiagKind;

struct CatalogEntry {
    kind: VmDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: VmDiagKind::SeamDecodeFailed,
        code: 6100,
        message: "SEAM decode failed (`{detail}`)",
        primary: "SEAM decode failed",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidProgramShape,
        code: 6101,
        message: "invalid program shape (`{detail}`)",
        primary: "invalid program shape",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidTypeTerm,
        code: 6102,
        message: "invalid type term `{ty}` (`{detail}`)",
        primary: "invalid type term `{ty}`",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidSyntaxConstant,
        code: 6103,
        message: "invalid syntax constant (`{detail}`)",
        primary: "invalid syntax constant",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::VmInitializationRequired,
        code: 6104,
        message: "VM initialization required",
        primary: "VM initialization required",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::ModuleInitCycle,
        code: 6105,
        message: "module `{spec}` initialization cycle detected",
        primary: "module `{spec}` initialization cycle detected",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::ExportNotFound,
        code: 6106,
        message: "missing export `{export}` in `{module}`",
        primary: "missing export `{export}`",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::OpaqueExport,
        code: 6107,
        message: "opaque export `{export}` inaccessible from `{module}`",
        primary: "opaque export `{export}` inaccessible",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::NonCallableValue,
        code: 6108,
        message: "callable value expected, found `{found}`",
        primary: "callable value expected",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::MissingEntryProcedure,
        code: 6109,
        message: "missing entry procedure in `{module}`",
        primary: "missing entry procedure",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::StackEmpty,
        code: 6110,
        message: "{stack} stack empty",
        primary: "{stack} stack empty",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::OperandCountMismatch,
        code: 6111,
        message: "operand stack expected `{needed}` values, found `{available}`",
        primary: "operand stack has `{available}` values",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::IndexOutOfBounds,
        code: 6112,
        message: "{space} `{index}` out of bounds for `{owner}` with `{len}` entries",
        primary: "{space} `{index}` out of bounds",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidBranchTarget,
        code: 6113,
        message: "invalid branch target `{target}` in `{procedure}`",
        primary: "invalid branch target `{target}`",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidOperandForOpcode,
        code: 6114,
        message: "opcode `{opcode}` rejects operand shape `{found}`",
        primary: "opcode `{opcode}` rejects operand",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidValueKind,
        code: 6115,
        message: "value kind expected `{expected}`, found `{found}`",
        primary: "value kind `{found}` found",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidSequenceIndex,
        code: 6116,
        message: "invalid sequence index `{index}` for length `{len}`",
        primary: "invalid sequence index `{index}`",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::EmptySequenceIndexList,
        code: 6117,
        message: "sequence index list empty",
        primary: "sequence index list empty",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidRangeBounds,
        code: 6118,
        message: "range bounds expected integers, found `{start}` and `{end}`",
        primary: "invalid range bounds",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidRangeEvidence,
        code: 6119,
        message: "invalid range evidence for value kind `{found}`",
        primary: "invalid range evidence",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidRangeStep,
        code: 6120,
        message: "invalid range step (`{detail}`)",
        primary: "invalid range step",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::RangeMaterializeTooLarge,
        code: 6121,
        message: "range materialize length `{len}` exceeds limit `{limit}`",
        primary: "range materialize length `{len}` too large",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidDataIndex,
        code: 6122,
        message: "invalid data field index `{index}` for length `{len}`",
        primary: "invalid data field index `{index}`",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InvalidTypeCast,
        code: 6123,
        message: "type cast expected `{expected}`, found `{found}`",
        primary: "type cast found `{found}`",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::ArithmeticFailed,
        code: 6124,
        message: "arithmetic failed (`{detail}`)",
        primary: "arithmetic failed",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::ModuleLoadRejected,
        code: 6125,
        message: "module `{spec}` load rejected",
        primary: "module `{spec}` load rejected",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::ForeignCallRejected,
        code: 6126,
        message: "foreign call `{foreign}` rejected",
        primary: "foreign call `{foreign}` rejected",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::PointerIntrinsicFailed,
        code: 6127,
        message: "pointer intrinsic `{intrinsic}` failed (`{detail}`)",
        primary: "pointer intrinsic `{intrinsic}` failed",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::NativeCallFailed,
        code: 6128,
        message: "native call `{foreign}` failed during `{stage}` for `{subject}` (`{detail}`)",
        primary: "native call `{foreign}` failed",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::EffectRejected,
        code: 6129,
        message: "effect `{effect}` operation `{op}` rejected (`{reason}`)",
        primary: "effect `{effect}` rejected",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::RootModuleRequired,
        code: 6130,
        message: "VM root module required",
        primary: "VM root module required",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::MissingModuleSource,
        code: 6131,
        message: "missing VM module source `{spec}`",
        primary: "missing VM module source `{spec}`",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::CallArityMismatch,
        code: 6132,
        message: "call `{callee}` expected `{expected}` arguments, found `{found}`",
        primary: "call `{callee}` arity mismatch",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::HandlerFrameMissing,
        code: 6133,
        message: "missing handler `{handler_id}` frame depth `{frame_depth}`",
        primary: "missing handler `{handler_id}` frame",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::MissingMatchingHandlerPop,
        code: 6134,
        message: "missing matching `hdl.pop` in `{procedure}`",
        primary: "missing matching `hdl.pop`",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::HeapLimitExceeded,
        code: 6135,
        message: "heap limit `{limit}` exceeded with `{allocated}` allocated bytes",
        primary: "heap limit `{limit}` exceeded",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::HeapObjectTooLarge,
        code: 6136,
        message: "heap object size `{bytes}` exceeds limit `{limit}`",
        primary: "heap object size `{bytes}` too large",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::StackFrameLimitExceeded,
        code: 6137,
        message: "stack frame limit `{limit}` exceeded with `{frames}` frames",
        primary: "stack frame limit `{limit}` exceeded",
        help: None,
    },
    CatalogEntry {
        kind: VmDiagKind::InstructionBudgetExhausted,
        code: 6138,
        message: "instruction budget `{budget}` exhausted",
        primary: "instruction budget `{budget}` exhausted",
        help: None,
    },
];

fn entry(kind: VmDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: VmDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: VmDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: VmDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn help(kind: VmDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<VmDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

pub const fn vm_error_kind(source: &crate::VmErrorKind) -> VmDiagKind {
    match source {
        crate::VmErrorKind::SeamDecodeFailed { .. } => VmDiagKind::SeamDecodeFailed,
        crate::VmErrorKind::InvalidProgramShape { .. } => VmDiagKind::InvalidProgramShape,
        crate::VmErrorKind::InvalidTypeTerm { .. } => VmDiagKind::InvalidTypeTerm,
        crate::VmErrorKind::InvalidSyntaxConstant { .. } => VmDiagKind::InvalidSyntaxConstant,
        crate::VmErrorKind::VmInitializationRequired => VmDiagKind::VmInitializationRequired,
        crate::VmErrorKind::ModuleInitCycle { .. } => VmDiagKind::ModuleInitCycle,
        crate::VmErrorKind::ExportNotFound { .. } => VmDiagKind::ExportNotFound,
        crate::VmErrorKind::OpaqueExport { .. } => VmDiagKind::OpaqueExport,
        crate::VmErrorKind::NonCallableValue { .. } => VmDiagKind::NonCallableValue,
        crate::VmErrorKind::MissingEntryProcedure { .. } => VmDiagKind::MissingEntryProcedure,
        crate::VmErrorKind::StackEmpty { .. } => VmDiagKind::StackEmpty,
        crate::VmErrorKind::OperandCountMismatch { .. } => VmDiagKind::OperandCountMismatch,
        crate::VmErrorKind::IndexOutOfBounds { .. } => VmDiagKind::IndexOutOfBounds,
        crate::VmErrorKind::InvalidBranchTarget { .. } => VmDiagKind::InvalidBranchTarget,
        crate::VmErrorKind::InvalidOperandForOpcode { .. } => VmDiagKind::InvalidOperandForOpcode,
        crate::VmErrorKind::InvalidValueKind { .. } => VmDiagKind::InvalidValueKind,
        crate::VmErrorKind::InvalidSequenceIndex { .. } => VmDiagKind::InvalidSequenceIndex,
        crate::VmErrorKind::EmptySequenceIndexList => VmDiagKind::EmptySequenceIndexList,
        crate::VmErrorKind::InvalidRangeBounds { .. } => VmDiagKind::InvalidRangeBounds,
        crate::VmErrorKind::InvalidRangeEvidence { .. } => VmDiagKind::InvalidRangeEvidence,
        crate::VmErrorKind::InvalidRangeStep { .. } => VmDiagKind::InvalidRangeStep,
        crate::VmErrorKind::RangeMaterializeTooLarge { .. } => VmDiagKind::RangeMaterializeTooLarge,
        crate::VmErrorKind::InvalidDataIndex { .. } => VmDiagKind::InvalidDataIndex,
        crate::VmErrorKind::InvalidTypeCast { .. } => VmDiagKind::InvalidTypeCast,
        crate::VmErrorKind::ArithmeticFailed { .. } => VmDiagKind::ArithmeticFailed,
        crate::VmErrorKind::ModuleLoadRejected { .. } => VmDiagKind::ModuleLoadRejected,
        crate::VmErrorKind::ForeignCallRejected { .. } => VmDiagKind::ForeignCallRejected,
        crate::VmErrorKind::PointerIntrinsicFailed { .. } => VmDiagKind::PointerIntrinsicFailed,
        crate::VmErrorKind::NativeCallFailed { .. } => VmDiagKind::NativeCallFailed,
        crate::VmErrorKind::EffectRejected { .. } => VmDiagKind::EffectRejected,
        crate::VmErrorKind::RootModuleRequired => VmDiagKind::RootModuleRequired,
        crate::VmErrorKind::MissingModuleSource { .. } => VmDiagKind::MissingModuleSource,
        crate::VmErrorKind::CallArityMismatch { .. } => VmDiagKind::CallArityMismatch,
        crate::VmErrorKind::HandlerFrameMissing { .. } => VmDiagKind::HandlerFrameMissing,
        crate::VmErrorKind::MissingMatchingHandlerPop { .. } => VmDiagKind::MissingMatchingHandlerPop,
        crate::VmErrorKind::HeapLimitExceeded { .. } => VmDiagKind::HeapLimitExceeded,
        crate::VmErrorKind::HeapObjectTooLarge { .. } => VmDiagKind::HeapObjectTooLarge,
        crate::VmErrorKind::StackFrameLimitExceeded { .. } => VmDiagKind::StackFrameLimitExceeded,
        crate::VmErrorKind::InstructionBudgetExhausted { .. } => VmDiagKind::InstructionBudgetExhausted,
    }
}
