// @generated by musi_diaggen. Do not edit by hand.

use super::ToolingDiagKind;

struct CatalogEntry {
    kind: ToolingDiagKind,
    code: u16,
    message: &'static str,
    primary: &'static str,
    help: Option<&'static str>,
}

const ENTRIES: &[CatalogEntry] = &[
    CatalogEntry {
        kind: ToolingDiagKind::MissingEntrySource,
        code: 5100,
        message: "missing entry source `{path}`",
        primary: "missing entry source `{path}`",
        help: None,
    },
    CatalogEntry {
        kind: ToolingDiagKind::PackageImportRequiresMusi,
        code: 5101,
        message: "import specifier `{spec}` requires `musi` package context",
        primary: "import specifier `{spec}` requires package context",
        help: None,
    },
    CatalogEntry {
        kind: ToolingDiagKind::MissingImport,
        code: 5102,
        message: "missing import specifier `{spec}` from `{path}`",
        primary: "missing import specifier `{spec}`",
        help: None,
    },
    CatalogEntry {
        kind: ToolingDiagKind::ToolingIoFailed,
        code: 5103,
        message: "tooling path `{path}` I/O failed (`{source}`)",
        primary: "tooling path `{path}` I/O failed",
        help: None,
    },
    CatalogEntry {
        kind: ToolingDiagKind::SessionCompilationFailed,
        code: 5104,
        message: "tooling session compilation failed (`{source}`)",
        primary: "tooling session compilation failed",
        help: None,
    },
];

fn entry(kind: ToolingDiagKind) -> &'static CatalogEntry {
    ENTRIES
        .iter()
        .find(|entry| entry.kind == kind)
        .expect("missing generated diagnostic catalog entry")
}

pub fn code(kind: ToolingDiagKind) -> u16 {
    entry(kind).code
}

pub fn message(kind: ToolingDiagKind) -> &'static str {
    entry(kind).message
}

pub fn primary(kind: ToolingDiagKind) -> &'static str {
    entry(kind).primary
}

pub fn help(kind: ToolingDiagKind) -> Option<&'static str> {
    entry(kind).help
}

pub fn from_code(raw: u16) -> Option<ToolingDiagKind> {
    ENTRIES
        .iter()
        .find(|entry| entry.code == raw)
        .map(|entry| entry.kind)
}

pub const fn tooling_error_kind(source: &crate::ToolingError) -> ToolingDiagKind {
    match source {
        crate::ToolingError::MissingEntrySource { .. } => ToolingDiagKind::MissingEntrySource,
        crate::ToolingError::PackageImportRequiresMusi { .. } => ToolingDiagKind::PackageImportRequiresMusi,
        crate::ToolingError::MissingImport { .. } => ToolingDiagKind::MissingImport,
        crate::ToolingError::ToolingIoFailed { .. } => ToolingDiagKind::ToolingIoFailed,
        crate::ToolingError::SessionCompilationFailed(_) => ToolingDiagKind::SessionCompilationFailed,
    }
}
